### ISSUE TITLE
Game crashes before exiting the launcher after every single driver update. (Linux)

### ISSUE THREAD

**Issue by AAVVIronAlex** [minecraft-linux/mcpelauncher-manifest#902] opened 2023-10-13 16:49 UTC
20:47:23 Info  [Launcher] Version: client 26bb56c / manifest 6273250
20:47:23 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
20:47:23 Info  [Launcher] CPU supports SSSE3: YES
20:47:23 Trace [Launcher] Loading hybris libraries
20:47:23 Trace [Launcher] linker loaded
20:47:23 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /home/earthmapspictures/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
20:47:23 Trace [REDIRECT] /data/data/app/proc/79/cmdline to /home/earthmapspictures/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
20:47:23 Trace [REDIRECT] /data/data/app/bin/mcpelauncher-client to /home/earthmapspictures/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
20:47:23 Trace [REDIRECT] /data/data to /home/earthmapspictures/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/
20:47:23 Trace [REDIRECT] . to /home/earthmapspictures/.var/app/io.mrarm.mcpelauncher/data/mcpelauncher/versions/1.16.40.02/assets/
20:47:23 Trace [LinkerUtils] Loaded OS library libm.so.6
20:47:23 Trace [LinkerUtils] Loaded OS library libz.so.1
20:47:23 Trace [LinkerUtils] Loaded OS library /app/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
20:47:23 Info  [Launcher] Loading gamepad mappings
20:47:23 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
20:47:23 Trace [Launcher] Loading gamepad mappings: /app/share/mcpelauncher/gamecontrollerdb.txt
20:47:23 Info  [Launcher] Creating window
terminate called after throwing an instance of 'std::runtime_error'
  what():  EGL: Failed to create window surface: An unrecognized attribute or attribute value was passed in the attribute list
Signal 6 received
Backtrace elements: 16
#0 /app/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0x12c) [0x5574a5d95c6c]
#1 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f100) [0x7f188523f100]
#2 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x91204) [0x7f1885291204]
#3 /usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e) [0x7f188523f04e]
#4 /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7) [0x7f18852287fc]
#5 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9a59) [0x7f18856a9a59]
#6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb577a) [0x7f18856b577a]
#7 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb57e5) [0x7f18856b57e5]
#8 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0x7f18856b5a70]
#9 /app/bin/mcpelauncher-client(_ZN14GLFWGameWindowC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii11GraphicsApi+0x317) [0x5574a5d9fdf7]
#10 /app/bin/mcpelauncher-client(_ZN17GLFWWindowManager12createWindowERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii11GraphicsApi+0x47) [0x5574a5d9d207]
#11 /app/bin/mcpelauncher-client(_ZN10FakeLooper16initializeWindowEv+0x1f7) [0x5574a5d75437]
#12 /app/bin/mcpelauncher-client(main+0x2663) [0x5574a5c56753]
#13 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2958a) [0x7f188522958a]
#14 /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7f188522964b]
#15 /app/bin/mcpelauncher-client(_start+0x25) [0x5574a5c53a55]
Dumping stack...
program failed with unix signal number: 6

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2023-10-14 13:19
So now you have this bug https://github.com/glfw/glfw/issues/2365

**Issues I cannot reproduce on old nvidia cards / intel uhd needs external contributors / testers**

**Comment by ChristopherHX** [comment] 2023-11-08 20:29
Closed as fixed in v0.12.0 (flatpak)

**Closed as completed by ChristopherHX** 2023-11-08 20:29 UTC
Labels: bug
