### ISSUE TITLE
std::runtime::error

### ISSUE THREAD

**Issue by 0had0** [minecraft-linux/mcpelauncher-manifest#302] opened 2020-05-18 17:28 UTC
20:25:58 Info  [Launcher] Version: client c735370 / manifest b3dd620
20:25:58 Info  [Launcher] CPU: GenuineIntel         Intel(R) Celeron(R) CPU 1017U @ 1.60GHz
20:25:58 Info  [Launcher] CPU supports SSSE3: YES
20:25:58 Trace [Launcher] Loading hybris libraries
20:25:58 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:25:58 Trace [HybrisUtils] Loaded OS library libm.so.6
20:25:58 Trace [HybrisUtils] Loaded OS library libz.so.1
20:25:58 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /tmp/.mount_Minecry9C1lm/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82f3a0f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fbeb60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fbeb49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf7663e66]
#4 /usr/lib32/libc.so.6(abort+0x12d) [0xf764c3f2]
#5 /usr/lib32/libstdc++.so.6(+0x75980) [0xf799e980]
#6 /usr/lib32/libstdc++.so.6(+0x837c7) [0xf79ac7c7]
#7 /usr/lib32/libstdc++.so.6(+0x83853) [0xf79ac853]
#8 /usr/lib32/libstdc++.so.6(+0x83bb5) [0xf79acbb5]
#9 /tmp/.mount_Minecry9C1lm/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14c) [0x82f4b52]
#10 /tmp/.mount_Minecry9C1lm/usr/bin/./mcpelauncher-client(main+0xece) [0x829e6b0]
#11 /usr/lib32/libc.so.6(__libc_start_main+0x10e) [0xf764defe]
#12 /tmp/.mount_Minecry9C1lm/usr/bin/./mcpelauncher-client() [0x829d311]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-01 21:15
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:15 UTC
Labels: bug, crash, duplicate, legacy (unsupported)
