### ISSUE TITLE
Launcher binary doesn't work on macOS

### ISSUE THREAD

**Issue by realSmushyTaco** [minecraft-linux/mcpelauncher-manifest#120] opened 2019-07-14 23:45 UTC
When using the binary for the macOS Minecraft Bedrock Launcher it keeps giving me the 

Could not find the game launcher. Please make sure it's properly installed (it must exist in the PATH variable used when starting this program).
Click here for help and additional information.

error but I didn't build from source so I have no idea why I keep getting this error. I'm currently on macOS 10.15 beta 3. I think it's because Catalina drops 32bit support, have you tried putting your application in an emulator? Bluestacks seems to be able to run Minecraft PE on Catalina so I assume it's possible to do so with this.

**Comment by filfat** [comment] 2019-07-16 22:58
Duplicate of #100

**Closed** 2019-07-31 08:44 UTC
