### ISSUE TITLE
Error opening Minecraft in version 1.14 and above.

### ISSUE THREAD

**Issue by GabrielGamer0** [minecraft-linux/mcpelauncher-manifest#300] opened 2020-05-11 00:19 UTC
20:14:23 Info  [Launcher] Version: client c735370 / manifest b3dd620
20:14:23 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz
20:14:23 Info  [Launcher] CPU supports SSSE3: YES
20:14:23 Trace [Launcher] Loading hybris libraries
20:14:23 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MAINDryTbT/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:14:23 Trace [HybrisUtils] Loaded OS library libm.so.6
20:14:23 Trace [HybrisUtils] Loaded OS library libz.so.1
20:14:23 Trace [Launcher] Loading Minecraft library
20:14:24 Info  [Launcher] Loaded Minecraft library
20:14:24 Debug [Launcher] Minecraft is at offset 0xee3e0000
20:14:24 Trace [Launcher] Initializing vtables
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
20:14:24 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
20:14:24 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82f3a0f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f39090]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f39079]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7635832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7636cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf799197d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7999174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf79991dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf79994dc]
#9 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0xf1) [0x833cacc]
#10 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x1f) [0x82f4dad]
#11 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x31) [0x82f4ceb]
#12 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client(main+0xf82) [0x829e764]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7620e81]
#14 /tmp/.mount_MAINDryTbT/usr/bin/./mcpelauncher-client() [0x829d311]
Dumping stack...
#2 HYBRIS (null)+-236786816 in libminecraftpe.so+0x3a4eb80 [0xf1e2eb80]
#13 HYBRIS (null)+-297926656 in libminecraftpe.so+0x0000 [0xee3e0000]
#32 HYBRIS (null)+-236754912 in libminecraftpe.so+0x3a56820 [0xf1e36820]
#33 HYBRIS (null)+-236754960 in libminecraftpe.so+0x3a567f0 [0xf1e367f0]
#37 HYBRIS (null)+-236743488 in libminecraftpe.so+0x3a594c0 [0xf1e394c0]
#38 HYBRIS (null)+-236743536 in libminecraftpe.so+0x3a59490 [0xf1e39490]
#108 HYBRIS (null)+-287481620 in libminecraftpe.so+0x9f60ec [0xeedd60ec]
#112 HYBRIS (null)+-174875196 in libminecraftpe.so+0x7559dc4 [0xf5939dc4]
#114 HYBRIS (null)+-175765244 in libminecraftpe.so+0x7480904 [0xf5860904]
#118 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5607bb6 [0xf39e7bb6]
#119 HYBRIS (null)+-175765244 in libminecraftpe.so+0x7480904 [0xf5860904]
#120 HYBRIS Core::Result::makeFailureWithStringLiteral(char const*)+114 in libminecraftpe.so+0x3e0bf62 [0xf21ebf62]
#122 HYBRIS (null)+-174875208 in libminecraftpe.so+0x7559db8 [0xf5939db8]
#124 HYBRIS (null)+-174875196 in libminecraftpe.so+0x7559dc4 [0xf5939dc4]
#126 HYBRIS (null)+-232863456 in libminecraftpe.so+0x3e0c920 [0xf21ec920]
#127 HYBRIS (null)+-174875196 in libminecraftpe.so+0x7559dc4 [0xf5939dc4]
#129 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74f9be8 [0xf58d9be8]
#130 HYBRIS (null)+-175765244 in libminecraftpe.so+0x7480904 [0xf5860904]
#132 HYBRIS Core::StorageAreasTree::insertStorageArea(Core::FileStorageArea&)+316 in libminecraftpe.so+0x3df9e1c [0xf21d9e1c]
#137 HYBRIS (null)+-236532144 in libminecraftpe.so+0x3a8ce50 [0xf1e6ce50]
#143 HYBRIS (null)+-236532048 in libminecraftpe.so+0x3a8ceb0 [0xf1e6ceb0]
#647 HYBRIS (null)+-297926656 in libminecraftpe.so+0x0000 [0xee3e0000]
Process exited with unexpected exit code: 6

My Desktop:
-Procesor:Intel i3 
-Ram: 4GB Ram
-OpenGL: 2.1
-Graphics Driver: Ironlake
-OS: Linux Mint 19.2 Tinha (Ubuntu 18.04)

**Comment by ChristopherHX** [comment] 2020-06-01 22:09
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:09 UTC
Labels: crash, duplicate, legacy (unsupported)
