### ISSUE TITLE
Game crashes when I try to launch it

### ISSUE THREAD

**Issue by PR0WN3D** [minecraft-linux/mcpelauncher-manifest#307] opened 2020-05-21 06:22 UTC
02:13:48 Info  [Launcher] Version: client c735370 / manifest eb0bc83
02:13:48 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
02:13:48 Info  [Launcher] CPU supports SSSE3: YES
02:13:48 Trace [Launcher] Loading hybris libraries
02:13:48 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
02:13:48 Trace [HybrisUtils] Loaded OS library libm.dylib
02:13:48 Error [HybrisUtils] Failed to load OS library libz.so.1
02:13:48 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 9

**Comment by PR0WN3D** [comment] 2020-05-21 06:28
02:26:55 Info  [Launcher] Version: client c735370 / manifest eb0bc83
02:26:55 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
02:26:55 Info  [Launcher] CPU supports SSSE3: YES
02:26:55 Trace [Launcher] Loading hybris libraries
02:26:55 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
02:26:55 Trace [HybrisUtils] Loaded OS library libm.dylib
02:26:55 Error [HybrisUtils] Failed to load OS library libz.so.1
02:26:55 Trace [Launcher] Loading Minecraft library
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: load_library[1115]: Library '/Users/PR0WN3D/Library/Application Support/mcpelauncher/versions/1.14.60.5/libs/libminecraftpe.so' not found
Signal 6 received
Backtrace elements: 12
#0 0   mcpelauncher-client                 0x0010288e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7cc6bae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7b8080e abort + 133
#4 4   libc++abi.dylib                     0xa5a45177 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa5a4531f _ZL25default_terminate_handlerv + 232
#6 6   libc++abi.dylib                     0xa5a501fd _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa5a4ffbc __cxa_get_exception_ptr + 0
#8 8   libc++abi.dylib                     0xa5a43a01 __cxa_get_globals + 0
#9 9   mcpelauncher-client                 0x00103ddf _ZN14MinecraftUtils16loadMinecraftLibERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 1439
#10 10  mcpelauncher-client                 0x0004869a main + 9962
#11 11  libdyld.dylib                       0xa7add051 start + 1
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-05-23 11:36
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/309#issuecomment-633031390

**Comment by ChristopherHX** [comment] 2020-06-01 21:36
duplicate of #271

The second post is a bit different, but has same solution as the first

**Closed by ChristopherHX** 2020-06-01 21:36 UTC
Labels: bug, crash, duplicate, legacy (unsupported)
