### ISSUE TITLE
Crashes when I click start macOS 10.13.6

### ISSUE THREAD

**Issue by ScribbleNerd** [minecraft-linux/mcpelauncher-manifest#324] opened 2020-06-05 04:56 UTC
23:54:59 Info  [Launcher] Version: client c735370 / manifest eb0bc83
23:54:59 Info  [Launcher] CPU: GenuineIntel         Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
23:54:59 Info  [Launcher] CPU supports SSSE3: YES
23:54:59 Trace [Launcher] Loading hybris libraries
23:54:59 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
23:54:59 Trace [HybrisUtils] Loaded OS library libm.dylib
23:54:59 Error [HybrisUtils] Failed to load OS library libz.so.1
23:54:59 Trace [Launcher] Loading Minecraft library
linkerlibc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 11
#0 0   mcpelauncher-client                 0x0016a88e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa757d02b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa731e956 abort + 133
#4 4   libc++abi.dylib                     0xa56dcea7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa56dd06a _ZL25default_terminate_handlerv + 250
#6 6   libc++abi.dylib                     0xa56f6657 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa56f60c1 __cxa_throw + 116
#8 8   mcpelauncher-client                 0x0016bddf _ZN14MinecraftUtils16loadMinecraftLibERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 1439
#9 9   mcpelauncher-client                 0x000b069a main + 9962
#10 10  libdyld.dylib                       0xa7274611 start + 1
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-05 22:48
duplicate of #271, please use my fork

**Closed by ChristopherHX** 2020-06-05 22:48 UTC
