### ISSUE TITLE
game wont start

### ISSUE THREAD

**Issue by vitimilocity** [minecraft-linux/mcpelauncher-manifest#225] opened 2020-01-26 17:00 UTC
11:00:07 Info  [Launcher] Version: client c735370 / manifest e405b8c
11:00:07 Info  [Launcher] CPU: AuthenticAMD AMD Athlon(tm) II X4 635 Processor
11:00:07 Info  [Launcher] CPU supports SSSE3: NO
11:00:07 Trace [Launcher] Loading hybris libraries
11:00:07 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
11:00:07 Trace [HybrisUtils] Loaded OS library libm.so.6
11:00:07 Trace [HybrisUtils] Loaded OS library libz.so.1
11:00:07 Trace [Launcher] Loading Minecraft library
11:00:08 Info  [Launcher] Loaded Minecraft library
11:00:08 Debug [Launcher] Minecraft is at offset 0xe8603000
11:00:08 Trace [Launcher] Initializing vtables
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
11:00:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
11:00:08 Trace [AppPlatform] Vtable size = 295
11:00:08 Trace [Store] Vtable size = 39
11:00:08 Info  [Launcher] Game version: 1.14.1
11:00:08 Info  [Launcher] Applying patches
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 131
11:00:08 Trace [Patch] Patching - result: 233 202 152 132 109
11:00:08 Trace [Patch] Patching - original: 83 87 86 131 236
11:00:08 Trace [Patch] Patching - result: 233 55 59 135 109
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 173 120 202 105
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 221 192 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 51 209 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 167 189 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 239 36 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 251 24 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 225 76 10 106
11:00:08 Trace [Patch] Patching - original: 83 87 86 131 236
11:00:08 Trace [Patch] Patching - result: 233 47 184 8 106
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 129
11:00:08 Trace [Patch] Patching - result: 233 235 226 8 106
11:00:08 Trace [Patch] Patching - original: 83 131 236 8 232
11:00:08 Trace [Patch] Patching - result: 233 63 193 38 106
11:00:08 Trace [Patch] Patching - original: 137 76 36 4 137
11:00:08 Trace [Patch] Patching - result: 232 227 202 219 105
11:00:08 Trace [Patch] Patching - original: 36 88 139 65 12
11:00:08 Trace [Patch] Patching - result: 232 238 202 219 105
11:00:08 Trace [Patch] Patching - original: 85 83 87 86 131
11:00:08 Trace [Patch] Patching - result: 233 136 69 194 105
11:00:08 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
11:00:08 Info  [Launcher] Creating window
11:00:08 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
11:00:08 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
11:00:08 Trace [Launcher] Initializing AppPlatform (create instance)
11:00:08 Trace [Launcher] Initializing AppPlatform (initialize call)
11:00:08 Trace [AppPlatform] createDeviceID (from file): 48ba9ddf-db40-4c34-97ae-d5fb0a03fb4c
11:00:08 Trace [Launcher] Initializing MinecraftGame (create instance)
11:00:08 Trace [Launcher] Initializing MinecraftGame (init call)
11:00:08 Info  [Launcher] Game initialized
libevdev_new_from_fd error -22 (/dev/input/js0)
11:00:08 Trace [WindowCallbacks] Gamepad connected #0
11:00:08 Trace [AppPlatform] getDataUrl: /home/miller/.local/share/mcpelauncher/versions/1.14.1.5/assets/
11:00:08 Error [LauncherAppPlatform] readAssetFile: not found: /home/miller/.local/share/mcpelauncher/versions/1.14.1.5/assets/skin_packs/vanilla/contents.json
11:00:08 Error [LauncherAppPlatform] readAssetFile: not found: /home/miller/.local/share/mcpelauncher/versions/1.14.1.5/assets/skin_packs/persona/contents.json
11:00:08 Error [LauncherAppPlatform] readAssetFile: not found: /home/miller/.local/share/mcpelauncher/versions/1.14.1.5/assets/skin_packs/persona/geometry.json
Process exited with unexpected exit code: 4

**Comment by ChristopherHX** [comment] 2020-06-03 14:35
Unfortunately you have an unsupported CPU ( very old amd, without SSSE3 ), newer amd (2012+) seems to be working
duplicate of #24

**Closed by ChristopherHX** 2020-06-03 14:35 UTC
