### ISSUE TITLE
"Minecraft has exited with a non-zero error code."

### ISSUE THREAD

**Issue by OCActivated** [minecraft-linux/mcpelauncher-manifest#257] opened 2020-03-25 11:27 UTC
Game Version : 1.14.30.2
14:16:12 Info  [Launcher] Version: client c735370 / manifest e405b8c
14:16:12 Info  [Launcher] CPU: GenuineIntel       Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
14:16:12 Info  [Launcher] CPU supports SSSE3: YES
14:16:12 Trace [Launcher] Loading hybris libraries
14:16:12 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
14:16:12 Trace [HybrisUtils] Loaded OS library libm.so.6
14:16:12 Trace [HybrisUtils] Loaded OS library libz.so.1
14:16:12 Trace [Launcher] Loading Minecraft library
14:16:13 Info  [Launcher] Loaded Minecraft library
14:16:13 Debug [Launcher] Minecraft is at offset 0xed7df000
14:16:13 Trace [Launcher] Initializing vtables
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
14:16:13 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
14:16:13 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567b9e41]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fd5b70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fd5b59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf78b6832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf78b7cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7c1497d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760e4) [0xf7c1c0e4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7614d) [0xf7c1c14d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7644c) [0xf7c1c44c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x5680e5b1]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567bb63a]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567bb532]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567625de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf78a1e81]
#14 /usr/bin/mcpelauncher-client(+0x1c8f31) [0x56760f31]
Dumping stack...
#2 HYBRIS (null)+-249369616 in libminecraftpe.so+0x3a4fbf0 [0xf122ebf0]
#13 HYBRIS (null)+-310513664 in libminecraftpe.so+0x0000 [0xed7df000]
#32 HYBRIS (null)+-249337712 in libminecraftpe.so+0x3a57890 [0xf1236890]
#33 HYBRIS (null)+-249337760 in libminecraftpe.so+0x3a57860 [0xf1236860]
#37 HYBRIS (null)+-249326288 in libminecraftpe.so+0x3a5a530 [0xf1239530]
#38 HYBRIS (null)+-249326336 in libminecraftpe.so+0x3a5a500 [0xf1239500]
#77 HYBRIS (null)+-249192832 in libminecraftpe.so+0x3a7ae80 [0xf1259e80]
#78 HYBRIS (null)+-249192880 in libminecraftpe.so+0x3a7ae50 [0xf1259e50]
#108 HYBRIS (null)+-300068372 in libminecraftpe.so+0x9f61ec [0xee1d51ec]
#112 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#114 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#118 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf2de7c36]
#119 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#122 HYBRIS (null)+-187458120 in libminecraftpe.so+0x755adb8 [0xf4d39db8]
#124 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#126 HYBRIS (null)+-245446240 in libminecraftpe.so+0x3e0d9a0 [0xf15ec9a0]
#127 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#129 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74fabf8 [0xf4cd9bf8]
#137 HYBRIS (null)+-249114944 in libminecraftpe.so+0x3a8dec0 [0xf126cec0]
#651 HYBRIS (null)+-310513664 in libminecraftpe.so+0x0000 [0xed7df000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-03-25 20:18
Works as designed by the dev.
These Versions works with this repository 0.12-1.13.0.6, 1.13.0.15, 1.13.0.34, 1.14.1.3 and 1.14.1.5
Try my version if you wish to run them anyways
Link under github forks .

**Comment by ChristopherHX** [comment] 2020-06-01 22:04
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:04 UTC
