### ISSUE TITLE
Error while extracting the file: Failed to open zip 21

### ISSUE THREAD

**Issue by KamenkoTV** [minecraft-linux/mcpelauncher-manifest#333] opened 2020-06-13 21:38 UTC
Error while extracting the file: Failed to open zip 21
i have x86 - 32bit apk but it still doesnt work

**Comment by crimsoncandy** [comment] 2020-06-21 18:12
Having the same issue with latest 1.14.60.5 version, beta don't work either.

**Comment by ChristopherHX** [comment] 2020-06-22 09:30
It would be worth to just login to google.
We don't support piracy (random apks from the internet).
You can also use the aurora store app to get valid apks.

**Comment by KamenkoTV** [comment] 2020-06-24 08:38
> aurora store

well i can't get Minecraft or buy it via Google play it says that the game is not avaliable in my country.

**Comment by ChristopherHX** [comment] 2020-06-24 11:42
> well i can't get Minecraft or buy it via Google play
piracy is still illegal in my country, whatever reason you have.
The 10th duplicate of #258, which is itself a duplicate

**Closed by ChristopherHX** 2020-06-24 11:42 UTC

**Comment by crimsoncandy** [comment] 2020-06-24 13:22
@ChristopherHX Is it safe to login through Google and download Minecraft? Isn't it against Google's ToS to download app from sources other than play store, Aurora store clearly state this. Will I get any bans on my google account? I'm kind of nervous about this as I have used my hard earned google opinion rewards credit to buy the Minecraft after about one year of waiting and can't afford to lose as I have no other means of paying (I'm kid).

**Comment by ChristopherHX** [comment] 2020-06-24 14:15
Maybe all your mentioned things can happen to you.
I cannot say you would never get a ban.
I never got banned for using this since last year (before last year I haven't found it or used it), but I cannot predict the future and won't guaranty anything.
You don't have to use this software, you can play it on android and stay save.

Using an android x86 vm or emulator on a pc and extract the apk manually should work too.

The Aurora store people won't want to be liable for any harm that could happen like myself.
