### ISSUE TITLE
I cant seem to Import APKs

### ISSUE THREAD

**Issue by RedcatPhoenix2** [minecraft-linux/mcpelauncher-manifest#292] opened 2020-04-28 14:33 UTC
![Screenshot 2020-04-28 at 10 23 17 AM](https://user-images.githubusercontent.com/62823569/80500013-a6a30a00-893b-11ea-9578-7e8c07d27476.png)

**Comment by ChristopherHX** [comment] 2020-06-08 11:49
duplicate of #258
Random modified pirated apk's are not supported

**Closed by ChristopherHX** 2020-06-08 11:49 UTC
