### ISSUE TITLE
1.14x not playable

### ISSUE THREAD

**Issue by Tiixxel** [minecraft-linux/mcpelauncher-manifest#201] opened 2019-12-10 19:28 UTC
**Getting this when I try to start the version:**
20:26:25 Info  [Launcher] Version: client c735370 / manifest 4d4d51a
20:26:25 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
20:26:25 Info  [Launcher] CPU supports SSSE3: YES
20:26:25 Trace [Launcher] Loading hybris libraries
20:26:25 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:26:25 Trace [HybrisUtils] Loaded OS library libm.so.6
20:26:25 Trace [HybrisUtils] Loaded OS library libz.so.1
20:26:25 Trace [Launcher] Loading Minecraft library
20:26:25 Info  [Launcher] Loaded Minecraft library
20:26:25 Debug [Launcher] Minecraft is at offset 0xdd7cd000
20:26:25 Trace [Launcher] Initializing vtables
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
20:26:25 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
20:26:25 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x566b26fc]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7efcb60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7efcb49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf776eb06]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf77573f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7aa593e]
#6 /usr/lib32/libstdc++.so.6(+0x839e7) [0xf7ab39e7]
#7 /usr/lib32/libstdc++.so.6(+0x83a63) [0xf7ab3a63]
#8 /usr/lib32/libstdc++.so.6(+0x83d95) [0xf7ab3d95]
#9 /usr/bin/mcpelauncher-client(+0x4c6d8) [0x5667b6d8]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x566b35ef]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x5668034c]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf9) [0xf7758fa9]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x56681be5]
Dumping stack...
#3 HYBRIS (null)+-518702864 in libminecraftpe.so+0x39868f0 [0xe11538f0]
#5 HYBRIS (null)+-579022848 in libminecraftpe.so+0x0000 [0xdd7cd000]
#23 HYBRIS (null)+-518687632 in libminecraftpe.so+0x398a470 [0xe1157470]
#24 HYBRIS (null)+-518698352 in libminecraftpe.so+0x3987a90 [0xe1154a90]
#28 HYBRIS (null)+-518683840 in libminecraftpe.so+0x398b340 [0xe1158340]
#29 HYBRIS (null)+-518687536 in libminecraftpe.so+0x398a4d0 [0xe11574d0]
#69 HYBRIS (null)+-518616992 in libminecraftpe.so+0x399b860 [0xe1168860]
#102 HYBRIS (null)+-457451920 in libminecraftpe.so+0x73f0670 [0xe4bbd670]
#103 HYBRIS (null)+-518547504 in libminecraftpe.so+0x39ac7d0 [0xe11797d0]
#104 HYBRIS (null)+-518554528 in libminecraftpe.so+0x39aac60 [0xe1177c60]
#108 HYBRIS (null)+-518547360 in libminecraftpe.so+0x39ac860 [0xe1179860]
#109 HYBRIS (null)+-518547408 in libminecraftpe.so+0x39ac830 [0xe1179830]
#112 HYBRIS (null)+-570166881 in libminecraftpe.so+0x87219f [0xde03f19f]
#113 HYBRIS (null)+-518529120 in libminecraftpe.so+0x39b0fa0 [0xe117dfa0]
#114 HYBRIS (null)+-518532816 in libminecraftpe.so+0x39b0130 [0xe117d130]
#118 HYBRIS (null)+-518525328 in libminecraftpe.so+0x39b1e70 [0xe117ee70]
#119 HYBRIS (null)+-518529024 in libminecraftpe.so+0x39b1000 [0xe117e000]
#122 HYBRIS (null)+-457836068 in libminecraftpe.so+0x73929dc [0xe4b5f9dc]
#123 HYBRIS (null)+-518525184 in libminecraftpe.so+0x39b1f00 [0xe117ef00]
#124 HYBRIS (null)+-518525232 in libminecraftpe.so+0x39b1ed0 [0xe117eed0]
#128 HYBRIS (null)+-518512048 in libminecraftpe.so+0x39b5250 [0xe1182250]
#129 HYBRIS (null)+-518513808 in libminecraftpe.so+0x39b4b70 [0xe1181b70]
#132 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0x9fe0ac [0xde1cb0ac]
#133 HYBRIS (null)+-518504464 in libminecraftpe.so+0x39b6ff0 [0xe1183ff0]
#134 HYBRIS (null)+-518511952 in libminecraftpe.so+0x39b52b0 [0xe11822b0]
#138 HYBRIS (null)+-518497344 in libminecraftpe.so+0x39b8bc0 [0xe1185bc0]
#139 HYBRIS (null)+-518504368 in libminecraftpe.so+0x39b7050 [0xe1184050]
#143 HYBRIS (null)+-518489760 in libminecraftpe.so+0x39ba960 [0xe1187960]
#144 HYBRIS (null)+-518497248 in libminecraftpe.so+0x39b8c20 [0xe1185c20]
#148 HYBRIS (null)+-518478944 in libminecraftpe.so+0x39bd3a0 [0xe118a3a0]
#149 HYBRIS (null)+-518489664 in libminecraftpe.so+0x39ba9c0 [0xe11879c0]
#153 HYBRIS (null)+-518475152 in libminecraftpe.so+0x39be270 [0xe118b270]
#154 HYBRIS (null)+-518478848 in libminecraftpe.so+0x39bd400 [0xe118a400]
#158 HYBRIS (null)+-518471360 in libminecraftpe.so+0x39bf140 [0xe118c140]
#159 HYBRIS (null)+-518475056 in libminecraftpe.so+0x39be2d0 [0xe118b2d0]
#162 HYBRIS (null)+-457836068 in libminecraftpe.so+0x73929dc [0xe4b5f9dc]
#163 HYBRIS (null)+-518469424 in libminecraftpe.so+0x39bf8d0 [0xe118c8d0]
#164 HYBRIS (null)+-518471264 in libminecraftpe.so+0x39bf1a0 [0xe118c1a0]
#168 HYBRIS (null)+-518465632 in libminecraftpe.so+0x39c07a0 [0xe118d7a0]
#169 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#172 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#173 HYBRIS (null)+-518465535 in libminecraftpe.so+0x39c0801 [0xe118d801]
#175 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#177 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#178 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#180 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#181 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#183 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#184 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#186 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#187 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#189 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#190 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#192 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#193 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#195 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#196 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#198 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#199 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#201 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#202 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#204 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#205 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#207 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#208 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#210 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#211 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#213 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#214 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#216 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#217 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#219 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#220 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#222 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#223 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#225 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#226 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#228 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#229 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#231 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#232 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#234 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#235 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#237 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#238 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#240 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#241 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#243 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#244 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#246 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#247 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#249 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#250 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#252 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#253 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#255 HYBRIS (null)+-488968716 in libminecraftpe.so+0x55e1df4 [0xe2daedf4]
#259 HYBRIS (null)+-488968959 in libminecraftpe.so+0x55e1d01 [0xe2daed01]
#513 HYBRIS (null)+-566165494 in libminecraftpe.so+0xc4300a [0xde41000a]
#778 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x7356e88 [0xe4b23e88]
#779 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7356e90 [0xe4b23e90]
#799 HYBRIS (null)+-579022848 in libminecraftpe.so+0x0000 [0xdd7cd000]
Process exited with unexpected exit code: 6

**Comment by thijs** [comment] 2019-12-10 19:29
Look at the other issues with 1.13, it's because Mojang removed debug symbols from the released code. There's an alternative fork that uses a different system (https://github.com/ChristopherHX/mcpelauncher-manifest), but that has some issues as well... At least it starts 1.14 for me...

**Comment by ChrisR009** [comment] 2019-12-14 09:34
https://pastebin.com/Yx6Aa1HV

**Comment by ChristopherHX** [comment] 2020-06-01 21:51
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:51 UTC
