### ISSUE TITLE
Can't log into google account

### ISSUE THREAD

**Issue by jurassicjordan** [minecraft-linux/mcpelauncher-manifest#211] opened 2019-12-26 19:54 UTC
hi when I try to log in to my google account it says "this browser or app may not be secure
try a different browser. if you're already using a supported browser, you can refresh your screen and try again to sign in"

I'm playing on Mac OS Sierrra Ver 10.12.6 on a macbook pro mid 2014 with Nvidia GT 750M
The launcher obviously needs an update because google seems to have updated its services
this is only one of 2 issues i have.

**Comment by ChristopherHX** [comment] 2020-02-11 13:24
Look here for workaround
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903

**Comment by KevDoy** [comment] 2020-04-05 03:40
I am also having this issue.

**Comment by ChristopherHX** [comment] 2020-07-16 20:11
duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/140
**only not fixed in the macOS dmg of the wiki**

**Closed by ChristopherHX** 2020-07-16 20:11 UTC
