### ISSUE TITLE
Minecraft PE 1.12.1.1 crashes on startup [Arch] with a non-zero error code

### ISSUE THREAD

**Issue by ItsSapphire** [minecraft-linux/mcpelauncher-manifest#148] opened 2019-09-10 01:44 UTC
OS: Arch Linux on Zen kernel
Way of installing launcher: AUR
Minecraft Version: 1.12.1.1

Hi everyone,
When I try running Minecraft PE [1.12.1.1] using the mcpelauncher-linux-git and mcpelauncher-ui-git AUR packages the game crashes on startup.

Here is the log:
20:39:59 Info  [Launcher] Version: client a48cb4c / manifest d9cc8d9
20:39:59 Info  [Launcher] CPU: AuthenticAMD AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G   
20:39:59 Info  [Launcher] CPU supports SSSE3: YES
20:39:59 Trace [Launcher] Loading hybris libraries
20:39:59 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:39:59 Trace [HybrisUtils] Loaded OS library libm.so.6
20:39:59 Trace [HybrisUtils] Loaded OS library libz.so.1
20:39:59 Trace [Launcher] Loading Minecraft library
20:40:01 Info  [Launcher] Loaded Minecraft library
20:40:01 Debug [Launcher] Minecraft is at offset 0xe5316000
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC2ESt8functionIFSsvEE
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EP15FilePathManagerSt10shared_ptrI22SaveTransactionManagerE
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManagerC2ESsb
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager11getRootPathEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getUserDataPathEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager13getWorldsPathEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager14setPackagePathESs
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager14getPackagePathEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN15FilePathManager15setSettingsPathESs
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZNK15FilePathManager15getSettingsPathEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2EP7Options
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderP15FilePathManagerR17PackSourceFactoryb
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKSs
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManagerb
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISZ_EER9SchedulerEERKSsP9LevelDataSsSsSY_I16EducationOptionsS10_IS1B_EEPSV_SX_IFvS18_EES1G_P13ServerMetricsP13DebugEndPoint
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
20:40:01 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
Signal 11 received
Backtrace elements: 6
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x5666b52c]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f1c970]
#2 /usr/bin/mcpelauncher-client(_Z22minecraft_symbols_initPv+0x1c29) [0x56697cf9]
#3 /usr/bin/mcpelauncher-client(main+0xc44) [0x56639274]
#4 /usr/lib32/libc.so.6(__libc_start_main+0xf9) [0xf77338b9]
#5 /usr/bin/mcpelauncher-client(_start+0x35) [0x5663a915]
Dumping stack...
#17 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x542ae4c [0xea740e4c]
#18 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5428b76 [0xea73eb76]
#19 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#20 HYBRIS Core::Result::makeFailureWithStringLiteral(char const*)+114 in libminecraftpe.so+0x3cce4c2 [0xe8fe44c2]
#26 HYBRIS (null)+-385987936 in libminecraftpe.so+0x3cceaa0 [0xe8fe4aa0]
#30 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#32 HYBRIS Core::FileSystem::cleanPathSeparators_deprecated(Core::PathBuffer<Core::StackString<char, 1024u> >&, Core::Path const&)+910 in libminecraftpe.so+0x3c9d76e [0xe8fb376e]
#100 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#101 HYBRIS (null)+-332306464 in libminecraftpe.so+0x70007e0 [0xec3167e0]
#102 HYBRIS (null)+-332306464 in libminecraftpe.so+0x70007e0 [0xec3167e0]
#105 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d14900 [0xe902a900]
#112 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x3d1750c [0xe902d50c]
#114 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#115 HYBRIS (null)+-332306464 in libminecraftpe.so+0x70007e0 [0xec3167e0]
#117 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x3d14900 [0xe902a900]
#118 HYBRIS (null)+-332306464 in libminecraftpe.so+0x70007e0 [0xec3167e0]
#119 HYBRIS (null)+-334475264 in libminecraftpe.so+0x6def000 [0xec105000]
#122 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#130 HYBRIS (null)+-332189512 in libminecraftpe.so+0x701d0b8 [0xec3330b8]
#131 HYBRIS (null)+-332306464 in libminecraftpe.so+0x70007e0 [0xec3167e0]
#171 HYBRIS (null)+-361162037 in libminecraftpe.so+0x547bacb [0xea791acb]
#172 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#175 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#176 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned int, unsigned int, std::__detail::_Hash_node<std::pair<std::string const, std::string>, true>*)+71 in libminecraftpe.so+0x15b69d7 [0xe68cc9d7]
#178 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x70019e0 [0xec3179e0]
#184 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x542ae67 [0xea740e67]
#188 HYBRIS xbox::services::serviceLocales+8 in libminecraftpe.so+0x70019d8 [0xec3179d8]
#189 HYBRIS (null)+-361136128 in libminecraftpe.so+0x5482000 [0xea798000]
#194 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#196 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+212 in libminecraftpe.so+0x20179a4 [0xe732d9a4]
#198 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#204 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x20178dc [0xe732d8dc]
#214 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#216 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Hashtable<std::pair<std::string const, std::string> const*>(std::pair<std::string const, std::string> const*, std::pair<std::string const, std::string> const*, unsigned int, std::hash<std::string> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<std::string> const&, std::__detail::_Select1st const&, std::allocator<std::pair<std::string const, std::string> > const&)+236 in libminecraftpe.so+0x290189c [0xe7c1789c]
#218 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#222 HYBRIS (null)+-360355727 in libminecraftpe.so+0x5540871 [0xea856871]
#224 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x542ae67 [0xea740e67]
#227 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#229 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x1660500 [0xe6976500]
#230 HYBRIS (null)+-332189512 in libminecraftpe.so+0x701d0b8 [0xec3330b8]
#231 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#238 HYBRIS (null)+-334871480 in libminecraftpe.so+0x6d8e448 [0xec0a4448]
#241 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x1660500 [0xe6976500]
#242 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#243 HYBRIS (null)+-334475264 in libminecraftpe.so+0x6def000 [0xec105000]
#248 HYBRIS (null)+-427619996 in libminecraftpe.so+0x151a964 [0xe6830964]
#249 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x1660500 [0xe6976500]
#250 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x70019d0 [0xec3179d0]
#251 HYBRIS (null)+-334475264 in libminecraftpe.so+0x6def000 [0xec105000]
#252 HYBRIS (null)+-427624833 in libminecraftpe.so+0x151967f [0xe682f67f]
#510 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x6d4b218 [0xec061218]
#527 HYBRIS (null)+-449748992 in libminecraftpe.so+0x0000 [0xe5316000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-07-14 20:59
duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/104

**Closed by ChristopherHX** 2020-07-14 20:59 UTC
