### ISSUE TITLE
Minecraft 1.14.30 is not starting

### ISSUE THREAD

**Issue by ItzLightyHD** [minecraft-linux/mcpelauncher-manifest#322] opened 2020-06-02 18:02 UTC
I'm just starting Minecraft 1.14.30 using an APK, but it doesn't start
![image](https://user-images.githubusercontent.com/45460688/83553754-fdd46580-a50b-11ea-8996-f04fcb3c1134.png)
This is the full log:
20:00:54 Info  [Launcher] Version: client c735370 / manifest b3dd620
20:00:54 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
20:00:54 Info  [Launcher] CPU supports SSSE3: YES
20:00:54 Trace [Launcher] Loading hybris libraries
20:00:54 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:00:54 Trace [HybrisUtils] Loaded OS library libm.so.6
20:00:54 Trace [HybrisUtils] Loaded OS library libz.so.1
20:00:54 Trace [Launcher] Loading Minecraft library
20:00:55 Info  [Launcher] Loaded Minecraft library
20:00:55 Debug [Launcher] Minecraft is at offset 0xed7df000
20:00:55 Trace [Launcher] Initializing vtables
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
20:00:55 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
20:00:55 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x5679b729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fc6b70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fc6b59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf78a5832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf78a6cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7c0397d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7c0b174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf7c0b1dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf7c0b4dc]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x567f0aa1]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x5679cf22]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x5679ce1a]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x5673779e]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7890e81]
#14 /usr/bin/mcpelauncher-client(+0x1dc0f1) [0x567360f1]
Dumping stack...
#1 HYBRIS (null)+-249515248 in libminecraftpe.so+0x3a2c310 [0xf120b310]
#13 HYBRIS (null)+-310513664 in libminecraftpe.so+0x0000 [0xed7df000]
#31 HYBRIS (null)+-249459904 in libminecraftpe.so+0x3a39b40 [0xf1218b40]
#34 HYBRIS (null)+-187964384 in libminecraftpe.so+0x74df420 [0xf4cbe420]
#35 HYBRIS (null)+-249445760 in libminecraftpe.so+0x3a3d280 [0xf121c280]
#36 HYBRIS (null)+-249452784 in libminecraftpe.so+0x3a3b710 [0xf121a710]
#40 HYBRIS (null)+-249445616 in libminecraftpe.so+0x3a3d310 [0xf121c310]
#75 HYBRIS (null)+-249388016 in libminecraftpe.so+0x3a4b410 [0xf122a410]
#110 HYBRIS (null)+-249348672 in libminecraftpe.so+0x3a54dc0 [0xf1233dc0]
#111 HYBRIS (null)+-249352368 in libminecraftpe.so+0x3a53f50 [0xf1232f50]
#115 HYBRIS (null)+-249337856 in libminecraftpe.so+0x3a57800 [0xf1236800]
#116 HYBRIS (null)+-249348576 in libminecraftpe.so+0x3a54e20 [0xf1233e20]
#120 HYBRIS (null)+-249337712 in libminecraftpe.so+0x3a57890 [0xf1236890]
#121 HYBRIS (null)+-249337760 in libminecraftpe.so+0x3a57860 [0xf1236860]
#125 HYBRIS (null)+-249326288 in libminecraftpe.so+0x3a5a530 [0xf1239530]
#126 HYBRIS (null)+-249326336 in libminecraftpe.so+0x3a5a500 [0xf1239500]
#130 HYBRIS (null)+-249304192 in libminecraftpe.so+0x3a5fb80 [0xf123eb80]
#131 HYBRIS (null)+-249314912 in libminecraftpe.so+0x3a5d1a0 [0xf123c1a0]
#134 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#135 HYBRIS (null)+-249303184 in libminecraftpe.so+0x3a5ff70 [0xf123ef70]
#136 HYBRIS (null)+-249304096 in libminecraftpe.so+0x3a5fbe0 [0xf123ebe0]
#140 HYBRIS (null)+-249303040 in libminecraftpe.so+0x3a60000 [0xf123f000]
#141 HYBRIS (null)+-249303088 in libminecraftpe.so+0x3a5ffd0 [0xf123efd0]
#144 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xee1edd5c]
#145 HYBRIS (null)+-249284176 in libminecraftpe.so+0x3a649b0 [0xf12439b0]
#146 HYBRIS (null)+-249291664 in libminecraftpe.so+0x3a62c70 [0xf1241c70]
#150 HYBRIS (null)+-249284032 in libminecraftpe.so+0x3a64a40 [0xf1243a40]
#151 HYBRIS (null)+-249284080 in libminecraftpe.so+0x3a64a10 [0xf1243a10]
#155 HYBRIS (null)+-249253632 in libminecraftpe.so+0x3a6c100 [0xf124b100]
#156 HYBRIS (null)+-249253680 in libminecraftpe.so+0x3a6c0d0 [0xf124b0d0]
#160 HYBRIS (null)+-249223232 in libminecraftpe.so+0x3a737c0 [0xf12527c0]
#161 HYBRIS (null)+-249223280 in libminecraftpe.so+0x3a73790 [0xf1252790]
#165 HYBRIS (null)+-249192832 in libminecraftpe.so+0x3a7ae80 [0xf1259e80]
#166 HYBRIS (null)+-249192880 in libminecraftpe.so+0x3a7ae50 [0xf1259e50]
#170 HYBRIS (null)+-249158784 in libminecraftpe.so+0x3a83380 [0xf1262380]
#171 HYBRIS (null)+-249162480 in libminecraftpe.so+0x3a82510 [0xf1261510]
#174 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#175 HYBRIS (null)+-249157776 in libminecraftpe.so+0x3a83770 [0xf1262770]
#176 HYBRIS (null)+-249158688 in libminecraftpe.so+0x3a833e0 [0xf12623e0]
#180 HYBRIS (null)+-249153984 in libminecraftpe.so+0x3a84640 [0xf1263640]
#184 HYBRIS std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_lookahead(std::__detail::_State<std::regex_traits<char> >)+531 in libminecraftpe.so+0xa0ed03 [0xee1edd03]
#185 HYBRIS (null)+-249143120 in libminecraftpe.so+0x3a870b0 [0xf12660b0]
#186 HYBRIS (null)+-249153888 in libminecraftpe.so+0x3a846a0 [0xf12636a0]
#196 HYBRIS (null)+-300068372 in libminecraftpe.so+0x9f61ec [0xee1d51ec]
#200 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#202 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#206 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf2de7c36]
#207 HYBRIS (null)+-188348156 in libminecraftpe.so+0x7481904 [0xf4c60904]
#210 HYBRIS (null)+-187458120 in libminecraftpe.so+0x755adb8 [0xf4d39db8]
#212 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#214 HYBRIS (null)+-245446240 in libminecraftpe.so+0x3e0d9a0 [0xf15ec9a0]
#215 HYBRIS (null)+-187458108 in libminecraftpe.so+0x755adc4 [0xf4d39dc4]
#217 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74fabf8 [0xf4cd9bf8]
#225 HYBRIS (null)+-249114944 in libminecraftpe.so+0x3a8dec0 [0xf126cec0]
#739 HYBRIS (null)+-310513664 in libminecraftpe.so+0x0000 [0xed7df000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-03 14:14
duplicate of #165

**Closed by ChristopherHX** 2020-06-03 14:14 UTC
