### ISSUE TITLE
Game Crash with PS4 controller

### ISSUE THREAD

**Issue by XM9G** [minecraft-linux/mcpelauncher-manifest#525] opened 2021-06-06 01:54 UTC
when I use my ps4 controller it crashes

**Comment by ChristopherHX** [comment] 2021-06-09 08:49
Incomplete Bug report.
Unknown OS.
Unknown CPU.
Unknown Minecraft Version.
Unknown Minecraft Architecture
Missing Gamelog of crash.

Duplicate of #510

**Closed by ChristopherHX** 2021-06-09 08:49 UTC
Labels: invalid
