### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Kariosphere** [minecraft-linux/mcpelauncher-manifest#195] opened 2019-11-19 13:17 UTC
Every time I start any version it says:
dyld: Library not loaded: /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
  Referenced from: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: mach-o, but wrong architecture
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: stat() failed with errno=45
	/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight: mach-o, but wrong architecture
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-04 08:27
duplicate of #180

**Closed by ChristopherHX** 2020-06-04 08:27 UTC
