### ISSUE TITLE
Process exited with unexpected exit code: 9

### ISSUE THREAD

**Issue by splimola** [minecraft-linux/mcpelauncher-manifest#310] opened 2020-05-24 01:32 UTC
Crashes when trying to launch game.  High Sierra 10.13.6.

```
21:25:57 Info  [Launcher] Version: client c735370 / manifest eb0bc83
21:25:57 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
21:25:57 Info  [Launcher] CPU supports SSSE3: YES
21:25:57 Trace [Launcher] Loading hybris libraries
21:25:57 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
21:25:57 Trace [HybrisUtils] Loaded OS library libm.dylib
21:25:57 Error [HybrisUtils] Failed to load OS library libz.so.1
21:25:57 Trace [Launcher] Loading Minecraft library
linkerlibc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
```

**Comment by ChristopherHX** [comment] 2020-06-01 21:16
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:16 UTC
