### ISSUE TITLE
Crash on load on both offline and online mode

### ISSUE THREAD

**Issue by infrustrationMC** [minecraft-linux/mcpelauncher-manifest#74] opened 2019-04-08 13:30 UTC
15:24:17 Info  [Launcher] Version: client b63fb08 / manifest fc11ccf
15:24:17 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
15:24:17 Info  [Launcher] CPU supports SSSE3: YES
15:24:17 Trace [Launcher] Loading hybris libraries
15:24:17 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
15:24:17 Trace [HybrisUtils] Loaded OS library libm.so.6
15:24:17 Trace [Launcher] Loading Minecraft library
15:24:19 Info  [Launcher] Loaded Minecraft library
15:24:19 Debug [Launcher] Minecraft is at offset 0xee325000
15:24:19 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFileP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteISY_EER9SchedulerEERKSsP9LevelDataSsSsSX_I16EducationOptionsSZ_IS1A_EEPSU_SW_IFvS17_EES1F_P28ServerCommunicationInterface
15:24:19 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
15:24:19 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
15:24:19 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFSsvEERK18ContentTierManager
15:24:19 Info  [Launcher] Game version: 1.11.0.9
15:24:19 Info  [Launcher] Applying patches
15:24:19 Trace [Store] Vtable size = 34
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 131
15:24:19 Trace [Patch] Patching - result: 233 3 97 218 102
15:24:19 Trace [Patch] Patching - original: 83 87 86 131 236
15:24:19 Trace [Patch] Patching - result: 233 169 86 60 102
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 1 48 50 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 49 113 112 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 135 129 112 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 251 109 112 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 23 217 111 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 157 214 111 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 55 15 114 100
15:24:19 Trace [Patch] Patching - original: 83 87 86 131 236
15:24:19 Trace [Patch] Patching - result: 233 117 118 112 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 49 161 112 100
15:24:19 Trace [Patch] Patching - original: 49 192 195 141 182
15:24:19 Trace [Patch] Patching - result: 233 157 48 212 102
15:24:19 Trace [Patch] Patching - original: 83 131 236 8 232
15:24:19 Trace [Patch] Patching - result: 233 193 249 141 100
15:24:19 Trace [Patch] Patching - original: 137 76 36 4 137
15:24:19 Trace [Patch] Patching - result: 232 12 18 67 100
15:24:19 Trace [Patch] Patching - original: 36 88 139 65 12
15:24:19 Trace [Patch] Patching - result: 232 23 18 67 100
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 131
15:24:19 Trace [Patch] Patching - result: 233 2 76 221 102
15:24:19 Trace [Patch] Patching - original: 85 83 87 86 129
15:24:19 Trace [Patch] Patching - result: 233 207 74 221 102
15:24:19 Trace [Patch] Patching - original: 83 87 86 131 236
15:24:19 Trace [Patch] Patching - result: 233 155 75 221 102
15:24:19 Trace [Patch] Patching - original: 85 137 229 83 87
15:24:19 Trace [Patch] Patching - result: 233 180 228 42 100
15:24:19 Trace [Patch] Patching - original: 83 86 131 236 20
15:24:19 Trace [Patch] Patching - result: 233 255 172 45 102
15:24:19 Trace [Patch] Patching - original: 232 109 196 182 253
15:24:19 Trace [Patch] Patching - result: 232 179 215 179 100
15:24:19 Info  [Launcher] Creating window
15:24:19 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
15:24:19 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
15:24:19 Trace [Launcher] Initializing AppPlatform (vtable)
15:24:19 Trace [AppPlatform] Vtable size = 260
15:24:19 Trace [Launcher] Initializing AppPlatform (create instance)
15:24:19 Trace [Launcher] Initializing AppPlatform (initialize call)
15:24:19 Trace [AppPlatform] createDeviceID (from file): eb0a77f8-e4ec-44ed-ba15-0970e465dfae
15:24:19 Info  [Launcher] OpenGL: version: OpenGL ES 3.2 Mesa 18.2.2, renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) x86/MMX/SSE2, vendor: Intel Open Source Technology Center
15:24:19 Trace [Launcher] Initializing MinecraftGame (create instance)
15:24:19 Trace [AppPlatform] getSystemRegion: en_US
15:24:19 Trace [Launcher] Initializing MinecraftGame (init call)
15:24:19 Info  [Launcher] Game initialized
15:24:19 Trace [AppPlatform] getDataUrl: /home/ptm2002/.local/share/mcpelauncher/versions/1.11.0.9/assets/
15:24:19 Info  [Cohtml] Initializing COHTML ver. 1.0.0.6
15:24:19 Debug [Cohtml] Opening task channel 2 on family 0
15:24:19 Debug [Cohtml] Opening task channel 0 on family 0
15:24:19 Info  [Cohtml] Coherent Renoir library initialized!
15:24:19 Info  [Cohtml] COHTML library initialized!
15:24:19 Debug [Cohtml] Opening task channel 2 on family 1
15:24:19 Info  [Cohtml] Failed to load dynamic library: MediaDecoders_Android.so with error: Cannot load library: load_library[1115]: Library 'libMediaDecoders_Android.so' not found
15:24:19 Debug [Cohtml] Inspector is disabled
15:24:19 Debug [Cohtml] Opening task channel 2 on family 2
15:24:19 Debug [Cohtml] Opening task channel 0 on family 2
15:24:19 Debug [Cohtml] Opening task channel 0 on family 1
15:24:19 Warn  [Cohtml] Unable to load default font name Noto Sans
15:24:19 Trace [AppPlatform] getDataUrl: /home/ptm2002/.local/share/mcpelauncher/versions/1.11.0.9/assets/
15:24:20 Trace [XboxLive] Reading xbox config file
15:24:20 Error [XSAPI.Android] java interop not initialized properly
15:24:20 Trace [Launcher] Creating store
15:24:20 Trace [Store] registerLicenseChangeCallback
15:24:20 Trace [Store] getStoreId: android.googleplay
15:24:20 Trace [Store] restoreFromCache
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -158552512] IPv4 supported, port: 34816
15:24:20 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -158552512] IPv6 supported, port: 42173
15:24:20 Trace [AppPlatform] isTablet: true
15:24:20 Trace [AppPlatform] getSystemRegion: en_US
15:24:20 Trace [AppPlatform] getApplicationId: com.mojang.minecraftpe
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Store] getStoreId: android.googleplay
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Debug [Cohtml] Force prunning all orphaned images.
15:24:20 Debug [Cohtml] Force prunning all orphaned svgs.
15:24:20 Trace [Store] getStoreId: android.googleplay
15:24:20 Trace [Store] receivedLicenseResponse: true
15:24:20 Trace [Store] isGameLicensed: true
15:24:20 Warn  [Store] getExtraLicenseData - not implemented
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:20 Debug [Cohtml] Force prunning all orphaned images.
15:24:20 Debug [Cohtml] Force prunning all orphaned svgs.
15:24:20 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
15:24:20 Trace [XboxLive] log_telemetry_signin 1 Entering
15:24:20 Trace [Launcher] init_sign_in_activity 1
15:24:20 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:22 Trace [Store] getStoreId: android.googleplay
15:24:22 Trace [Store] onPrimaryUserConnectedToPlatform
15:24:22 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -158552512] IPv4 supported, port: 32917
15:24:22 Info  [Minecraft] NO LOG FILE! - [INFO NETWORK -158552512] IPv6 supported, port: 51616
15:24:22 Trace [Store] queryProducts
15:24:22 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:23 Trace [Store] queryPurchases
15:24:23 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:23 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:23 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:38 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:38 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:38 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:38 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:38 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:38 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:39 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:41 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:43 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:44 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:44 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:44 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:46 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:46 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:47 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:48 Trace [Store] getStoreId: android.googleplay
15:24:48 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:48 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:50 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:51 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:51 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:51 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:51 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:51 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:51 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:51 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:51 Trace [XboxLive] verify_cert_chain_platform_specific stub called
15:24:55 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:56 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:56 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:56 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:24:56 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
**15:24:59 Info  [DaemonLauncher] Daemon file exists, but we could not open it (Failed to connect); starting the service anyways
terminate called after throwing an instance of 'std::runtime_error'
  what():  No active connection to send the message on**
Signal 6 received
Backtrace elements: 16
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x56784f83]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f89070]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f89059]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7860832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7861cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e91d) [0xf7bbe91d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760d4) [0xf7bc60d4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7613d) [0xf7bc613d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7643c) [0xf7bc643c]
#9 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client24unix_service_client_impl12send_messageERKNS_11rpc_messageE+0x6c) [0x5680474e]
#10 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client14service_client12send_messageERKNS_11rpc_messageE+0xf6) [0x56814d46]
#11 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client13rpc_json_call4callESt8functionIFvNS_10rpc_resultIN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbxydSaNS4_14adl_serializerEEEEEEE+0x174) [0x568199da]
#12 /usr/bin/mcpelauncher-client(_ZN9simpleipc6client8rpc_callISt10shared_ptrIN3msa6client5TokenEEE4callESt8functionIFvNS_10rpc_resultIS6_EEEE+0x73) [0x5676f047]
#13 /usr/bin/mcpelauncher-client(_ZN14XboxLiveHelper15requestXblTokenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbSt8functionIFvS7_S7_EES8_IFviS7_EE+0x172) [0x5676a702]
#14 /usr/bin/mcpelauncher-client(_ZN15XboxLivePatches18initSignInActivityEPN4xbox8services6system17user_auth_androidEi+0x2c1) [0x5674b6dd]
#15 HYBRIS xbox::services::system::user_auth_android::msa_sign_in()+170 in libminecraftpe.so+0x3d2c1ca [0xf20511ca]
Dumping stack...
#13 HYBRIS (null)+-298692608 in libminecraftpe.so+0x0000 [0xee325000]
#31 HYBRIS xbox::services::system::user_auth_android::msa_sign_in()+170 in libminecraftpe.so+0x3d2c1ca [0xf20511ca]
#878 HYBRIS (null)+-212426058 in libminecraftpe.so+0x52452b6 [0xf356a2b6]
#879 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#933 HYBRIS xbox::services::local_config::get_bool_from_config(std::string const&, bool, bool)+0 in libminecraftpe.so+0x3f4baf0 [0xf2270af0]
#941 HYBRIS (null)+-184554812 in libminecraftpe.so+0x6cd9ac4 [0xf4ffeac4]
#944 HYBRIS (null)+-184554812 in libminecraftpe.so+0x6cd9ac4 [0xf4ffeac4]
#946 HYBRIS (null)+-186651012 in libminecraftpe.so+0x6ad9e7c [0xf4dfee7c]
#948 HYBRIS xbox::services::local_config::get_bool_from_config(std::string const&, bool, bool)+0 in libminecraftpe.so+0x3f4baf0 [0xf2270af0]
#950 HYBRIS (null)+-212426058 in libminecraftpe.so+0x52452b6 [0xf356a2b6]
#951 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#968 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#972 HYBRIS xbox::services::system::user_auth_android::msa_sign_in()+170 in libminecraftpe.so+0x3d2c1ca [0xf20511ca]
#978 HYBRIS (null)+-184554824 in libminecraftpe.so+0x6cd9ab8 [0xf4ffeab8]
#980 HYBRIS (null)+-186706108 in libminecraftpe.so+0x6acc744 [0xf4df1744]
#981 HYBRIS (null)+-184554812 in libminecraftpe.so+0x6cd9ac4 [0xf4ffeac4]
#984 HYBRIS (null)+-186706108 in libminecraftpe.so+0x6acc744 [0xf4df1744]
#985 HYBRIS (null)+-184554812 in libminecraftpe.so+0x6cd9ac4 [0xf4ffeac4]
#986 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#987 HYBRIS (null)+-184554812 in libminecraftpe.so+0x6cd9ac4 [0xf4ffeac4]
#988 HYBRIS (null)+-184554824 in libminecraftpe.so+0x6cd9ab8 [0xf4ffeab8]
#990 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x51ebff6 [0xf3510ff6]
#991 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#994 HYBRIS (null)+-187214692 in libminecraftpe.so+0x6a5049c [0xf4d7549c]
#996 HYBRIS (null)+-234444137 in libminecraftpe.so+0x3d45a97 [0xf206aa97]
15:24:59 Trace [DaemonLauncher] Starting daemon: /usr/bin/msa-daemon
Process exited with unexpected exit code: 6
(The report would mess up if I put it as a code)

Sometimes I also get exit code 5 (3 times)

**Comment by MCMrARM** [comment] 2019-04-08 14:58
Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/73

**Closed by MCMrARM** 2019-04-08 14:58 UTC
