### ISSUE TITLE
1.18.30 - 1.19.20 is not compatible

### ISSUE THREAD

**Issue by ratchild5** [minecraft-linux/mcpelauncher-manifest#685] opened 2022-04-22 18:51 UTC
1.18.3 on bedrock is not yet compatible for the launcher. it's a little annoying considering i can't play with friends on servers or on worlds, so hopefully its become compatible soon. sorry if i seem impatient !

**Comment by p0ryae** [comment] 2022-04-23 21:10
You can still play in servers by using the last version, not the latest. 1.18.12 works very fine

**Comment by by5tark** [comment] 2022-04-26 06:07
1.18.12 doesnt work more

**Comment by wertie3020** [comment] 2022-05-03 13:08
the problem is android and windows auto update so all servers have to update to the latest version as fast as poseble becos atherwise they lose players

**Comment by CapLifter** [comment] 2022-05-08 18:14
When will this be fixed?

**Comment by wertie3020** [comment] 2022-05-09 09:36
i don't know but i hope soon

**Comment by RedsonBr140** [comment] 2022-05-10 10:47
@ChristopherHX what about?

**Comment by t1mest0ne** [comment] 2022-05-10 16:11
does anyone know if or when the latest version is going to be compatible with the launcher?

**Comment by RedsonBr140** [comment] 2022-08-10 11:50
I think you can close it now

**Comment by ChristopherHX** [comment] 2022-08-28 14:03
The 1.19, could be closed, because it is technically a duplicate of this one

1.18.30-1.19.21 is available for testing on flathub beta ( linux arm64 and amd64 devices ).
Known Issues
- The qt UI suggests to install the armeabi-v7 version of the game, while it shouldn't offer it on amd64 devices
  - Workaround 1: this workaround works as long 1.19.21 is the latest version of the game
    - Open Settings
    - Switch to the Dev Tab
    - Enable Show Unverifed versions
    - Now you can download and play 1.19.21
  - Workaround 2: to be documented
    - edit the profiles file and replace the versions code of an existing profile to 1.19.21 see https://github.com/minecraft-linux/mcpelauncher-versiondb/blob/master/versions.json
- Xbox Live Sign in is broken in the beta
  - you need to sign in with Minecraft 1.18.12 via the normal flatpak version
- Some Devices may freeze within a minute, you might be able to load a world and play for 5-10s
  - No workaround, **backup your worlds before upgrading or they are lost in 1.18.12**
- **1.19.30 is not compatible**

**Comment by ktheticdev** [comment] 2022-09-01 21:29
Even if I sign in in 1.18.12, 1.19.22 says that "there was a problem when signing in" (same with 1.18.12, btw, but here I can at least click "sign in" again), so I am unable to use Xbox Live. What could be the problem?

**Comment by ChristopherHX** [comment] 2022-09-02 08:46
> What could be the problem?

You pressing the sign in button, before auto sign in completes.
If you signed in successfully in 1.18.12, you just have to wait until the sign in button disappears in 1.19.21.
Otherwise someone can contribute to the xbox sign in logic of this launcher to improve it. As long it works for me nothing needs to be improved from my side.

**Comment by ktheticdev** [comment] 2022-09-08 10:18
> > What could be the problem?
> 
> You pressing the sign in button, before auto sign in completes. If you signed in successfully in 1.18.12, you just have to wait until the sign in button disappears in 1.19.21. Otherwise someone can contribute to the xbox sign in logic of this launcher to improve it. As long it works for me nothing needs to be improved from my side.

From what I've seen, it basically hangs and GNOME states that it's not responding.

**Comment by awuioebhjnd** [comment] 2022-09-13 18:06
I cant find 1.19.21 only 1.19.20.24 which is locked even on the dev unverified version and on the flat hub one. anyone know what im doing wrong?

**Comment by marshallishere** [comment] 2022-09-17 17:14
Hey, I was looking for the version 1.19.22, there's any update?

**Comment by ChristopherHX** [comment] 2022-09-25 08:06
> From what I've seen, it basically hangs and GNOME states that it's not responding.

If you mean the launcher with the title Minecraft, it is the known issue `"Some Devices may freeze within a minute, you might be able to load a world and play for 5-10s"`.

No clue what happens, running the same code outside of the flatpak sandbox kept responding on my device.
My other device didn't have this problem at all.

> I cant find 1.19.21 only 1.19.20.24 which is locked

Sounds like you downloaded a pirated old beta version of the game, otherwise I have no idea why you even have that beta of the game. Beta versions are locked behind another toggle.

**Comment by ChristopherHX** [comment] 2022-10-01 18:49
Closed via https://github.com/minecraft-linux/mcpelauncher-manifest/commit/4c7dadf29df543856db9b73f8a7b220e65d489a2

**Closed as completed by ChristopherHX** 2022-10-01 18:49 UTC
Labels: enhancement
