### ISSUE TITLE
Same

### ISSUE THREAD

**Issue by gosch2912** [minecraft-linux/mcpelauncher-manifest#295] opened 2020-05-01 06:32 UTC
10:10:50 Info  [Launcher] Version: client c735370 / manifest b3dd620
10:10:50 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
10:10:50 Info  [Launcher] CPU supports SSSE3: YES
10:10:50 Trace [Launcher] Loading hybris libraries
10:10:50 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
10:10:50 Trace [HybrisUtils] Loaded OS library libm.so.6
10:10:50 Trace [HybrisUtils] Loaded OS library libz.so.1
10:10:50 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 6

**Comment by dolinavidit** [comment] 2020-05-01 08:24
14:22:36 Info  [Launcher] Version: client c735370 / manifest b3dd620
14:22:36 Info  [Launcher] CPU: AuthenticAMD AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G   
14:22:36 Info  [Launcher] CPU supports SSSE3: YES
14:22:36 Trace [Launcher] Loading hybris libraries
14:22:36 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
14:22:36 Trace [HybrisUtils] Loaded OS library libm.so.6
14:22:36 Trace [HybrisUtils] Loaded OS library libz.so.1
14:22:36 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-01 21:26
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:26 UTC
Labels: bug, crash, duplicate, legacy (unsupported)
