### ISSUE TITLE
Exit code 12

### ISSUE THREAD

**Issue by YannYB** [minecraft-linux/mcpelauncher-manifest#664] opened 2022-02-20 20:32 UTC
21:30:34 Info  [Launcher] Version: client 1e44372 / manifest 1da5aa2
21:30:34 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
21:30:34 Info  [Launcher] CPU supports SSSE3: YES
21:30:34 Trace [Launcher] Loading hybris libraries
21:30:34 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/yann/Library/Application Support/mcpelauncher/
21:30:34 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/3675/cmdline to /Users/yann/Library/Application Support/mcpelauncher/
21:30:34 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/yann/Library/Application Support/mcpelauncher/
21:30:34 Trace [REDIRECT] /data/data to /Users/yann/Library/Application Support/mcpelauncher/
21:30:34 Trace [LinkerUtils] Loaded OS library libm.dylib
21:30:34 Trace [LinkerUtils] Loaded OS library libz.dylib
21:30:34 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
21:30:34 Trace [Launcher] Loading Minecraft library
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x10b8dee00
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x10b8dede0
21:30:34 Info  [Launcher] Loaded Minecraft library
21:30:34 Debug [Launcher] Minecraft is at offset 0x0x111200000
21:30:34 Info  [Launcher] Game version: 0.0.0.0
21:30:34 Info  [Launcher] Applying patches
21:30:34 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
21:30:36 Error [GLCOREPATCH] Failed to apply glcorepatch: Failed to find gl::supportsImmediateMode
21:30:36 Info  [Launcher] Initializing JNI
21:30:36 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
21:30:36 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
21:30:36 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
21:30:36 Info  [Launcher] Executing main thread
21:30:36 Trace [Minecraft] Entering JNI_OnLoad 0x70000a9d6000
21:30:36 Trace [Minecraft] JNI_OnLoad completed
21:30:36 Trace [JniSupport] Invoking nativeRegisterThis
21:30:36 Trace [JniSupport] Invoking ANativeActivity_onCreate
21:30:36 Warn  [Main] Android stub called
21:30:36 Warn  [Main] Android stub called
21:30:36 Warn  [Main] Android stub called
21:30:36 Warn  [Main] Android stub called
21:30:36 Info  [Launcher] Loading gamepad mappings
21:30:36 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
21:30:36 Info  [Launcher] Creating window
21:30:36 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
21:30:36 Trace [JniSupport] Invoking start activity callbacks
21:30:36 Error [MCPE] *** setCachedDeviceId(1b7d7f18-08a2-42a8-82cb-917a1cc43dfb)
21:30:36 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: 592a8d1d-7b0b-4afb-a62b-9408a87348f1

Process exited with unexpected exit code: 12
<img width="496" alt="Capture d’écran 2022-02-20 à 21 31 40" src="https://user-images.githubusercontent.com/100095100/154863126-c2785ab3-c7d3-43b1-a1eb-07a5a565654a.png">

**Comment by ChristopherHX** [comment] 2022-03-27 14:54
Are you also on macOS Montery?

Duplicate of #676

The newer issue does follow the issue template, you don't.

**Comment by YannYB** [comment] 2022-03-27 19:16
> Are you also on macOS Montery?
> 
> Duplicate of #676
> 
> The newer issue does follow the issue template, you don't.

Yeah I'm also on macOS Monterey, sorry for the issue template

**Comment by ChristopherHX** [comment] 2022-03-28 18:10
Fixed in new hotfix release v0.3.4. Confimed by two people.

**Closed as completed by ChristopherHX** 2022-03-28 18:10 UTC
Labels: bug

**Comment by YannYB** [comment] 2022-10-11 07:43
Yes

Le 27 mars 2022 à 16:55, ChristopherHX ***@***.******@***.***>> a écrit :



You are on also macOS Montery?

Duplicate of #676<https://github.com/minecraft-linux/mcpelauncher-manifest/issues/676>

The newer issue does follow the issue template, you don't.
