### ISSUE TITLE
Instant crash upon pressing "play" 1.13.0.34

### ISSUE THREAD

**Issue by Drodash** [minecraft-linux/mcpelauncher-manifest#183] opened 2019-11-11 10:28 UTC

**Comment by Drodash** [comment] 2019-11-11 10:29
11:25:13 Info  [Launcher] Version: client c735370 / manifest eb0bc83
11:25:13 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
11:25:13 Info  [Launcher] CPU supports SSSE3: YES
11:25:13 Trace [Launcher] Loading hybris libraries
11:25:13 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
11:25:13 Trace [HybrisUtils] Loaded OS library libm.dylib
11:25:13 Error [HybrisUtils] Failed to load OS library libz.so.1
11:25:13 Trace [Launcher] Loading Minecraft library
11:25:14 Info  [Launcher] Loaded Minecraft library
11:25:14 Debug [Launcher] Minecraft is at offset 0x2b8a000
11:25:14 Trace [Launcher] Initializing vtables
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
11:25:14 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
11:25:14 Trace [AppPlatform] Vtable size = 288
11:25:14 Trace [Store] Vtable size = 40
11:25:14 Info  [Launcher] Game version: 1.13.0
11:25:14 Info  [Launcher] Applying patches
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 131
11:25:14 Trace [Patch] Patching - result: 233 251 249 186 252
11:25:14 Trace [Patch] Patching - original: 83 87 86 131 236
11:25:14 Trace [Patch] Patching - result: 233 11 151 192 252
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 43 11 19 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 59 41 81 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 203 66 81 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 107 47 81 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 139 150 80 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 155 138 80 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 59 199 82 249
11:25:14 Trace [Patch] Patching - original: 83 87 86 131 236
11:25:14 Trace [Patch] Patching - result: 233 219 40 81 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 129
11:25:14 Trace [Patch] Patching - result: 233 155 83 81 249
11:25:14 Trace [Patch] Patching - original: 83 131 236 8 232
11:25:14 Trace [Patch] Patching - result: 233 171 114 114 249
11:25:14 Trace [Patch] Patching - original: 137 76 36 4 137
11:25:14 Trace [Patch] Patching - result: 232 113 195 39 249
11:25:14 Trace [Patch] Patching - original: 36 88 139 65 12
11:25:14 Trace [Patch] Patching - result: 232 124 195 39 249
11:25:14 Trace [Patch] Patching - original: 85 83 87 86 131
11:25:14 Trace [Patch] Patching - result: 233 91 182 13 249
11:25:14 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
Signal 11 received
Backtrace elements: 6
#0 0   mcpelauncher-client                 0x0014188e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa759a02b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x001075b6 _ZN11GLCorePatch7installEPv + 662
#4 4   mcpelauncher-client                 0x00087a95 main + 10981
#5 5   libdyld.dylib                       0xa7291611 start + 1
Dumping stack...
#74 HYBRIS (null)+134793001 in libminecraftpe.so+0x5502729 [0x808c729]
#124 HYBRIS (null)+55546448 in libminecraftpe.so+0x96f250 [0x34f9250]
#125 HYBRIS (null)+55546512 in libminecraftpe.so+0x96f290 [0x34f9290]
#126 HYBRIS (null)+55546528 in libminecraftpe.so+0x96f2a0 [0x34f92a0]
#127 HYBRIS (null)+55546544 in libminecraftpe.so+0x96f2b0 [0x34f92b0]
#273 HYBRIS mce::ShaderGroupBase::loadShader(std::string const&, Core::Path const&, Core::Path const&, Core::Path const&)+0 in libminecraftpe.so+0x3afbde0 [0x6685de0]
#382 HYBRIS (null)+45654016 in libminecraftpe.so+0x0000 [0x2b8a000]
#383 HYBRIS (null)+45654016 in libminecraftpe.so+0x0000 [0x2b8a000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2019-11-11 11:27
@Drodash  Your Issue is a duplicate off #171
You will find there a temporary Solution until it is merged (MacOs user)

**Comment by Drodash** [comment] 2019-11-12 17:05
@ChristopherHX Thanks!! However now I have a different problem since the newest build requires OS 1.14 and I can't seem to upgrade from 1.13.
(Macbook Pro late 2011)
Thanks!

**Comment by Drodash** [comment] 2019-11-12 17:09
@ChristopherHX Never mind I solved it thanks!!

**Closed** 2019-11-16 00:19 UTC
Labels: crash, duplicate
