### ISSUE TITLE
Minecraft stops unexpectedly

### ISSUE THREAD

**Issue by ImHammer** [minecraft-linux/mcpelauncher-manifest#721] opened 2022-10-17 11:49 UTC
**Describe the bug**
Minecraft stops unexpectedly

**To Reproduce**
Just play for a while (or sometimes you don't even have to wait long)

**Expected behavior**
Play normally

**Screenshots**
![Captura de tela_2022-10-17_08-32-49](https://user-images.githubusercontent.com/59282552/196167688-f5bf139c-c825-4dd7-9180-06640818fe6c.png)
![Captura de tela_2022-10-17_08-33-13](https://user-images.githubusercontent.com/59282552/196167718-e19263b7-b9b3-482c-9c48-bd3e0fd282dc.png)
![Captura de tela_2022-10-17_08-33-30](https://user-images.githubusercontent.com/59282552/196167731-c4ac0d40-56b7-4c7f-aa8c-c77f6993d063.png)
![Captura de tela_2022-10-17_08-33-48](https://user-images.githubusercontent.com/59282552/196167749-9369e5f3-27d5-4924-a01c-8529c2e39bdb.png)
![Captura de tela_2022-10-17_08-33-58](https://user-images.githubusercontent.com/59282552/196167765-63a1e055-bae0-458d-8968-bba57c27bfad.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 (Vanessa) 64 Bit Processor
 - Version: v0.5.0-AppImage-x86_64-0.5.0-693 (build 693)
 - Installation: AppImage

**Additional context**
This happens quite often.
Before anyone asks, I've already installed all the necessary dependencies.

**Comment by ChristopherHX** [comment] 2022-10-19 18:21
Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/718

**Closed as not planned by ChristopherHX** 2022-10-19 18:21 UTC
Labels: bug
