### ISSUE TITLE
no files

### ISSUE THREAD

**Issue by nu4h** [minecraft-linux/mcpelauncher-manifest#242] opened 2020-03-11 12:44 UTC
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127
 i look the wiki but i didn't see help
(sorry for my bad english im french)

**Comment by Th3Ang3lo** [comment] 2020-03-14 04:27
Same issue also

**Comment by RealAkito** [comment] 2020-03-18 14:11
Wiki have said you need "32 bit" graphic driver installed.

This vary depends on your linux distribution.

I am using arch so and is using AMD so

1. Enable multilib support
2. install lib32-mesa

**Comment by ChristopherHX** [comment] 2020-06-03 21:22
duplicate of #94

**Closed by ChristopherHX** 2020-06-03 21:22 UTC
