### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HowToPeaZYT** [minecraft-linux/mcpelauncher-manifest#273] opened 2020-04-17 13:44 UTC
14:37:57 Info  [Launcher] Version: client 7c17ac3 / manifest 45f9d98
14:37:57 Info  [Launcher] CPU: GenuineIntel         Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
14:37:57 Info  [Launcher] CPU supports SSSE3: YES
14:37:57 Trace [Launcher] Loading hybris libraries
14:37:57 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
14:37:57 Trace [HybrisUtils] Loaded OS library libm.so.6
14:37:57 Trace [HybrisUtils] Loaded OS library libz.so.1
14:37:57 Info  [Launcher] Creating window
14:37:57 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
14:37:57 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
14:37:57 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
14:37:57 Trace [Launcher] Loading Minecraft library
14:37:58 Info  [Launcher] Loaded Minecraft library
14:37:58 Debug [Launcher] Minecraft is at offset 0xec634000
14:37:58 Trace [AppPlatform] Vtable size = 295
14:37:58 Trace [Patch] Patching - original: 85 83 87 86 129
14:37:58 Trace [Patch] Patching - result: 233 251 191 174 101
14:37:58 Trace [Patch] Patching - original: 85 83 87 86 131
14:37:58 Trace [Patch] Patching - result: 233 59 220 164 101
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
14:37:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/florian/.local/share/mcpelauncher/'
14:37:58 Error [JNIVM] Object not found in current local layer
14:37:58 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
14:37:58 Error [JNIVM] Object not found in current local layer
14:37:58 Debug [XSAPI.Android] Successfully registerered HttpCall methods
14:37:58 Error [JNIVM] Object not found in current local layer
14:37:58 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
14:37:58 Error [JNIVM] Object not found in current local layer
14:37:58 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
14:37:58 Error [JNIVM] Object not found in current local layer
14:37:58 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
14:37:58 Trace [XBOXLive] Reading xbox config file
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] EGL stub eglMakeCurrent called
14:37:58 Warn  [Launcher] EGL stub eglMakeCurrent called
14:37:58 Warn  [Launcher] Android stub called
14:37:58 Warn  [Launcher] EGL stub eglMakeCurrent called
14:37:58 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
14:37:58 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
14:37:59 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 32880
14:37:59 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 34735
14:38:05 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 48490
14:38:05 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 38251
14:38:13 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
14:38:13 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
14:38:13 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting - user_interaction_required
14:38:13 Debug [XSAPI.Android] sign_in_impl: will be showing UI
14:38:13 Debug [XSAPI.Android] sign_in_impl: native activity, continuing on
14:38:13 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin - :Entering
14:38:13 Trace [DaemonLauncher] Starting daemon: /usr/bin/msa-daemon
14:38:13 Trace [DaemonLauncher] Starting daemon: /usr/bin/./msa-ui-qt
14:38:20 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin - :Exiting
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Signal 6 received
Backtrace elements: 11
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x566bb9cc]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f28170]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f28159]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf78549b6]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf783d3f5]
#5 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libgnustl_shared.so+0x523e5 [0xf3b803e5]
#6 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libgnustl_shared.so+0x4fd29 [0xf3b7dd29]
#7 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libgnustl_shared.so+0x4fdc0 [0xf3b7ddc0]
#8 HYBRIS (null)+-206053244 in libgnustl_shared.so+0x50084 [0xf3b7e084]
#9 HYBRIS (null)+-206051533 in libgnustl_shared.so+0x50733 [0xf3b7e733]
#10 HYBRIS mce::Blob::~Blob()+8 in libminecraftpe.so+0x3dc7868 [0xf03fb868]
Dumping stack...
#5 HYBRIS (null)+-329039872 in libminecraftpe.so+0x0000 [0xec634000]
#13 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libgnustl_shared.so+0x523e5 [0xf3b803e5]
#14 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libgnustl_shared.so+0x4fd29 [0xf3b7dd29]
#15 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libgnustl_shared.so+0x4fdc0 [0xf3b7ddc0]
#16 HYBRIS (null)+-206053244 in libgnustl_shared.so+0x50084 [0xf3b7e084]
#17 HYBRIS (null)+-206051533 in libgnustl_shared.so+0x50733 [0xf3b7e733]
#18 HYBRIS mce::Blob::~Blob()+8 in libminecraftpe.so+0x3dc7868 [0xf03fb868]
#226 HYBRIS (null)+-238693373 in libminecraftpe.so+0x5629403 [0xf1c5d403]
#230 HYBRIS (null)+-238693373 in libminecraftpe.so+0x5629403 [0xf1c5d403]
#234 HYBRIS (null)+-238693373 in libminecraftpe.so+0x5629403 [0xf1c5d403]
#264 HYBRIS std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned int) const+297 in libgnustl_shared.so+0xbaea9 [0xf3be8ea9]
#291 HYBRIS std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned int) const+297 in libgnustl_shared.so+0xbaea9 [0xf3be8ea9]
#512 HYBRIS __gnu_cxx::__verbose_terminate_handler()+326 in libgnustl_shared.so+0x52356 [0xf3b80356]
#590 HYBRIS (null)+-205496816 in libgnustl_shared.so+0xd7e10 [0xf3c05e10]
#648 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#650 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#654 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#655 HYBRIS typeinfo name for std::bad_alloc+0 in libgnustl_shared.so+0xd8bc2 [0xf3c06bc2]
#656 HYBRIS (null)+54 in libgnustl_shared.so+0x4ecc6 [0xf3b7ccc6]
#660 HYBRIS (null)+76 in libgnustl_shared.so+0x500dc [0xf3b7e0dc]
#661 HYBRIS (null)+7 in libgnustl_shared.so+0x4ece7 [0xf3b7cce7]
#662 HYBRIS (null)+6 in libgnustl_shared.so+0x4ec96 [0xf3b7cc96]
#663 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#665 HYBRIS (null)+7 in libgnustl_shared.so+0x4ece7 [0xf3b7cce7]
#666 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#668 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#669 HYBRIS typeinfo name for std::bad_alloc+0 in libgnustl_shared.so+0xd8bc2 [0xf3c06bc2]
#670 HYBRIS (null)+-205496816 in libgnustl_shared.so+0xd7e10 [0xf3c05e10]
#672 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libgnustl_shared.so+0x523e5 [0xf3b803e5]
#687 HYBRIS __gnu_cxx::__verbose_terminate_handler()+11 in libgnustl_shared.so+0x5221b [0xf3b8021b]
#688 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#692 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libgnustl_shared.so+0x4fd29 [0xf3b7dd29]
#694 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#695 HYBRIS (null)+-205288376 in libgnustl_shared.so+0x10ac48 [0xf3c38c48]
#696 HYBRIS (null)+62 in libgnustl_shared.so+0x4ed1e [0xf3b7cd1e]
#699 HYBRIS __cxxabiv1::__terminate(void (*)())+11 in libgnustl_shared.so+0x4fd1b [0xf3b7dd1b]
#700 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#704 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libgnustl_shared.so+0x4fdc0 [0xf3b7ddc0]
#705 HYBRIS __gnu_cxx::__verbose_terminate_handler()+0 in libgnustl_shared.so+0x52210 [0xf3b80210]
#706 HYBRIS (null)+-206053456 in libgnustl_shared.so+0x4ffb0 [0xf3b7dfb0]
#707 HYBRIS (null)+9 in libgnustl_shared.so+0x4e929 [0xf3b7c929]
#708 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#709 HYBRIS std::terminate()+9 in libgnustl_shared.so+0x4fda9 [0xf3b7dda9]
#710 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#712 HYBRIS (null)+-206053244 in libgnustl_shared.so+0x50084 [0xf3b7e084]
#715 HYBRIS (null)+9 in libgnustl_shared.so+0x4e439 [0xf3b7c439]
#716 HYBRIS (null)+10 in libgnustl_shared.so+0x5001a [0xf3b7e01a]
#717 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#720 HYBRIS (null)+-206051533 in libgnustl_shared.so+0x50733 [0xf3b7e733]
#722 HYBRIS typeinfo for std::bad_alloc+0 in libgnustl_shared.so+0x102ec0 [0xf3c30ec0]
#723 HYBRIS std::bad_alloc::~bad_alloc()+0 in libgnustl_shared.so+0x4db40 [0xf3b7bb40]
#724 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#725 HYBRIS operator new(unsigned int)+12 in libgnustl_shared.so+0x506ac [0xf3b7e6ac]
#726 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#728 HYBRIS operator new[](unsigned int)+28 in libgnustl_shared.so+0x507dc [0xf3b7e7dc]
#732 HYBRIS ReadOnlyBinaryStream::read(void*, unsigned int)+129 in libminecraftpe.so+0x3e5df61 [0xf0491f61]
#734 HYBRIS operator new[](unsigned int)+6 in libgnustl_shared.so+0x507c6 [0xf3b7e7c6]
#735 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#736 HYBRIS mce::Blob::Blob(unsigned int)+40 in libminecraftpe.so+0x3dc7798 [0xf03fb798]
#739 HYBRIS (null)+-205568446 in libgnustl_shared.so+0xc6642 [0xf3bf4642]
#740 HYBRIS mce::Blob::Blob(unsigned int)+12 in libminecraftpe.so+0x3dc777c [0xf03fb77c]
#742 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#746 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#748 HYBRIS mce::Image::resizeImageBytesToFitImageDescription()+72 in libminecraftpe.so+0x3e14418 [0xf0448418]
#752 HYBRIS mce::Blob::~Blob()+8 in libminecraftpe.so+0x3dc7868 [0xf03fb868]
#755 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#756 HYBRIS (null)+-284217638 in libminecraftpe.so+0x2abeeda [0xef0f2eda]
#764 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#772 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#800 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#803 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#804 HYBRIS operator new(unsigned int)+39 in libgnustl_shared.so+0x506c7 [0xf3b7e6c7]
#808 HYBRIS std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned int) const+293 in libgnustl_shared.so+0xbaea5 [0xf3be8ea5]
#809 HYBRIS operator new(unsigned int)+12 in libgnustl_shared.so+0x506ac [0xf3b7e6ac]
#810 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#812 HYBRIS std::string::reserve(unsigned int)+127 in libgnustl_shared.so+0xc630f [0xf3bf430f]
#816 HYBRIS operator new(unsigned int)+39 in libgnustl_shared.so+0x506c7 [0xf3b7e6c7]
#818 HYBRIS operator delete(void*)+6 in libgnustl_shared.so+0x4e086 [0xf3b7c086]
#827 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#828 HYBRIS std::string::copy(char*, unsigned int, unsigned int) const+8 in libgnustl_shared.so+0xc6ee8 [0xf3bf4ee8]
#829 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#832 HYBRIS std::string::copy(char*, unsigned int, unsigned int) const+8 in libgnustl_shared.so+0xc6ee8 [0xf3bf4ee8]
#833 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#836 HYBRIS ReadOnlyBinaryStream::read(void*, unsigned int)+129 in libminecraftpe.so+0x3e5df61 [0xf0491f61]
#842 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#846 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#848 HYBRIS ReadOnlyBinaryStream::getSignedInt()+36 in libminecraftpe.so+0x3e5e214 [0xf0492214]
#854 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#856 HYBRIS (null)+-290581525 in libminecraftpe.so+0x24ad3eb [0xeeae13eb]
#860 HYBRIS (null)+-290582979 in libminecraftpe.so+0x24ace3d [0xeeae0e3d]
#864 HYBRIS ReadOnlyBinaryStream::getUnsignedVarInt()+12 in libminecraftpe.so+0x3e5e90c [0xf049290c]
#865 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#867 HYBRIS (null)+-206922044 in libminecraftpe.so+0x7475ec4 [0xf3aa9ec4]
#870 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#872 HYBRIS (null)+-290579157 in libminecraftpe.so+0x24add2b [0xeeae1d2b]
#876 HYBRIS leveldb::ZlibCompressorBase::decompress(char const*, unsigned int, std::string&) const+37 in libminecraftpe.so+0x3c77b35 [0xf02abb35]
#885 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#887 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#888 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#889 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#890 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#900 HYBRIS ReadOnlyBinaryStream::read(void*, unsigned int)+32 in libminecraftpe.so+0x3e5df00 [0xf0491f00]
#907 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#912 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#913 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#918 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#925 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#934 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#936 HYBRIS (null)+-290923717 in libminecraftpe.so+0x2459b3b [0xeea8db3b]
#939 HYBRIS std::chrono::_V2::steady_clock::now()+9 in libgnustl_shared.so+0xb74d9 [0xf3be54d9]
#940 HYBRIS (null)+-290923751 in libminecraftpe.so+0x2459b19 [0xeea8db19]
#943 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
#944 HYBRIS (null)+-290989446 in libminecraftpe.so+0x2449a7a [0xeea7da7a]
#957 HYBRIS vtable for ReadOnlyBinaryStream+8 in libminecraftpe.so+0x73a4f08 [0xf39d8f08]
#959 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0xf3c3ab84]
#963 HYBRIS (null)+-206925992 in libminecraftpe.so+0x7474f58 [0xf3aa8f58]
#964 HYBRIS vtable for ReadOnlyBinaryStream+8 in libminecraftpe.so+0x73a4f08 [0xf39d8f08]
#966 HYBRIS std::string::_Rep::_S_empty_rep_storage+0 in libgnustl_shared.so+0x10cb78 [0xf3c3ab78]
#989 HYBRIS (null)+-205308396 in libgnustl_shared.so+0x105e14 [0xf3c33e14]
#992 HYBRIS std::chrono::_V2::system_clock::now()+43 in libgnustl_shared.so+0xb749b [0xf3be549b]
#997 HYBRIS (null)+-207251576 in libminecraftpe.so+0x7425788 [0xf3a59788]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-08 19:20
You ran out of memory?
Are you using any non vanilla resource pack?
Do you have no swap space?
duplicate of #121

**Closed** 2020-06-08 19:20 UTC
Labels: legacy/ChristopherHX
