### ISSUE TITLE
Minecraft Bedrock Launcher Crash v 1.14.1.5

### ISSUE THREAD

**Issue by jahmatee** [minecraft-linux/mcpelauncher-manifest#213] opened 2019-12-28 19:46 UTC
Hi guys,

completely new here. :)

Try to use Minecraft Bedrock Launcher on a Macbook with latest Google Play version ( 1.14.1.5 ) but always crashes.

Any solution?

Thx,

Togo

19:38:48 Info  [Launcher] Version: client c735370 / manifest eb0bc83
19:38:48 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
19:38:48 Info  [Launcher] CPU supports SSSE3: YES
19:38:48 Trace [Launcher] Loading hybris libraries
19:38:48 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
19:38:48 Trace [HybrisUtils] Loaded OS library libm.dylib
19:38:48 Error [HybrisUtils] Failed to load OS library libz.so.1
19:38:48 Trace [Launcher] Loading Minecraft library
19:38:51 Info  [Launcher] Loaded Minecraft library
19:38:51 Debug [Launcher] Minecraft is at offset 0x3917000
19:38:51 Trace [Launcher] Initializing vtables
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
19:38:51 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
19:38:51 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 13
#0 0   mcpelauncher-client                 0x0019888e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa17c3e5b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa1649a34 abort + 141
#4 4   libc++abi.dylib                     0xa01d1df7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa01f2371 _ZL25default_terminate_handlerv + 244
#6 6   libc++abi.dylib                     0xa01ef551 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa01eef7b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
#8 8   mcpelauncher-client                 0x0021418c _Z21minecraft_get_versionPiS_S_S_ + 396
#9 9   mcpelauncher-client                 0x0019a7f9 _ZN16MinecraftVersion4initEv + 57
#10 10  mcpelauncher-client                 0x00199f85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#11 11  mcpelauncher-client                 0x000de790 main + 10208
#12 12  libdyld.dylib                       0xa15ba395 start + 1
Dumping stack...
#485 HYBRIS (null)+62105568 in libminecraftpe.so+0x2237e0 [0x3b3a7e0]
#518 HYBRIS (null)+59863316 in libminecraftpe.so+0x0114 [0x3917114]
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7421d30 [0xad38d30]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7421d30 [0xad38d30]
#627 HYBRIS (null)+59863040 in libminecraftpe.so+0x0000 [0x3917000]
#674 HYBRIS (null)+59863040 in libminecraftpe.so+0x0000 [0x3917000]
#675 HYBRIS (null)+59863040 in libminecraftpe.so+0x0000 [0x3917000]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment] 2019-12-28 21:22
Are you on Catalina? The launcher will not work because the game itself is
32bit. Switch to Linux or downgrade to Mojave.

**Comment by jahmatee** [comment] 2019-12-29 15:07
@Mhowser . Thx. I am on High Sierra version 10.13. 6 . Does not work still. Can you use Minecraft v 1.14?

**Comment by mariobrostech** [comment] 2019-12-29 19:27
@jahmatee See the pinned issue [here](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165). Minecraft 1.13+ isn't functional at this time.

You can try using ChristopherHX's fork of this project, which supports 1.13+, although it may be a bit buggy. If you want the best experience, I would follow the instructions [here](https://github.com/ChristopherHX/mcpelauncher-manifest/tree/master#experimental-builds-release-page-maybe-outdated) to ensure you get the latest build.

Hope this helps!

**Comment by jahmatee** [comment] 2019-12-29 20:13
@mariobrostech Thank you. Oops, not used to forks, hope can make it work.

**Comment by mariobrostech** [comment] 2019-12-30 14:49
Great, let me know if you have any further questions (even on the fork).
Good luck!

**Comment by ChristopherHX** [comment] 2020-06-01 21:56
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:56 UTC
