### ISSUE TITLE
Unable to get MCPELauncher for Project Crostini (Chrome OS Linux Beta)

### ISSUE THREAD

**Issue by RedcatPhoenix2** [minecraft-linux/mcpelauncher-manifest#291] opened 2020-04-28 00:58 UTC
I type
`awesomepcat@penguin:~$ chmod +x /mnt/chromeos/MyFiles/Downloads/Minecraft_Bedrock_Launcher.AppImage`

Then...
`chmod: changing permissions of '/mnt/chromeos/MyFiles/Downloads/Minecraft_Bedrock_Launcher.AppImage': Operation not permitted`

Which is odd, What do I have to do to Install .AppImages on chrome os?

**Comment by SupDroidStudio** [comment] 2020-04-28 17:44
From the Crostini terminal, run `wget https://mcpelauncher.mrarm.io/appimage/Minecraft_Bedrock_Launcher.AppImage`. That will download the binary into your home folder. Then you can `chmod +x Minecraft_Bedrock_Launcher.AppImage` without getting permission denied errors, and then run with `./Minecraft_Bedrock_Launcher.AppImage`

**Comment by ChristopherHX** [comment] 2020-06-03 21:03
duplicate of #150

**Closed by ChristopherHX** 2020-06-03 21:03 UTC
