### ISSUE TITLE
Error [HybrisUtils] Failed to load OS library libz.so.1

### ISSUE THREAD

**Issue by TheMinecraftGuyGuru** [minecraft-linux/mcpelauncher-manifest#303] opened 2020-05-19 18:22 UTC
When attempting to launch Minecraft, it closes the launcher, the game log opens, it makes it way all the way down to `11:15:48 Trace [Launcher] Loading Minecraft library` and then gets stuck. I left it there for 2 hours just to make sure it wasn't a first time launch sort of thing, since it is unofficial and all. I tried deleting the installed version and redownloading, and I tried deleting the application and reinstalling, and I tried running the troubleshooter. Here is the full log.

`11:21:00 Info  [Launcher] Version: client c735370 / manifest eb0bc83
11:21:00 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
11:21:00 Info  [Launcher] CPU supports SSSE3: YES
11:21:00 Trace [Launcher] Loading hybris libraries
11:21:00 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
11:21:00 Trace [HybrisUtils] Loaded OS library libm.dylib
11:21:00 Error [HybrisUtils] Failed to load OS library libz.so.1
11:21:00 Trace [Launcher] Loading Minecraft library
linker`

**Comment by ChristopherHX** [comment] 2020-06-01 21:19
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:19 UTC
Labels: bug, crash, duplicate, legacy (unsupported)
