### ISSUE TITLE
Minecraft Bedrock On Debian 10 Buster Crashing

### ISSUE THREAD

**Issue by xXTeraXx** [minecraft-linux/mcpelauncher-manifest#247] opened 2020-03-21 22:31 UTC
Hello i'm trying to run minecraft bedrock with debian 10 buster.  Older versions of the game work such as 1.14.1.5.  But the latest version 1.14.30.2 just refuses to work and exits with this code

18:30:46 Info  [Launcher] Version: client c735370 / manifest b3dd620
18:30:46 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
18:30:46 Info  [Launcher] CPU supports SSSE3: YES
18:30:46 Trace [Launcher] Loading hybris libraries
18:30:46 Trace [HybrisUtils] Loaded OS library /home/rahul/Downloads/linux-packaging-scripts-master/source/mcpelauncher/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
18:30:46 Trace [HybrisUtils] Loaded OS library libm.so.6
18:30:46 Trace [HybrisUtils] Loaded OS library libz.so.1
18:30:46 Trace [Launcher] Loading Minecraft library
18:30:46 Info  [Launcher] Loaded Minecraft library
18:30:46 Debug [Launcher] Minecraft is at offset 0xe5cdf000
18:30:46 Trace [Launcher] Initializing vtables
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
18:30:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
18:30:46 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xab) [0x5688b3b1]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fd0ad0]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fd0ab9]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf783e8b2]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x12c) [0xf7827309]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x79994) [0xf7bae994]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x87364) [0xf7bbc364]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x873dd) [0xf7bbc3dd]
#8 /lib/i386-linux-gnu/libstdc++.so.6(+0x876dc) [0xf7bbc6dc]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x568da4a2]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x5688c9e0]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x42) [0x5688c8d8]
#12 /usr/bin/mcpelauncher-client(main+0x1117) [0x5682c7c7]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7828ef1]
#14 /usr/bin/mcpelauncher-client(_start+0x31) [0x5682b221]
Dumping stack...
#22 HYBRIS (null)+-430572049 in libminecraftpe.so+0x880def [0xe655fdef]
#23 HYBRIS (null)+-378402224 in libminecraftpe.so+0x3a41a50 [0xe9720a50]
#24 HYBRIS (null)+-378405920 in libminecraftpe.so+0x3a40be0 [0xe971fbe0]
#28 HYBRIS (null)+-378398432 in libminecraftpe.so+0x3a42920 [0xe9721920]
#29 HYBRIS (null)+-378402128 in libminecraftpe.so+0x3a41ab0 [0xe9720ab0]
#32 HYBRIS (null)+-317323004 in libminecraftpe.so+0x7481904 [0xed160904]
#33 HYBRIS (null)+-378398288 in libminecraftpe.so+0x3a429b0 [0xe97219b0]
#34 HYBRIS (null)+-378398336 in libminecraftpe.so+0x3a42980 [0xe9721980]
#38 HYBRIS (null)+-378385152 in libminecraftpe.so+0x3a45d00 [0xe9724d00]
#39 HYBRIS (null)+-378386912 in libminecraftpe.so+0x3a45620 [0xe9724620]
#42 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe66edd5c]
#43 HYBRIS (null)+-378377568 in libminecraftpe.so+0x3a47aa0 [0xe9726aa0]
#44 HYBRIS (null)+-378385056 in libminecraftpe.so+0x3a45d60 [0xe9724d60]
#48 HYBRIS (null)+-378370448 in libminecraftpe.so+0x3a49670 [0xe9728670]
#49 HYBRIS (null)+-378377472 in libminecraftpe.so+0x3a47b00 [0xe9726b00]
#53 HYBRIS (null)+-378362864 in libminecraftpe.so+0x3a4b410 [0xe972a410]
#54 HYBRIS (null)+-378370352 in libminecraftpe.so+0x3a496d0 [0xe97286d0]
#58 HYBRIS (null)+-378352048 in libminecraftpe.so+0x3a4de50 [0xe972ce50]
#59 HYBRIS (null)+-378362768 in libminecraftpe.so+0x3a4b470 [0xe972a470]
#63 HYBRIS (null)+-378348256 in libminecraftpe.so+0x3a4ed20 [0xe972dd20]
#64 HYBRIS (null)+-378351952 in libminecraftpe.so+0x3a4deb0 [0xe972ceb0]
#68 HYBRIS (null)+-378344464 in libminecraftpe.so+0x3a4fbf0 [0xe972ebf0]
#69 HYBRIS (null)+-378348160 in libminecraftpe.so+0x3a4ed80 [0xe972dd80]
#72 HYBRIS (null)+-317323004 in libminecraftpe.so+0x7481904 [0xed160904]
#73 HYBRIS (null)+-378342528 in libminecraftpe.so+0x3a50380 [0xe972f380]
#74 HYBRIS (null)+-378344368 in libminecraftpe.so+0x3a4fc50 [0xe972ec50]
#78 HYBRIS (null)+-378338736 in libminecraftpe.so+0x3a51250 [0xe9730250]
#79 HYBRIS (null)+-378342432 in libminecraftpe.so+0x3a503e0 [0xe972f3e0]
#82 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe66edd5c]
#83 HYBRIS (null)+-378338592 in libminecraftpe.so+0x3a512e0 [0xe97302e0]
#84 HYBRIS (null)+-378338640 in libminecraftpe.so+0x3a512b0 [0xe97302b0]
#88 HYBRIS (null)+-378323520 in libminecraftpe.so+0x3a54dc0 [0xe9733dc0]
#89 HYBRIS (null)+-378327216 in libminecraftpe.so+0x3a53f50 [0xe9732f50]
#93 HYBRIS (null)+-378312704 in libminecraftpe.so+0x3a57800 [0xe9736800]
#94 HYBRIS (null)+-378323424 in libminecraftpe.so+0x3a54e20 [0xe9733e20]
#98 HYBRIS (null)+-378312560 in libminecraftpe.so+0x3a57890 [0xe9736890]
#99 HYBRIS (null)+-378312608 in libminecraftpe.so+0x3a57860 [0xe9736860]
#103 HYBRIS (null)+-378301136 in libminecraftpe.so+0x3a5a530 [0xe9739530]
#104 HYBRIS (null)+-378301184 in libminecraftpe.so+0x3a5a500 [0xe9739500]
#108 HYBRIS (null)+-378279040 in libminecraftpe.so+0x3a5fb80 [0xe973eb80]
#109 HYBRIS (null)+-378289760 in libminecraftpe.so+0x3a5d1a0 [0xe973c1a0]
#112 HYBRIS (null)+-317323004 in libminecraftpe.so+0x7481904 [0xed160904]
#113 HYBRIS (null)+-378278032 in libminecraftpe.so+0x3a5ff70 [0xe973ef70]
#114 HYBRIS (null)+-378278944 in libminecraftpe.so+0x3a5fbe0 [0xe973ebe0]
#118 HYBRIS (null)+-378277888 in libminecraftpe.so+0x3a60000 [0xe973f000]
#119 HYBRIS (null)+-378277936 in libminecraftpe.so+0x3a5ffd0 [0xe973efd0]
#122 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe66edd5c]
#123 HYBRIS (null)+-378259024 in libminecraftpe.so+0x3a649b0 [0xe97439b0]
#124 HYBRIS (null)+-378266512 in libminecraftpe.so+0x3a62c70 [0xe9741c70]
#128 HYBRIS (null)+-378258880 in libminecraftpe.so+0x3a64a40 [0xe9743a40]
#129 HYBRIS (null)+-378258928 in libminecraftpe.so+0x3a64a10 [0xe9743a10]
#133 HYBRIS (null)+-378228480 in libminecraftpe.so+0x3a6c100 [0xe974b100]
#134 HYBRIS (null)+-378228528 in libminecraftpe.so+0x3a6c0d0 [0xe974b0d0]
#138 HYBRIS (null)+-378198080 in libminecraftpe.so+0x3a737c0 [0xe97527c0]
#139 HYBRIS (null)+-378198128 in libminecraftpe.so+0x3a73790 [0xe9752790]
#143 HYBRIS (null)+-378167680 in libminecraftpe.so+0x3a7ae80 [0xe9759e80]
#144 HYBRIS (null)+-378167728 in libminecraftpe.so+0x3a7ae50 [0xe9759e50]
#148 HYBRIS (null)+-378133632 in libminecraftpe.so+0x3a83380 [0xe9762380]
#149 HYBRIS (null)+-378137328 in libminecraftpe.so+0x3a82510 [0xe9761510]
#152 HYBRIS (null)+-317323004 in libminecraftpe.so+0x7481904 [0xed160904]
#153 HYBRIS (null)+-378132624 in libminecraftpe.so+0x3a83770 [0xe9762770]
#154 HYBRIS (null)+-378133536 in libminecraftpe.so+0x3a833e0 [0xe97623e0]
#158 HYBRIS (null)+-378128832 in libminecraftpe.so+0x3a84640 [0xe9763640]
#159 HYBRIS (null)+-378132528 in libminecraftpe.so+0x3a837d0 [0xe97627d0]
#164 HYBRIS (null)+-378142717 in libminecraftpe.so+0x3a81003 [0xe9760003]
#174 HYBRIS (null)+-429043220 in libminecraftpe.so+0x9f61ec [0xe66d51ec]
#177 HYBRIS (null)+-374421088 in libminecraftpe.so+0x3e0d9a0 [0xe9aec9a0]
#721 HYBRIS (null)+-439488512 in libminecraftpe.so+0x0000 [0xe5cdf000]
Process exited with unexpected exit code: 6

**Comment by intchanter** [comment] 2020-03-23 01:34
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165

**Comment by ChristopherHX** [comment] 2020-06-01 22:02
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:02 UTC
