### ISSUE TITLE
Game crashes upon startup (LibEGL)

### ISSUE THREAD

**Issue by zvillager10** [minecraft-linux/mcpelauncher-manifest#191] opened 2019-11-16 12:18 UTC
pls help /usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

**Comment by Mhowser** [comment] 2019-11-16 21:27
Install 32 bit graphics drivers, read the docs for which ones.

**Comment by Craftstar15** [comment] 2019-11-18 19:12
I cant play 1.13!

**Comment by ChristopherHX** [comment] 2020-06-03 21:22
duplicate of #94

**Closed by ChristopherHX** 2020-06-03 21:22 UTC
