### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BRENTGAMEZ** [minecraft-linux/mcpelauncher-manifest#209] opened 2019-12-23 09:41 UTC
03:40:08 Info  [Launcher] Version: client c735370 / manifest eb0bc83
03:40:08 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz
03:40:08 Info  [Launcher] CPU supports SSSE3: YES
03:40:08 Trace [Launcher] Loading hybris libraries
03:40:08 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
03:40:08 Trace [HybrisUtils] Loaded OS library libm.so.6
03:40:08 Trace [HybrisUtils] Loaded OS library libz.so.1
03:40:08 Trace [Launcher] Loading Minecraft library
03:40:09 Info  [Launcher] Loaded Minecraft library
03:40:09 Debug [Launcher] Minecraft is at offset 0xed903000
03:40:09 Trace [Launcher] Initializing vtables
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
03:40:09 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
03:40:09 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567e77db]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fae950]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fae939]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7874832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7875cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7bd297d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7bda0f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7bda15d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7bda45c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x5683bf4b]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567e8fd4]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567e8ecc]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567901de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf785fe81]
#14 /usr/bin/mcpelauncher-client(+0x1c8b31) [0x5678eb31]
Dumping stack...
#1 HYBRIS (null)+-248427856 in libminecraftpe.so+0x3a11ab0 [0xf1314ab0]
#2 HYBRIS (null)+-248435344 in libminecraftpe.so+0x3a0fd70 [0xf1312d70]
#13 HYBRIS (null)+-309317632 in libminecraftpe.so+0x0000 [0xed903000]
#31 HYBRIS (null)+-248377280 in libminecraftpe.so+0x3a1e040 [0xf1321040]
#32 HYBRIS (null)+-248384304 in libminecraftpe.so+0x3a1c4d0 [0xf131f4d0]
#36 HYBRIS (null)+-248377136 in libminecraftpe.so+0x3a1e0d0 [0xf13210d0]
#37 HYBRIS (null)+-248377184 in libminecraftpe.so+0x3a1e0a0 [0xf13210a0]
#40 HYBRIS (null)+-300402721 in libminecraftpe.so+0x8807df [0xee1837df]
#77 HYBRIS (null)+-248319440 in libminecraftpe.so+0x3a2c230 [0xf132f230]
#111 HYBRIS (null)+-248269376 in libminecraftpe.so+0x3a385c0 [0xf133b5c0]
#112 HYBRIS (null)+-248280096 in libminecraftpe.so+0x3a35be0 [0xf1338be0]
#116 HYBRIS (null)+-248269232 in libminecraftpe.so+0x3a38650 [0xf133b650]
#117 HYBRIS (null)+-248269280 in libminecraftpe.so+0x3a38620 [0xf133b620]
#121 HYBRIS (null)+-248257808 in libminecraftpe.so+0x3a3b2f0 [0xf133e2f0]
#122 HYBRIS (null)+-248257856 in libminecraftpe.so+0x3a3b2c0 [0xf133e2c0]
#126 HYBRIS (null)+-248235712 in libminecraftpe.so+0x3a40940 [0xf1343940]
#127 HYBRIS (null)+-248246432 in libminecraftpe.so+0x3a3df60 [0xf1340f60]
#130 HYBRIS (null)+-187299588 in libminecraftpe.so+0x745d8fc [0xf4d608fc]
#131 HYBRIS (null)+-248234704 in libminecraftpe.so+0x3a40d30 [0xf1343d30]
#132 HYBRIS (null)+-248235616 in libminecraftpe.so+0x3a409a0 [0xf13439a0]
#136 HYBRIS (null)+-248234560 in libminecraftpe.so+0x3a40dc0 [0xf1343dc0]
#137 HYBRIS (null)+-248234608 in libminecraftpe.so+0x3a40d90 [0xf1343d90]
#140 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ee6c [0xee311e6c]
#141 HYBRIS (null)+-248215696 in libminecraftpe.so+0x3a45770 [0xf1348770]
#142 HYBRIS (null)+-248223184 in libminecraftpe.so+0x3a43a30 [0xf1346a30]
#146 HYBRIS (null)+-248215552 in libminecraftpe.so+0x3a45800 [0xf1348800]
#147 HYBRIS (null)+-248215600 in libminecraftpe.so+0x3a457d0 [0xf13487d0]
#151 HYBRIS (null)+-248185152 in libminecraftpe.so+0x3a4cec0 [0xf134fec0]
#152 HYBRIS (null)+-248185200 in libminecraftpe.so+0x3a4ce90 [0xf134fe90]
#156 HYBRIS (null)+-248154752 in libminecraftpe.so+0x3a54580 [0xf1357580]
#157 HYBRIS (null)+-248154800 in libminecraftpe.so+0x3a54550 [0xf1357550]
#161 HYBRIS (null)+-248124352 in libminecraftpe.so+0x3a5bc40 [0xf135ec40]
#162 HYBRIS (null)+-248124400 in libminecraftpe.so+0x3a5bc10 [0xf135ec10]
#166 HYBRIS (null)+-248090304 in libminecraftpe.so+0x3a64140 [0xf1367140]
#167 HYBRIS (null)+-248094000 in libminecraftpe.so+0x3a632d0 [0xf13662d0]
#170 HYBRIS (null)+-187299588 in libminecraftpe.so+0x745d8fc [0xf4d608fc]
#171 HYBRIS (null)+-248089296 in libminecraftpe.so+0x3a64530 [0xf1367530]
#172 HYBRIS (null)+-248090208 in libminecraftpe.so+0x3a641a0 [0xf13671a0]
#176 HYBRIS (null)+-248085504 in libminecraftpe.so+0x3a65400 [0xf1368400]
#180 HYBRIS std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_lookahead(std::__detail::_State<std::regex_traits<char> >)+515 in libminecraftpe.so+0xa0ee03 [0xee311e03]
#181 HYBRIS (null)+-248074640 in libminecraftpe.so+0x3a67e70 [0xf136ae70]
#182 HYBRIS (null)+-248085408 in libminecraftpe.so+0x3a65460 [0xf1368460]
#192 HYBRIS (null)+-298872980 in libminecraftpe.so+0x9f5f6c [0xee2f8f6c]
#196 HYBRIS (null)+-186409596 in libminecraftpe.so+0x7536d84 [0xf4e39d84]
#198 HYBRIS (null)+-187299588 in libminecraftpe.so+0x745d8fc [0xf4d608fc]
#202 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x55e7b36 [0xf2eeab36]
#203 HYBRIS (null)+-187299588 in libminecraftpe.so+0x745d8fc [0xf4d608fc]
#206 HYBRIS (null)+-186409608 in libminecraftpe.so+0x7536d78 [0xf4e39d78]
#208 HYBRIS (null)+-186409596 in libminecraftpe.so+0x7536d84 [0xf4e39d84]
#210 HYBRIS (null)+-244384880 in libminecraftpe.so+0x3decb90 [0xf16efb90]
#211 HYBRIS (null)+-186409596 in libminecraftpe.so+0x7536d84 [0xf4e39d84]
#213 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74d6ba8 [0xf4dd9ba8]
#221 HYBRIS (null)+-248046464 in libminecraftpe.so+0x3a6ec80 [0xf1371c80]
#735 HYBRIS (null)+-309317632 in libminecraftpe.so+0x0000 [0xed903000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-02-11 13:25
Look here for workaround
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903

**Comment by ChristopherHX** [comment] 2020-06-01 21:53
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:53 UTC
