### ISSUE TITLE
Non-zero error code

### ISSUE THREAD

**Issue by Block81838** [minecraft-linux/mcpelauncher-manifest#231] opened 2020-02-07 11:52 UTC
19:51:56 Info  [Launcher] Version: client c735370 / manifest b3dd620
19:51:56 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
19:51:56 Info  [Launcher] CPU supports SSSE3: YES
19:51:56 Trace [Launcher] Loading hybris libraries
19:51:56 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
19:51:56 Trace [HybrisUtils] Loaded OS library libm.so.6
19:51:56 Trace [HybrisUtils] Loaded OS library libz.so.1
19:51:56 Trace [Launcher] Loading Minecraft library
19:51:56 Info  [Launcher] Loaded Minecraft library
19:51:56 Debug [Launcher] Minecraft is at offset 0xec2e0000
19:51:56 Trace [Launcher] Initializing vtables
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
19:51:56 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
19:51:56 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x565eaebc]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fcaad0]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fcaab9]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf7851b06]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf783a3f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7b8893e]
#6 /usr/lib32/libstdc++.so.6(+0x839e7) [0xf7b969e7]
#7 /usr/lib32/libstdc++.so.6(+0x83a63) [0xf7b96a63]
#8 /usr/lib32/libstdc++.so.6(+0x83d95) [0xf7b96d95]
#9 /usr/bin/mcpelauncher-client(+0x4e9f4) [0x565b09f4]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x565ebdaf]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x565b45cc]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf9) [0xf783bfa9]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x565b5e65]
Dumping stack...
#3 HYBRIS (null)+-271621328 in libminecraftpe.so+0x3a16330 [0xefcf6330]
#5 HYBRIS (null)+-332529664 in libminecraftpe.so+0x0000 [0xec2e0000]
#23 HYBRIS (null)+-271606096 in libminecraftpe.so+0x3a19eb0 [0xefcf9eb0]
#24 HYBRIS (null)+-271616816 in libminecraftpe.so+0x3a174d0 [0xefcf74d0]
#28 HYBRIS (null)+-271602304 in libminecraftpe.so+0x3a1ad80 [0xefcfad80]
#29 HYBRIS (null)+-271606000 in libminecraftpe.so+0x3a19f10 [0xefcf9f10]
#69 HYBRIS (null)+-271535456 in libminecraftpe.so+0x3a2b2a0 [0xefd0b2a0]
#102 HYBRIS (null)+-209984496 in libminecraftpe.so+0x74de410 [0xf37be410]
#103 HYBRIS (null)+-271465968 in libminecraftpe.so+0x3a3c210 [0xefd1c210]
#104 HYBRIS (null)+-271472992 in libminecraftpe.so+0x3a3a6a0 [0xefd1a6a0]
#108 HYBRIS (null)+-271465824 in libminecraftpe.so+0x3a3c2a0 [0xefd1c2a0]
#109 HYBRIS (null)+-271465872 in libminecraftpe.so+0x3a3c270 [0xefd1c270]
#112 HYBRIS (null)+-323613457 in libminecraftpe.so+0x880cef [0xecb60cef]
#113 HYBRIS (null)+-271447584 in libminecraftpe.so+0x3a409e0 [0xefd209e0]
#114 HYBRIS (null)+-271451280 in libminecraftpe.so+0x3a3fb70 [0xefd1fb70]
#118 HYBRIS (null)+-271443792 in libminecraftpe.so+0x3a418b0 [0xefd218b0]
#119 HYBRIS (null)+-271447488 in libminecraftpe.so+0x3a40a40 [0xefd20a40]
#122 HYBRIS (null)+-210368252 in libminecraftpe.so+0x7480904 [0xf3760904]
#123 HYBRIS (null)+-271443648 in libminecraftpe.so+0x3a41940 [0xefd21940]
#124 HYBRIS (null)+-271443696 in libminecraftpe.so+0x3a41910 [0xefd21910]
#128 HYBRIS (null)+-271430512 in libminecraftpe.so+0x3a44c90 [0xefd24c90]
#129 HYBRIS (null)+-271432272 in libminecraftpe.so+0x3a445b0 [0xefd245b0]
#132 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ec5c [0xecceec5c]
#133 HYBRIS (null)+-271422928 in libminecraftpe.so+0x3a46a30 [0xefd26a30]
#134 HYBRIS (null)+-271430416 in libminecraftpe.so+0x3a44cf0 [0xefd24cf0]
#138 HYBRIS (null)+-271415808 in libminecraftpe.so+0x3a48600 [0xefd28600]
#139 HYBRIS (null)+-271422832 in libminecraftpe.so+0x3a46a90 [0xefd26a90]
#143 HYBRIS (null)+-271408224 in libminecraftpe.so+0x3a4a3a0 [0xefd2a3a0]
#144 HYBRIS (null)+-271415712 in libminecraftpe.so+0x3a48660 [0xefd28660]
#148 HYBRIS (null)+-271397408 in libminecraftpe.so+0x3a4cde0 [0xefd2cde0]
#149 HYBRIS (null)+-271408128 in libminecraftpe.so+0x3a4a400 [0xefd2a400]
#153 HYBRIS (null)+-271393616 in libminecraftpe.so+0x3a4dcb0 [0xefd2dcb0]
#154 HYBRIS (null)+-271397312 in libminecraftpe.so+0x3a4ce40 [0xefd2ce40]
#158 HYBRIS (null)+-271389824 in libminecraftpe.so+0x3a4eb80 [0xefd2eb80]
#159 HYBRIS (null)+-271393520 in libminecraftpe.so+0x3a4dd10 [0xefd2dd10]
#162 HYBRIS (null)+-210368252 in libminecraftpe.so+0x7480904 [0xf3760904]
#163 HYBRIS (null)+-271387888 in libminecraftpe.so+0x3a4f310 [0xefd2f310]
#164 HYBRIS (null)+-271389728 in libminecraftpe.so+0x3a4ebe0 [0xefd2ebe0]
#168 HYBRIS (null)+-271384096 in libminecraftpe.so+0x3a501e0 [0xefd301e0]
#169 HYBRIS (null)+-271387792 in libminecraftpe.so+0x3a4f370 [0xefd2f370]
#172 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ec5c [0xecceec5c]
#173 HYBRIS (null)+-271383952 in libminecraftpe.so+0x3a50270 [0xefd30270]
#174 HYBRIS (null)+-271384000 in libminecraftpe.so+0x3a50240 [0xefd30240]
#178 HYBRIS (null)+-271368880 in libminecraftpe.so+0x3a53d50 [0xefd33d50]
#179 HYBRIS (null)+-271372576 in libminecraftpe.so+0x3a52ee0 [0xefd32ee0]
#183 HYBRIS (null)+-271358064 in libminecraftpe.so+0x3a56790 [0xefd36790]
#184 HYBRIS (null)+-271368784 in libminecraftpe.so+0x3a53db0 [0xefd33db0]
#188 HYBRIS (null)+-271357920 in libminecraftpe.so+0x3a56820 [0xefd36820]
#189 HYBRIS (null)+-271357968 in libminecraftpe.so+0x3a567f0 [0xefd367f0]
#193 HYBRIS (null)+-271346496 in libminecraftpe.so+0x3a594c0 [0xefd394c0]
#194 HYBRIS (null)+-271346544 in libminecraftpe.so+0x3a59490 [0xefd39490]
#198 HYBRIS (null)+-271324400 in libminecraftpe.so+0x3a5eb10 [0xefd3eb10]
#199 HYBRIS (null)+-271335120 in libminecraftpe.so+0x3a5c130 [0xefd3c130]
#202 HYBRIS (null)+-210368252 in libminecraftpe.so+0x7480904 [0xf3760904]
#203 HYBRIS (null)+-271323392 in libminecraftpe.so+0x3a5ef00 [0xefd3ef00]
#204 HYBRIS (null)+-271324304 in libminecraftpe.so+0x3a5eb70 [0xefd3eb70]
#208 HYBRIS (null)+-271323248 in libminecraftpe.so+0x3a5ef90 [0xefd3ef90]
#209 HYBRIS (null)+-271323296 in libminecraftpe.so+0x3a5ef60 [0xefd3ef60]
#212 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ec5c [0xecceec5c]
#213 HYBRIS (null)+-271304384 in libminecraftpe.so+0x3a63940 [0xefd43940]
#214 HYBRIS (null)+-271311872 in libminecraftpe.so+0x3a61c00 [0xefd41c00]
#218 HYBRIS (null)+-271304240 in libminecraftpe.so+0x3a639d0 [0xefd439d0]
#219 HYBRIS (null)+-271304288 in libminecraftpe.so+0x3a639a0 [0xefd439a0]
#223 HYBRIS (null)+-271273840 in libminecraftpe.so+0x3a6b090 [0xefd4b090]
#224 HYBRIS (null)+-271273888 in libminecraftpe.so+0x3a6b060 [0xefd4b060]
#228 HYBRIS (null)+-271243440 in libminecraftpe.so+0x3a72750 [0xefd52750]
#229 HYBRIS (null)+-271243488 in libminecraftpe.so+0x3a72720 [0xefd52720]
#233 HYBRIS (null)+-271213040 in libminecraftpe.so+0x3a79e10 [0xefd59e10]
#234 HYBRIS (null)+-271213088 in libminecraftpe.so+0x3a79de0 [0xefd59de0]
#238 HYBRIS (null)+-271178992 in libminecraftpe.so+0x3a82310 [0xefd62310]
#239 HYBRIS (null)+-271182688 in libminecraftpe.so+0x3a814a0 [0xefd614a0]
#242 HYBRIS (null)+-210368252 in libminecraftpe.so+0x7480904 [0xf3760904]
#243 HYBRIS (null)+-271177984 in libminecraftpe.so+0x3a82700 [0xefd62700]
#244 HYBRIS (null)+-271178896 in libminecraftpe.so+0x3a82370 [0xefd62370]
#248 HYBRIS (null)+-271174192 in libminecraftpe.so+0x3a835d0 [0xefd635d0]
#249 HYBRIS (null)+-271177888 in libminecraftpe.so+0x3a82760 [0xefd62760]
#254 HYBRIS (null)+-271187965 in libminecraftpe.so+0x3a80003 [0xefd60003]
#259 HYBRIS (null)+-271163232 in libminecraftpe.so+0x3a860a0 [0xefd660a0]
#513 HYBRIS (null)+-319553526 in libminecraftpe.so+0xc6000a [0xecf4000a]
#778 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x7444d18 [0xf3724d18]
#779 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7444d20 [0xf3724d20]
#799 HYBRIS (null)+-332529664 in libminecraftpe.so+0x0000 [0xec2e0000]
Process exited with unexpected exit code: 6

**Comment by rcmonsterdude** [comment] 2020-02-07 20:23
same here. i had the app work once. closed app and came back to play. get logged in and when i click play it crashes.

**Comment by ChristopherHX** [comment] 2020-02-11 13:20
Look here for workaround
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903

**Comment by ChristopherHX** [comment] 2020-06-01 21:58
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:58 UTC
