### ISSUE TITLE
Minecraft Mac Mojave 10.14.6 crash process exited with unexpected exit code: 6

### ISSUE THREAD

**Issue by ImNotTechSmart** [minecraft-linux/mcpelauncher-manifest#316] opened 2020-05-25 04:16 UTC
00:11:28 Info  [Launcher] Version: client 7c17ac3 / manifest 05861bf
00:11:28 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
00:11:28 Info  [Launcher] CPU supports SSSE3: YES
00:11:28 Trace [Launcher] Loading hybris libraries
00:11:28 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
00:11:28 Trace [HybrisUtils] Loaded OS library libm.dylib
00:11:28 Error [HybrisUtils] Failed to load OS library libz.so.1
00:11:28 Info  [Launcher] Creating window
00:11:28 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
00:11:29 Trace [Launcher] Loading Minecraft library
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: load_library[1119]: Library '/Users/wildcat/Library/Application Support/mcpelauncher/versions/1.14.60.5/libs/libminecraftpe.so' not found
Signal 6 received
Backtrace elements: 12
#0 0   mcpelauncher-client                 0x00128477 _ZN12CrashHandler12handleSignalEiPv + 279
#1 1   libsystem_platform.dylib            0xa7cc6bae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7b8080e abort + 133
#4 4   libc++abi.dylib                     0xa5a45177 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa5a4531f _ZL25default_terminate_handlerv + 232
#6 6   libc++abi.dylib                     0xa5a501fd _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa5a4ffbc __cxa_get_exception_ptr + 0
#8 8   libc++abi.dylib                     0xa5a43a01 __cxa_get_globals + 0
#9 9   mcpelauncher-client                 0x001294e5 _ZN14MinecraftUtils16loadMinecraftLibERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 421
#10 10  mcpelauncher-client                 0x000414e4 main + 7172
#11 11  libdyld.dylib                       0xa7add051 start + 1
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ImNotTechSmart** [comment] 2020-05-25 04:47
I tried downloading another version of it and now it stays loading the game log and doesn't finish loading.

**Comment by DeanMcQueen** [comment] 2020-05-25 22:55
15:46:15 Info  [Launcher] Version: client 4432ade / manifest b4136d7
15:46:15 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
15:46:15 Info  [Launcher] CPU supports SSSE3: YES
15:46:15 Trace [Launcher] Loading hybris libraries
15:46:15 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher 119_10.10.0.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
15:46:15 Trace [HybrisUtils] Loaded OS library libm.dylib
15:46:15 Error [HybrisUtils] Failed to load OS library libz.so.1
15:46:15 Info  [Launcher] Creating window
15:46:15 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher 119_10.10.0.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
15:46:15 Trace [Launcher] Loading Minecraft library
15:46:15 Info  [Launcher] Loaded Minecraft library
15:46:15 Debug [Launcher] Minecraft is at offset 0x8d96000
15:46:15 Trace [AppPlatform] Vtable size = 295
15:46:15 Trace [Patch] Patching - original: 85 83 87 86 129
15:46:15 Trace [Patch] Patching - result: 233 11 35 211 242
15:46:15 Trace [Patch] Patching - original: 85 83 87 86 131
15:46:15 Trace [Patch] Patching - result: 233 59 97 210 242
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
15:46:15 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/Users/connerkrenzke/Library/Application Support/mcpelauncher/'
15:46:15 Error [JNIVM] Object not found in current local layer
15:46:15 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
15:46:15 Error [JNIVM] Object not found in current local layer
15:46:15 Debug [XSAPI.Android] Successfully registerered HttpCall methods
15:46:15 Error [JNIVM] Object not found in current local layer
15:46:15 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
15:46:15 Error [JNIVM] Object not found in current local layer
15:46:15 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
15:46:15 Error [JNIVM] Object not found in current local layer
15:46:15 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
15:46:15 Trace [XBOXLive] Reading xbox config file
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] EGL stub eglMakeCurrent called
15:46:15 Warn  [Launcher] EGL stub eglMakeCurrent called
15:46:15 Warn  [Launcher] Android stub called
15:46:15 Warn  [Launcher] EGL stub eglMakeCurrent called
15:46:15 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
15:46:15 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
15:46:16 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 61987
15:46:16 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 61988
15:46:19 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 57876
15:46:19 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 57877
potentially unsupported ioctl: 8912
potentially unsupported ioctl: 8912
potentially unsupported ioctl: 8912
potentially unsupported ioctl: 8912
potentially unsupported ioctl: 8912
15:46:23 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
15:46:23 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
15:46:23 Trace [DaemonLauncher] Starting daemon: /Applications/Minecraft Bedrock Launcher 119_10.10.0.app/Contents/MacOS/./msa-daemon
15:46:24 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
15:46:24 Trace [com::microsoft::xbox::idp::interop::Interop::LogCLL] log_cll 2535425381026137 Microsoft.XboxLive.T1739947436.SignInToXboxLive {"baseData":{"measurements":null,"name":"SignInToXboxLive","playerSessionId":"5bf9d200-0ff3-4414-80d1-863a1f978d6e","properties":{"AccountType":1,"ActiveSessionID":"1f4a772c-ab7b-4682-9773-ed999368035f","AppSessionID":"88be7a11-a403-4336-a440-cc55338e6db2","Build":"1.14.60","BuildPlat":1,"Cheevos":1,"ClientId":"19af3ae9-b15a-44b0-a3c2-aa2c66df489e","CurrentInput":1,"DeviceSessionId":"88be7a11-a403-4336-a440-cc55338e6db2","Plat":"","SchemaCommitHash":"19b6ec0744c3c83a00ecbd840f48cb080c7bc64d","Seq":76,"SignInUI":0,"Stage":4,"TimeStamp":9.3484459999999991,"Treatments":"mc-rp-pacman:mc-perf-plat-12-20:mc-perf-plat-1-20:mc-perf-plat-2-20:mc-perf-plat-4-20:mc-perf-plat-7-20:mc-perf-plat-13-20:mc-perf-plat-11-20:mc-rp-pdp-order:mc-rp-playfab","UserId":"2535425381026137","isTrial":0,"locale":"en"},"serviceConfigId":"00000000-0000-0000-0000-000067b57dac","titleId":"1739947436","userId":"2535425381026137","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
Signal 11 received
Backtrace elements: 4
#0 0   mcpelauncher-client                 0x0012c8d1 _ZN12CrashHandler12handleSignalEiPv + 273
#1 1   libsystem_platform.dylib            0xa7e3abae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x000b7c57 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7__allocEv + 23
Dumping stack...
#3 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#4 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#19 HYBRIS std::ios_base::~ios_base()+7 in libgnustl_shared.so+0x6b707 [0x8cf4707]
#24 HYBRIS (null)+270251912 in libminecraftpe.so+0x7425788 [0x101bb788]
#81 HYBRIS (null)+162141648 in libminecraftpe.so+0xd0b5d0 [0x9aa15d0]
#85 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#86 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#87 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#88 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#242 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+2007 in libminecraftpe.so+0x417c677 [0xcf12677]
#269 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#287 HYBRIS std::string::_Rep::_S_empty_rep_storage+12 in libgnustl_shared.so+0x10cb84 [0x8d95b84]
#306 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+0 in libminecraftpe.so+0x417bea0 [0xcf11ea0]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-05-27 15:22
@ImNotTechSmart Your launcher is outdated and cannot handle backward breaking changes.
Please follow the update notification, using older versions is unsupported.
If it stucks on starting you may need to redownload the game via the launcher or clean your launcher gamedata / cache. (Or just retry starting it a few times)
@DeanMcQueen Your issue is completly different, please open a new issue.

**Comment by ChristopherHX** [comment] 2020-06-02 16:12
duplicate of #311

**Closed by ChristopherHX** 2020-06-02 16:12 UTC

**Comment by ChristopherHX** [comment] 2020-06-02 21:23
Proposed fix starting with version 0.0.136 (stable), should be available soon.
