### ISSUE TITLE
Issues with installing??? - Help asap

### ISSUE THREAD

**Issue by breached82** [minecraft-linux/mcpelauncher-manifest#280] opened 2020-04-19 15:23 UTC
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127

Could anyone help me fix this?
Thanks! -Breached82

**Comment by ChristopherHX** [comment] 2020-06-03 21:23
duplicate of #94

**Closed by ChristopherHX** 2020-06-03 21:23 UTC
