### ISSUE TITLE
Arch linux x86_64; Intel HD 4000 Ivybridge game won't launch

### ISSUE THREAD

**Issue by Syndicate6690** [minecraft-linux/mcpelauncher-manifest#108] opened 2019-06-26 03:32 UTC
Just like the title suggests.

23:31:54 Info  [Launcher] Version: client 9d41f29 / manifest a7e2144
23:31:54 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz
23:31:54 Info  [Launcher] CPU supports SSSE3: YES
23:31:54 Trace [Launcher] Loading hybris libraries
23:31:54 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
23:31:54 Trace [HybrisUtils] Loaded OS library libm.so.6
23:31:54 Trace [HybrisUtils] Loaded OS library libz.so.1
23:31:54 Trace [Launcher] Loading Minecraft library
23:31:55 Info  [Launcher] Loaded Minecraft library
23:31:55 Debug [Launcher] Minecraft is at offset 0xee881000
23:31:55 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
23:31:55 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
Signal 11 received
Backtrace elements: 6
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x56671d9c]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f43940]
#2 /usr/bin/mcpelauncher-client(_Z22minecraft_symbols_initPv+0x19aa) [0x5669e22a]
#3 /usr/bin/mcpelauncher-client(main+0xc44) [0x566401e4]
#4 /usr/lib32/libc.so.6(__libc_start_main+0xf1) [0xf77d37d1]
#5 /usr/bin/mcpelauncher-client(_start+0x31) [0x56641881]
Dumping stack...
#15 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#22 HYBRIS (null)+-232680576 in libminecraftpe.so+0x3998380 [0xf2219380]
#26 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#30 HYBRIS (null)+-198388466 in libminecraftpe.so+0x5a4c50e [0xf42cd50e]
#32 HYBRIS Core::FileSystem::cleanPathSeparators_deprecated(Core::PathBuffer<Core::StackString<char, 1024u> >&, Core::Path)+12 in libminecraftpe.so+0x3966c2c [0xf21e7c2c]
#74 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#75 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#82 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#84 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#100 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#103 HYBRIS (null)+-206964757 in libminecraftpe.so+0x521e7eb [0xf3a9f7eb]
#104 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#105 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#106 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#109 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#116 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x39e1c9c [0xf2262c9c]
#118 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#119 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#121 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#122 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#123 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#126 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#128 HYBRIS (null)+-269737128 in libminecraftpe.so+0x1641358 [0xefec2358]
#129 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#130 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#131 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#134 HYBRIS (null)+-179072136 in libminecraftpe.so+0x6cb8378 [0xf5539378]
#135 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#175 HYBRIS (null)+-206964757 in libminecraftpe.so+0x521e7eb [0xf3a9f7eb]
#176 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#179 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#180 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned int, unsigned int, std::__detail::_Hash_node<std::pair<std::string const, std::string>, true>*)+71 in libminecraftpe.so+0x1675ab7 [0xefef6ab7]
#182 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x6c9f08c [0xf552008c]
#188 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x51cdba7 [0xf3a4eba7]
#192 HYBRIS xbox::services::serviceLocales+8 in libminecraftpe.so+0x6c9f084 [0xf5520084]
#193 HYBRIS (null)+-206938880 in libminecraftpe.so+0x5224d00 [0xf3aa5d00]
#198 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#200 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+212 in libminecraftpe.so+0x2051104 [0xf08d2104]
#202 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#208 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<std::string const, std::string>, false, true>, bool> std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > >(std::pair<std::string const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<std::string const, std::string>, true> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x205103c [0xf08d203c]
#218 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#220 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Hashtable<std::pair<std::string const, std::string> const*>(std::pair<std::string const, std::string> const*, std::pair<std::string const, std::string> const*, unsigned int, std::hash<std::string> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<std::string> const&, std::__detail::_Select1st const&, std::allocator<std::pair<std::string const, std::string> > const&)+236 in libminecraftpe.so+0x2905d1c [0xf1186d1c]
#222 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#226 HYBRIS (null)+-198365548 in libminecraftpe.so+0x5a51e94 [0xf42d2e94]
#228 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x51cdba7 [0xf3a4eba7]
#231 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#233 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x171add0 [0xeff9bdd0]
#234 HYBRIS (null)+-179072136 in libminecraftpe.so+0x6cb8378 [0xf5539378]
#235 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#242 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#245 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x171add0 [0xeff9bdd0]
#246 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#247 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#252 HYBRIS (null)+-269694444 in libminecraftpe.so+0x164ba14 [0xefecca14]
#253 HYBRIS std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x171add0 [0xeff9bdd0]
#254 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#255 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#502 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#503 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#531 HYBRIS (null)+-293072896 in libminecraftpe.so+0x0000 [0xee881000]
Process exited with unexpected exit code: 6

**Comment by Mhowser** [comment] 2019-06-26 03:35
What game version are you launching?

**Comment by MCMrARM** [comment] 2019-06-26 09:47
Duplicate of #104

**Closed by MCMrARM** 2019-06-26 09:47 UTC
