### ISSUE TITLE
Minecraft has exited with a non-zero error code

### ISSUE THREAD

**Issue by survivalbloke** [minecraft-linux/mcpelauncher-manifest#259] opened 2020-03-26 13:45 UTC
Seems I can only launch the game with the 1.14.1.5 version.  If I try to use the newer version marked "1.14.30.2(Installed)" or with the choice above that marked "Latest Version (Google Play)" then it shuts down with this error.

09:40:16 Info  [Launcher] Version: client c735370 / manifest b3dd620
09:40:16 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 7 2700X Eight-Core Processor         
09:40:16 Info  [Launcher] CPU supports SSSE3: YES
09:40:16 Trace [Launcher] Loading hybris libraries
09:40:16 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
09:40:16 Trace [HybrisUtils] Loaded OS library libm.so.6
09:40:16 Trace [HybrisUtils] Loaded OS library libz.so.1
09:40:16 Trace [Launcher] Loading Minecraft library
09:40:17 Info  [Launcher] Loaded Minecraft library
09:40:17 Debug [Launcher] Minecraft is at offset 0xedb2e000
09:40:17 Trace [Launcher] Initializing vtables
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
09:40:17 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
09:40:17 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x5667deec]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f80b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f80b49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf77f99b6]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf77e23f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7b3293e]
#6 /usr/lib32/libstdc++.so.6(+0x83957) [0xf7b40957]
#7 /usr/lib32/libstdc++.so.6(+0x839e3) [0xf7b409e3]
#8 /usr/lib32/libstdc++.so.6(+0x83d25) [0xf7b40d25]
#9 /usr/bin/mcpelauncher-client(+0x4e9d4) [0x566439d4]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x5667eddf]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x566475ac]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf5) [0xf77e3ee5]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x56648e45]
Dumping stack...
#4 HYBRIS (null)+-246045888 in libminecraftpe.so+0x3a2c340 [0xf155a340]
#5 HYBRIS (null)+-307044352 in libminecraftpe.so+0x0000 [0xedb2e000]
#24 HYBRIS (null)+-246001552 in libminecraftpe.so+0x3a37070 [0xf1565070]
#25 HYBRIS (null)+-246005248 in libminecraftpe.so+0x3a36200 [0xf1564200]
#28 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xee53cd5c]
#29 HYBRIS (null)+-245990688 in libminecraftpe.so+0x3a39ae0 [0xf1567ae0]
#30 HYBRIS (null)+-246001456 in libminecraftpe.so+0x3a370d0 [0xf15650d0]
#69 HYBRIS (null)+-245933408 in libminecraftpe.so+0x3a47aa0 [0xf1575aa0]
#70 HYBRIS (null)+-245940896 in libminecraftpe.so+0x3a45d60 [0xf1573d60]
#100 HYBRIS (null)+-245900208 in libminecraftpe.so+0x3a4fc50 [0xf157dc50]
#104 HYBRIS (null)+-245894576 in libminecraftpe.so+0x3a51250 [0xf157f250]
#105 HYBRIS (null)+-245898272 in libminecraftpe.so+0x3a503e0 [0xf157e3e0]
#108 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xee53cd5c]
#109 HYBRIS (null)+-245894432 in libminecraftpe.so+0x3a512e0 [0xf157f2e0]
#110 HYBRIS (null)+-245894480 in libminecraftpe.so+0x3a512b0 [0xf157f2b0]
#114 HYBRIS (null)+-245879360 in libminecraftpe.so+0x3a54dc0 [0xf1582dc0]
#115 HYBRIS (null)+-245883056 in libminecraftpe.so+0x3a53f50 [0xf1581f50]
#119 HYBRIS (null)+-245868544 in libminecraftpe.so+0x3a57800 [0xf1585800]
#120 HYBRIS (null)+-245879264 in libminecraftpe.so+0x3a54e20 [0xf1582e20]
#124 HYBRIS (null)+-245868400 in libminecraftpe.so+0x3a57890 [0xf1585890]
#125 HYBRIS (null)+-245868448 in libminecraftpe.so+0x3a57860 [0xf1585860]
#129 HYBRIS (null)+-245856976 in libminecraftpe.so+0x3a5a530 [0xf1588530]
#130 HYBRIS (null)+-245857024 in libminecraftpe.so+0x3a5a500 [0xf1588500]
#134 HYBRIS (null)+-245834880 in libminecraftpe.so+0x3a5fb80 [0xf158db80]
#135 HYBRIS (null)+-245845600 in libminecraftpe.so+0x3a5d1a0 [0xf158b1a0]
#138 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#139 HYBRIS (null)+-245833872 in libminecraftpe.so+0x3a5ff70 [0xf158df70]
#140 HYBRIS (null)+-245834784 in libminecraftpe.so+0x3a5fbe0 [0xf158dbe0]
#144 HYBRIS (null)+-245833728 in libminecraftpe.so+0x3a60000 [0xf158e000]
#145 HYBRIS (null)+-245833776 in libminecraftpe.so+0x3a5ffd0 [0xf158dfd0]
#148 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xee53cd5c]
#149 HYBRIS (null)+-245814864 in libminecraftpe.so+0x3a649b0 [0xf15929b0]
#150 HYBRIS (null)+-245822352 in libminecraftpe.so+0x3a62c70 [0xf1590c70]
#154 HYBRIS (null)+-245814720 in libminecraftpe.so+0x3a64a40 [0xf1592a40]
#155 HYBRIS (null)+-245814768 in libminecraftpe.so+0x3a64a10 [0xf1592a10]
#159 HYBRIS (null)+-245784320 in libminecraftpe.so+0x3a6c100 [0xf159a100]
#160 HYBRIS (null)+-245784368 in libminecraftpe.so+0x3a6c0d0 [0xf159a0d0]
#164 HYBRIS (null)+-245753920 in libminecraftpe.so+0x3a737c0 [0xf15a17c0]
#165 HYBRIS (null)+-245753968 in libminecraftpe.so+0x3a73790 [0xf15a1790]
#169 HYBRIS (null)+-245723520 in libminecraftpe.so+0x3a7ae80 [0xf15a8e80]
#170 HYBRIS (null)+-245723568 in libminecraftpe.so+0x3a7ae50 [0xf15a8e50]
#174 HYBRIS (null)+-245689472 in libminecraftpe.so+0x3a83380 [0xf15b1380]
#175 HYBRIS (null)+-245693168 in libminecraftpe.so+0x3a82510 [0xf15b0510]
#178 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#179 HYBRIS (null)+-245688464 in libminecraftpe.so+0x3a83770 [0xf15b1770]
#180 HYBRIS (null)+-245689376 in libminecraftpe.so+0x3a833e0 [0xf15b13e0]
#184 HYBRIS (null)+-245684672 in libminecraftpe.so+0x3a84640 [0xf15b2640]
#185 HYBRIS (null)+-245688368 in libminecraftpe.so+0x3a837d0 [0xf15b17d0]
#190 HYBRIS (null)+-245694461 in libminecraftpe.so+0x3a82003 [0xf15b0003]
#194 HYBRIS (null)+-245671872 in libminecraftpe.so+0x3a87840 [0xf15b5840]
#195 HYBRIS (null)+-245673712 in libminecraftpe.so+0x3a87110 [0xf15b5110]
#200 HYBRIS (null)+-296599060 in libminecraftpe.so+0x9f61ec [0xee5241ec]
#203 HYBRIS (null)+-241976928 in libminecraftpe.so+0x3e0d9a0 [0xf193b9a0]
#204 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#206 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#209 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x560af0c [0xf3138f0c]
#210 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf3136c36]
#211 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#212 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#214 HYBRIS (null)+-183988808 in libminecraftpe.so+0x755adb8 [0xf5088db8]
#216 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#218 HYBRIS (null)+-241976928 in libminecraftpe.so+0x3e0d9a0 [0xf193b9a0]
#219 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#221 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74fabf8 [0xf5028bf8]
#222 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#224 HYBRIS Core::StorageAreasTree::insertStorageArea(Core::FileStorageArea&)+316 in libminecraftpe.so+0x3dfae9c [0xf1928e9c]
#229 HYBRIS (null)+-245645632 in libminecraftpe.so+0x3a8dec0 [0xf15bbec0]
#234 HYBRIS (null)+-245643696 in libminecraftpe.so+0x3a8e650 [0xf15bc650]
#235 HYBRIS (null)+-245645536 in libminecraftpe.so+0x3a8df20 [0xf15bbf20]
#239 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#240 HYBRIS Core::Result::~Result()+9 in libminecraftpe.so+0x3e0d049 [0xf193b049]
#242 HYBRIS (null)+-184878844 in libminecraftpe.so+0x7481904 [0xf4faf904]
#243 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#244 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#245 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#246 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#247 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#248 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#249 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#250 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#251 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#252 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#253 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#254 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#255 HYBRIS (null)+-183988796 in libminecraftpe.so+0x755adc4 [0xf5088dc4]
#714 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x7445d18 [0xf4f73d18]
#715 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7445d20 [0xf4f73d20]
#735 HYBRIS (null)+-307044352 in libminecraftpe.so+0x0000 [0xedb2e000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-03-27 10:04
Works as designed by the dev. (not me)
These Versions works with this repository 0.12-1.13.0.6, 1.13.0.15, 1.13.0.34, 1.14.1.3 and 1.14.1.5
Try my version if you wish to run them anyways
Link under github forks.

**Comment by ChristopherHX** [comment] 2020-06-01 22:05
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:05 UTC
