### ISSUE TITLE
minecraft has exited with a non-zero error

### ISSUE THREAD

**Issue by Guzki** [minecraft-linux/mcpelauncher-manifest#206] opened 2019-12-15 16:49 UTC
11:47:38 Info  [Launcher] Version: client c735370 / manifest eb0bc83
11:47:38 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
11:47:38 Info  [Launcher] CPU supports SSSE3: YES
11:47:38 Trace [Launcher] Loading hybris libraries
11:47:38 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
11:47:38 Trace [HybrisUtils] Loaded OS library libm.so.6
11:47:38 Trace [HybrisUtils] Loaded OS library libz.so.1
11:47:38 Trace [Launcher] Loading Minecraft library
11:47:38 Info  [Launcher] Loaded Minecraft library
11:47:38 Debug [Launcher] Minecraft is at offset 0xed4c8000
11:47:38 Trace [Launcher] Initializing vtables
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
11:47:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
11:47:38 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567a2e43]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7ef2b60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7ef2b49]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf7739616]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf77213f7]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x7d7f6) [0xf7ab77f6]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x8be48) [0xf7ac5e48]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x8bec1) [0xf7ac5ec1]
#8 /lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7ac61f0]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x567f5cde]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567a463c]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567a4534]
#12 /usr/bin/mcpelauncher-client(main+0x10bc) [0x5674c7e0]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf9) [0xf7722fb9]
#14 /usr/bin/mcpelauncher-client(_start+0x31) [0x5674b241]
Dumping stack...
#1 HYBRIS (null)+-252862224 in libminecraftpe.so+0x3a120f0 [0xf0eda0f0]
#2 HYBRIS (null)+-252869712 in libminecraftpe.so+0x3a103b0 [0xf0ed83b0]
#13 HYBRIS (null)+-313753600 in libminecraftpe.so+0x0000 [0xed4c8000]
#32 HYBRIS (null)+-252818672 in libminecraftpe.so+0x3a1cb10 [0xf0ee4b10]
#36 HYBRIS (null)+-252811504 in libminecraftpe.so+0x3a1e710 [0xf0ee6710]
#37 HYBRIS (null)+-252811552 in libminecraftpe.so+0x3a1e6e0 [0xf0ee66e0]
#40 HYBRIS (null)+-304838753 in libminecraftpe.so+0x88079f [0xedd4879f]
#77 HYBRIS (null)+-252753808 in libminecraftpe.so+0x3a2c870 [0xf0ef4870]
#111 HYBRIS (null)+-252703744 in libminecraftpe.so+0x3a38c00 [0xf0f00c00]
#112 HYBRIS (null)+-252714464 in libminecraftpe.so+0x3a36220 [0xf0efe220]
#116 HYBRIS (null)+-252703600 in libminecraftpe.so+0x3a38c90 [0xf0f00c90]
#117 HYBRIS (null)+-252703648 in libminecraftpe.so+0x3a38c60 [0xf0f00c60]
#121 HYBRIS (null)+-252692176 in libminecraftpe.so+0x3a3b930 [0xf0f03930]
#122 HYBRIS (null)+-252692224 in libminecraftpe.so+0x3a3b900 [0xf0f03900]
#126 HYBRIS (null)+-252670080 in libminecraftpe.so+0x3a40f80 [0xf0f08f80]
#127 HYBRIS (null)+-252680800 in libminecraftpe.so+0x3a3e5a0 [0xf0f065a0]
#130 HYBRIS (null)+-191735556 in libminecraftpe.so+0x745d8fc [0xf49258fc]
#131 HYBRIS (null)+-252669072 in libminecraftpe.so+0x3a41370 [0xf0f09370]
#132 HYBRIS (null)+-252669984 in libminecraftpe.so+0x3a40fe0 [0xf0f08fe0]
#136 HYBRIS (null)+-252668928 in libminecraftpe.so+0x3a41400 [0xf0f09400]
#137 HYBRIS (null)+-252668976 in libminecraftpe.so+0x3a413d0 [0xf0f093d0]
#140 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ee2c [0xeded6e2c]
#141 HYBRIS (null)+-252650064 in libminecraftpe.so+0x3a45db0 [0xf0f0ddb0]
#142 HYBRIS (null)+-252657552 in libminecraftpe.so+0x3a44070 [0xf0f0c070]
#146 HYBRIS (null)+-252649920 in libminecraftpe.so+0x3a45e40 [0xf0f0de40]
#147 HYBRIS (null)+-252649968 in libminecraftpe.so+0x3a45e10 [0xf0f0de10]
#151 HYBRIS (null)+-252619520 in libminecraftpe.so+0x3a4d500 [0xf0f15500]
#152 HYBRIS (null)+-252619568 in libminecraftpe.so+0x3a4d4d0 [0xf0f154d0]
#156 HYBRIS (null)+-252589120 in libminecraftpe.so+0x3a54bc0 [0xf0f1cbc0]
#157 HYBRIS (null)+-252589168 in libminecraftpe.so+0x3a54b90 [0xf0f1cb90]
#161 HYBRIS (null)+-252558720 in libminecraftpe.so+0x3a5c280 [0xf0f24280]
#162 HYBRIS (null)+-252558768 in libminecraftpe.so+0x3a5c250 [0xf0f24250]
#166 HYBRIS (null)+-252524672 in libminecraftpe.so+0x3a64780 [0xf0f2c780]
#167 HYBRIS (null)+-252528368 in libminecraftpe.so+0x3a63910 [0xf0f2b910]
#170 HYBRIS (null)+-191735556 in libminecraftpe.so+0x745d8fc [0xf49258fc]
#171 HYBRIS (null)+-252523664 in libminecraftpe.so+0x3a64b70 [0xf0f2cb70]
#172 HYBRIS (null)+-252524576 in libminecraftpe.so+0x3a647e0 [0xf0f2c7e0]
#176 HYBRIS (null)+-252519872 in libminecraftpe.so+0x3a65a40 [0xf0f2da40]
#177 HYBRIS (null)+-252523568 in libminecraftpe.so+0x3a64bd0 [0xf0f2cbd0]
#182 HYBRIS (null)+-252575741 in libminecraftpe.so+0x3a58003 [0xf0f20003]
#192 HYBRIS (null)+-303309012 in libminecraftpe.so+0x9f5f2c [0xedebdf2c]
#195 HYBRIS (null)+-248819248 in libminecraftpe.so+0x3ded1d0 [0xf12b51d0]
#196 HYBRIS (null)+-190845564 in libminecraftpe.so+0x7536d84 [0xf49fed84]
#198 HYBRIS (null)+-191735556 in libminecraftpe.so+0x745d8fc [0xf49258fc]
#202 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x55e8076 [0xf2ab0076]
#203 HYBRIS (null)+-191735556 in libminecraftpe.so+0x745d8fc [0xf49258fc]
#206 HYBRIS (null)+-190845576 in libminecraftpe.so+0x7536d78 [0xf49fed78]
#208 HYBRIS (null)+-190845564 in libminecraftpe.so+0x7536d84 [0xf49fed84]
#213 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74d6ba8 [0xf499eba8]
#214 HYBRIS (null)+-191735556 in libminecraftpe.so+0x745d8fc [0xf49258fc]
#216 HYBRIS Core::StorageAreasTree::insertStorageArea(Core::FileStorageArea&)+316 in libminecraftpe.so+0x3dda77c [0xf12a277c]
#221 HYBRIS (null)+-252480832 in libminecraftpe.so+0x3a6f2c0 [0xf0f372c0]
#735 HYBRIS (null)+-313753600 in libminecraftpe.so+0x0000 [0xed4c8000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-01 21:52
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:52 UTC
