### ISSUE TITLE
I can't enter Chinese in the game

### ISSUE THREAD

**Issue by wyxa233** [minecraft-linux/mcpelauncher-manifest#230] opened 2020-02-03 04:55 UTC
I am a Chinese player.When I use this launcher to play Minecraft,I can't enter Chinese through my ime.So I can only copy and paste the text.That's so difficult!I don't know if there are other languages like this.Please help me.
(The level of my English is not very good, so I cannot make too much dialog with you. )

**Comment by ChristopherHX** [comment] 2020-02-05 17:50
I addresed your issue for linux, in [my fork](https://github.com/ChristopherHX/linux-packaging-scripts/releases).
Prebuilds with this patch are coming soon (Make shure to download a Release newer than this comment)

**Comment by ChristopherHX** [comment] 2020-06-04 12:41
duplicate of feature request #123

**Closed by ChristopherHX** 2020-06-04 12:41 UTC
