### ISSUE TITLE
exited with unexpected exit code 11

### ISSUE THREAD

**Issue by K1LL4** [minecraft-linux/mcpelauncher-manifest#279] opened 2020-04-18 21:44 UTC
22:37:15 Info  [Launcher] Version: client c735370 / manifest b3dd620
22:37:15 Info  [Launcher] CPU: AuthenticAMD AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G   
22:37:15 Info  [Launcher] CPU supports SSSE3: YES
22:37:15 Trace [Launcher] Loading hybris libraries
22:37:17 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
22:37:17 Trace [HybrisUtils] Loaded OS library libm.so.6
22:37:17 Trace [HybrisUtils] Loaded OS library libz.so.1
22:37:17 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by CarlosRoque** [comment] 2020-04-18 21:45
16:44:41 Info  [Launcher] Version: client c735370 / manifest e405b8c
16:44:41 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
16:44:41 Info  [Launcher] CPU supports SSSE3: YES
16:44:41 Trace [Launcher] Loading hybris libraries
16:44:41 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
16:44:41 Trace [HybrisUtils] Loaded OS library libm.so.6
16:44:41 Trace [HybrisUtils] Loaded OS library libz.so.1
16:44:41 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11


I am having the same issue

**Comment by 106217** [comment] 2020-04-19 06:31
Me too...
02:26:59 Info  [Launcher] Version: client c735370 / manifest b3dd620
02:26:59 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
02:26:59 Info  [Launcher] CPU supports SSSE3: YES
02:26:59 Trace [Launcher] Loading hybris libraries
02:26:59 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
02:26:59 Trace [HybrisUtils] Loaded OS library libm.so.6
02:26:59 Trace [HybrisUtils] Loaded OS library libz.so.1
02:26:59 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by tqaw19** [comment] 2020-04-22 01:05
20:00:50 Info  [Launcher] Version: client c735370 / manifest b3dd620
20:00:50 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
20:00:50 Info  [Launcher] CPU supports SSSE3: YES
20:00:50 Trace [Launcher] Loading hybris libraries
20:00:50 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrOsh6mE/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
20:00:50 Trace [HybrisUtils] Loaded OS library libm.so.6
20:00:50 Trace [HybrisUtils] Loaded OS library libz.so.1
20:00:50 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by MerlinTheMafiaMortician** [comment] 2020-04-25 17:28
Same here...
12:25:21 Info  [Launcher] Version: client c735370 / manifest b3dd620
12:25:21 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 5 2600 Six-Core Processor            
12:25:21 Info  [Launcher] CPU supports SSSE3: YES
12:25:21 Trace [Launcher] Loading hybris libraries
12:25:21 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
12:25:21 Trace [HybrisUtils] Loaded OS library libm.so.6
12:25:21 Trace [HybrisUtils] Loaded OS library libz.so.1
12:25:21 Trace [Launcher] Loading Minecraft library
linkerlinkerProcess exited with unexpected exit code: 11

**Comment by leetie** [comment] 2020-05-01 01:59
21:57:46 Info  [Launcher] Version: client c735370 / manifest b3dd620
21:57:46 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
21:57:46 Info  [Launcher] CPU supports SSSE3: YES
21:57:46 Trace [Launcher] Loading hybris libraries
21:57:46 Trace [HybrisUtils] Loaded OS library /home/jesse/mcpelauncher/mcpelauncher-linux-bin/libs/native/libfmod.so.9.16
21:57:46 Trace [HybrisUtils] Loaded OS library libm.so.6
21:57:46 Trace [HybrisUtils] Loaded OS library libz.so.1
21:57:46 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by jbeduya** [comment] 2020-05-15 00:09
08:09:05 Info  [Launcher] Version: client c735370 / manifest e405b8c
08:09:05 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 7 3700X 8-Core Processor             
08:09:05 Info  [Launcher] CPU supports SSSE3: YES
08:09:05 Trace [Launcher] Loading hybris libraries
08:09:05 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
08:09:05 Trace [HybrisUtils] Loaded OS library libm.so.6
08:09:05 Trace [HybrisUtils] Loaded OS library libz.so.1
08:09:05 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by ChristopherHX** [comment] 2020-06-01 21:35
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:35 UTC
