### ISSUE TITLE
  Failed to load Minecraft: Cannot load library: link_image[1965]

### ISSUE THREAD

**Issue by KoreaGD** [minecraft-linux/mcpelauncher-manifest#321] opened 2020-06-02 00:53 UTC
21:52:30 Info  [Launcher] Version: client c735370 / manifest b3dd620
21:52:30 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
21:52:30 Info  [Launcher] CPU supports SSSE3: YES
21:52:30 Trace [Launcher] Loading hybris libraries
21:52:30 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
21:52:30 Trace [HybrisUtils] Loaded OS library libm.so.6
21:52:30 Trace [HybrisUtils] Loaded OS library libz.so.1
21:52:30 Trace [Launcher] Loading Minecraft library
linker  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567f9729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f0db70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f0db59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf77e4832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf77e5cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b4297d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7b4a174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf7b4a1dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf7b4a4dc]
#9 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x183) [0x567fac03]
#10 /usr/bin/mcpelauncher-client(main+0xff8) [0x567956d4]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf77cfe81]
#12 /usr/bin/mcpelauncher-client(+0x1dc0f1) [0x567940f1]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-02 10:31
duplicate of #271

**Closed by ChristopherHX** 2020-06-02 10:31 UTC
