### ISSUE TITLE
Crash 1.14.0.6

### ISSUE THREAD

**Issue by KawaiiWinter** [minecraft-linux/mcpelauncher-manifest#184] opened 2019-11-12 10:31 UTC
> 19:30:06 Info  [Launcher] Version: client c735370 / manifest 4d4d51a
19:30:06 Info  [Launcher] CPU: GenuineIntel          Intel(R) Celeron(R) CPU G550 @ 2.60GHz
19:30:06 Info  [Launcher] CPU supports SSSE3: YES
19:30:06 Trace [Launcher] Loading hybris libraries
19:30:06 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
19:30:07 Trace [HybrisUtils] Loaded OS library libm.so.6
19:30:07 Trace [HybrisUtils] Loaded OS library libz.so.1
19:30:07 Trace [Launcher] Loading Minecraft library
19:30:08 Info  [Launcher] Loaded Minecraft library
19:30:08 Debug [Launcher] Minecraft is at offset 0xedfd1000
19:30:08 Trace [Launcher] Initializing vtables
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
19:30:08 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
19:30:08 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x566d76fc]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f7bb60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f7bb49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf77deb06]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf77c73f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7b1593e]
#6 /usr/lib32/libstdc++.so.6(+0x839e7) [0xf7b239e7]
#7 /usr/lib32/libstdc++.so.6(+0x83a63) [0xf7b23a63]
#8 /usr/lib32/libstdc++.so.6(+0x83d94) [0xf7b23d94]
#9 /usr/bin/mcpelauncher-client(+0x4c6d8) [0x566a06d8]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x566d85ef]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x566a534c]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf9) [0xf77c8fa9]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x566a6be5]
Dumping stack...
#1 HYBRIS (null)+-241703696 in libminecraftpe.so+0x39ad4f0 [0xf197e4f0]
#5 HYBRIS (null)+-302182400 in libminecraftpe.so+0x0000 [0xedfd1000]
#25 HYBRIS (null)+-241665040 in libminecraftpe.so+0x39b6bf0 [0xf1987bf0]
#26 HYBRIS (null)+-241668736 in libminecraftpe.so+0x39b5d80 [0xf1986d80]
#30 HYBRIS (null)+-241661248 in libminecraftpe.so+0x39b7ac0 [0xf1988ac0]
#31 HYBRIS (null)+-241664944 in libminecraftpe.so+0x39b6c50 [0xf1987c50]
#67 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#70 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#100 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#101 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#103 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#104 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#106 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#107 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#109 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#110 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#112 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#113 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#115 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#116 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#118 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#119 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#121 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#122 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#124 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#125 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#127 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#128 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#130 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#131 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#133 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#134 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#136 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#137 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#139 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#140 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#142 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#143 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#145 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#146 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#148 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#149 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#151 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#152 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#154 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#155 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#157 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#158 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#160 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#161 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#163 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#164 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#166 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#167 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#169 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#170 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#172 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#173 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#175 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#176 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#178 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#179 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#181 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#182 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#184 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#185 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#187 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#188 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#190 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#191 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#193 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#194 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#196 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#197 HYBRIS (null)+-212161791 in libminecraftpe.so+0x55d9b01 [0xf35aab01]
#199 HYBRIS (null)+-212161612 in libminecraftpe.so+0x55d9bb4 [0xf35aabb4]
#650 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x7352ec8 [0xf5323ec8]
#651 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7352ed0 [0xf5323ed0]
#671 HYBRIS (null)+-302182400 in libminecraftpe.so+0x0000 [0xedfd1000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2019-11-12 11:06
Duplicate of **1.14.x beta** #181 #163  not working
@KawaiiWinter Please wait at least till some days after its offical Release, betas 1.14 are **not Supported in this Repo**

If you can't wait to play it, use my [Fork](https://github.com/ChristopherHX/mcpelauncher-manifest/tree/master) **with some other limitations** of this Launcher which utilizes another approach since the disappearing of a lot of used Debugging Information.

**Closed by ChristopherHX** 2019-11-12 11:06 UTC
