### ISSUE TITLE
Could not find the game launcher on MacOS Catalina?

### ISSUE THREAD

**Issue by mtoensing** [minecraft-linux/mcpelauncher-manifest#254] opened 2020-03-24 12:58 UTC
Hi! 

What can I do to fix this? I don't understand how this is relevant https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html#could-not-find-the-game-launcher

**Comment by ChristopherHX** [comment] 2020-06-03 14:30
duplicate of #100

**Closed by ChristopherHX** 2020-06-03 14:30 UTC
