### ISSUE TITLE
Can't open 1.13.1.5 on MacOS 10.13.6

### ISSUE THREAD

**Issue by 4nZwar3** [minecraft-linux/mcpelauncher-manifest#192] opened 2019-11-17 15:34 UTC
Code:

09:32:38 Info  [Launcher] Version: client c735370 / manifest eb0bc83
09:32:38 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
09:32:38 Info  [Launcher] CPU supports SSSE3: YES
09:32:38 Trace [Launcher] Loading hybris libraries
09:32:39 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
09:32:39 Trace [HybrisUtils] Loaded OS library libm.dylib
09:32:39 Error [HybrisUtils] Failed to load OS library libz.so.1
09:32:39 Trace [Launcher] Loading Minecraft library
09:32:44 Info  [Launcher] Loaded Minecraft library
09:32:44 Debug [Launcher] Minecraft is at offset 0x2a6b000
09:32:44 Trace [Launcher] Initializing vtables
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
09:32:44 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
09:32:44 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 0   mcpelauncher-client                 0x0011088e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa757502b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7316956 abort + 133
#4 4   libc++abi.dylib                     0xa56d7ea7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa56d806a _ZL25default_terminate_handlerv + 250
#6 6   libc++abi.dylib                     0xa56f1657 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa56f10c1 __cxa_throw + 116
#8 8   mcpelauncher-client                 0x0018c18c _Z21minecraft_get_versionPiS_S_S_ + 396
#9 9   mcpelauncher-client                 0x001127f9 _ZN16MinecraftVersion4initEv + 57
#10 10  mcpelauncher-client                 0x00111f85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#11 11  mcpelauncher-client                 0x00056790 main + 10208
#12 12  libdyld.dylib                       0xa726c611 start + 1
#13 13  ???                                 0x00000005 0x0 + 5
Dumping stack...
#485 HYBRIS (null)+46713616 in libminecraftpe.so+0x221b10 [0x2c8cb10]
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0x9ccbf60]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0x9ccbf60]
#627 HYBRIS (null)+44478464 in libminecraftpe.so+0x0000 [0x2a6b000]
#674 HYBRIS (null)+44478464 in libminecraftpe.so+0x0000 [0x2a6b000]
#675 HYBRIS (null)+44478464 in libminecraftpe.so+0x0000 [0x2a6b000]
Process exited with unexpected exit code: 6

**Comment by edeleflie** [comment] 2019-12-04 09:50
I have the same issue on the same version of OSX ... 10.13.6

**Comment by ChristopherHX** [comment] 2020-06-01 21:48
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:48 UTC
