### ISSUE TITLE
My game doesn't start

### ISSUE THREAD

**Issue by ItzLightyHD** [minecraft-linux/mcpelauncher-manifest#226] opened 2020-01-26 17:47 UTC
![Why?](https://user-images.githubusercontent.com/45460688/73139239-3fd83100-406c-11ea-8dac-910d80829498.png)

I just used a x86 APK, but the game doesn't start.

**Comment by Mhowser** [comment] 2020-01-26 18:08
Install 32bit graphics drivers
https://mcpelauncher.readthedocs.io/en/latest/troubleshooting.html

**Comment by ItzLightyHD** [comment] 2020-01-26 18:12
I already did this, probably the launcher doesn't support 1.14

**Comment by Mhowser** [comment] 2020-01-26 18:15
Are you in the discord support server? I can help you faster there
https://discord.gg/27TUUwf

**Comment by ChristopherHX** [comment] 2020-06-07 17:28
duplicate of #94

**Closed by ChristopherHX** 2020-06-07 17:28 UTC
