### ISSUE TITLE
Crashing Issue.

### ISSUE THREAD

**Issue by MoonCraftGames** [minecraft-linux/mcpelauncher-manifest#317] opened 2020-05-27 05:44 UTC
01:44:17 Info  [Launcher] Version: client 4432ade / manifest b4136d7
01:44:17 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
01:44:17 Info  [Launcher] CPU supports SSSE3: YES
01:44:17 Trace [Launcher] Loading hybris libraries
01:44:17 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
01:44:17 Trace [HybrisUtils] Loaded OS library libm.dylib
01:44:17 Error [HybrisUtils] Failed to load OS library libz.so.1
01:44:17 Info  [Launcher] Creating window
01:44:17 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
01:44:17 Trace [Launcher] Loading Minecraft library
01:44:18 Info  [Launcher] Loaded Minecraft library
01:44:18 Debug [Launcher] Minecraft is at offset 0x509e000
01:44:18 Trace [AppPlatform] Vtable size = 295
01:44:18 Trace [Patch] Patching - original: 85 83 87 86 129
01:44:18 Trace [Patch] Patching - result: 233 155 96 171 246
01:44:18 Trace [Patch] Patching - original: 85 83 87 86 131
01:44:18 Trace [Patch] Patching - result: 233 203 158 170 246
01:44:18 Warn  [Launcher] Android stub called
01:44:18 Warn  [Launcher] Android stub called
01:44:18 Warn  [Launcher] Android stub called
01:44:18 Warn  [Launcher] Android stub called
01:44:18 Warn  [Launcher] Android stub called
01:44:18 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
01:44:18 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/Users/admin/Library/Application Support/mcpelauncher/'
01:44:18 Error [JNIVM] Object not found in current local layer
01:44:18 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
01:44:18 Error [JNIVM] Object not found in current local layer
01:44:18 Debug [XSAPI.Android] Successfully registerered HttpCall methods
01:44:18 Error [JNIVM] Object not found in current local layer
01:44:18 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
01:44:18 Error [JNIVM] Object not found in current local layer
01:44:18 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
01:44:18 Error [JNIVM] Object not found in current local layer
01:44:18 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
01:44:18 Trace [XBOXLive] Reading xbox config file
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
01:44:19 Warn  [Launcher] Android stub called
01:44:19 Warn  [Launcher] EGL stub eglMakeCurrent called
01:44:19 Warn  [Launcher] EGL stub eglMakeCurrent called
01:44:19 Warn  [Launcher] Android stub called
01:44:19 Warn  [Launcher] EGL stub eglMakeCurrent called
01:44:19 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
01:44:19 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
01:44:21 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 50550
01:44:21 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 50551
01:44:22 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
01:44:22 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
01:44:31 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
01:44:31 Trace [com::microsoft::xbox::idp::interop::Interop::LogCLL] log_cll 2535425039234731 Microsoft.XboxLive.T1739947436.SignInToXboxLive {"baseData":{"measurements":null,"name":"SignInToXboxLive","playerSessionId":"a8c27cda-bb38-4a97-a559-2aef54dc3c79","properties":{"AccountType":1,"ActiveSessionID":"1a75daaa-c745-4f48-b332-48ff40bdc864","AppSessionID":"3b78374d-ff3e-49a5-9cdb-56d425ca909f","Build":"1.14.20","BuildPlat":1,"Cheevos":1,"ClientId":"19af3ae9-b15a-44b0-a3c2-aa2c66df489e","CurrentInput":2,"DeviceSessionId":"3b78374d-ff3e-49a5-9cdb-56d425ca909f","Plat":"","SchemaCommitHash":"19b6ec0744c3c83a00ecbd840f48cb080c7bc64d","Seq":7,"SignInUI":0,"Stage":4,"TimeStamp":13.817542,"Treatments":"","UserId":"2535425039234731","locale":"en"},"serviceConfigId":"00000000-0000-0000-0000-000067b57dac","titleId":"1739947436","userId":"2535425039234731","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
Signal 11 received
Backtrace elements: 4
#0 0   mcpelauncher-client                 0x001a38d1 _ZN12CrashHandler12handleSignalEiPv + 273
#1 1   libsystem_platform.dylib            0xa7dffbae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x0012ec57 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7__allocEv + 23
Dumping stack...
#3 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#4 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#19 HYBRIS (null)+174755367 in libminecraftpe.so+0x560ae27 [0xa6a8e27]
#25 HYBRIS (null)+206674176 in libminecraftpe.so+0x747b900 [0xc519900]
#34 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+1992 in libminecraftpe.so+0x41678d8 [0x92058d8]
#82 HYBRIS (null)+98218560 in libminecraftpe.so+0xd0d240 [0x5dab240]
#86 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#87 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#88 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#89 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#269 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#287 HYBRIS (null)+207564228 in libminecraftpe.so+0x7554dc4 [0xc5f2dc4]
#306 HYBRIS xbox::services::system::user_auth_android::get_uploader_x_token_callback(_JNIEnv*, _jclass*, unsigned char)+0 in libminecraftpe.so+0x4167110 [0x9205110]
#409 HYBRIS (null)+131611328 in libminecraftpe.so+0x2ce5ac0 [0x7d83ac0]
#942 HYBRIS (null)+133170014 in libminecraftpe.so+0x2e6235e [0x7f0035e]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-05-27 12:11
Please retry starting it, at least 5 times.
It is macOS specfic issue with xbox live archivements.
Disabling xbox live archivements was the previous now removed WORKAROUND

**Comment by ChristopherHX** [comment] 2020-06-01 21:01
duplicate of #311

**Closed by ChristopherHX** 2020-06-01 21:01 UTC

**Comment by ChristopherHX** [comment] 2020-06-02 21:24
Proposed fix starting with version 0.0.136 (stable), should be available soon.
