### ISSUE TITLE
1.13.1.5 cant play

### ISSUE THREAD

**Issue by mrwoowoo** [minecraft-linux/mcpelauncher-manifest#200] opened 2019-11-30 10:51 UTC
18:50:25 Info  [Launcher] Version: client c735370 / manifest eb0bc83
18:50:25 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
18:50:25 Info  [Launcher] CPU supports SSSE3: YES
18:50:25 Trace [Launcher] Loading hybris libraries
18:50:25 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
18:50:25 Trace [HybrisUtils] Loaded OS library libm.so.6
18:50:25 Trace [HybrisUtils] Loaded OS library libz.so.1
18:50:25 Trace [Launcher] Loading Minecraft library
18:50:26 Info  [Launcher] Loaded Minecraft library
18:50:26 Debug [Launcher] Minecraft is at offset 0xed35b000
18:50:26 Trace [Launcher] Initializing vtables
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
18:50:26 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
18:50:26 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567fe7db]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f57090]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f57079]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7833832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7834cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b9197d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7b990f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7b9915d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7b9945c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x56852f4b]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567fffd4]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567ffecc]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567a71de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf781ee81]
#14 /usr/bin/mcpelauncher-client(+0x1c8b31) [0x567a5b31]
Dumping stack...
#1 HYBRIS (null)+-255577712 in libminecraftpe.so+0x38e8190 [0xf0c43190]
#13 HYBRIS (null)+-315248640 in libminecraftpe.so+0x0000 [0xed35b000]
#31 HYBRIS (null)+-255522368 in libminecraftpe.so+0x38f59c0 [0xf0c509c0]
#34 HYBRIS (null)+-195069376 in libminecraftpe.so+0x729ca40 [0xf45f7a40]
#35 HYBRIS (null)+-255508224 in libminecraftpe.so+0x38f9100 [0xf0c54100]
#36 HYBRIS (null)+-255515248 in libminecraftpe.so+0x38f7590 [0xf0c52590]
#40 HYBRIS (null)+-255508080 in libminecraftpe.so+0x38f9190 [0xf0c54190]
#75 HYBRIS (null)+-255450480 in libminecraftpe.so+0x3907290 [0xf0c62290]
#79 HYBRIS (null)+-194961408 in libminecraftpe.so+0x72b7000 [0xf4612000]
#110 HYBRIS (null)+-255411136 in libminecraftpe.so+0x3910c40 [0xf0c6bc40]
#111 HYBRIS (null)+-255414832 in libminecraftpe.so+0x390fdd0 [0xf0c6add0]
#113 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#116 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#119 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#120 HYBRIS (null)+-255400191 in libminecraftpe.so+0x3913701 [0xf0c6e701]
#121 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#122 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#124 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#125 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#127 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#128 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#130 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#131 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#133 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#134 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#136 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#137 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#139 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#140 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#142 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#143 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#145 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#146 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#148 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#149 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#151 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#152 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#154 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#155 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#157 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#158 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#160 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#161 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#163 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#164 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#166 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#167 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#169 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#170 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#172 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#173 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#175 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#176 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#178 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#179 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#181 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#182 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#184 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#185 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#187 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#188 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#190 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#191 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#193 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#194 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#196 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#197 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#199 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#200 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#202 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#203 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#205 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#206 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#208 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#209 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#211 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#212 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#214 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#215 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#217 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#221 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#223 HYBRIS (null)+-225932804 in libminecraftpe.so+0x552d9fc [0xf28889fc]
#224 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#227 HYBRIS (null)+-225933055 in libminecraftpe.so+0x552d901 [0xf2888901]
#739 HYBRIS (null)+-315248640 in libminecraftpe.so+0x0000 [0xed35b000]
Process exited with unexpected exit code: 6

**Comment by justindthomas** [comment] 2019-11-30 18:30
I'm seeing this too. Using Pop!_OS 19.10 (Ubuntu 19.10).

**Comment by TGC-TECH** [comment] 2019-12-02 23:23
Same issue

**Comment by beckadamtheinventor** [comment] 2019-12-08 15:09
same issue also.

**Comment by TheRealKizu** [comment] 2019-12-10 05:39
Same issue here.

**Comment by Tiixxel** [comment] 2019-12-10 13:14
Getting the same issue.

**Comment by uzyandev** [comment] 2019-12-10 14:04
As I understand it, due to the fact that Mojang removed the debug characters

**Comment by thijs** [comment] 2019-12-10 19:31
This fork seems to work (at least, is starts 1.14 for me), but has other issues (for me) : https://github.com/ChristopherHX/mcpelauncher-manifest

**Comment by ChristopherHX** [comment] 2020-06-01 21:50
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:50 UTC
