### ISSUE TITLE
MC Launcher still crashes constantly while loading

### ISSUE THREAD

**Issue by santiagoitzcoatl** [minecraft-linux/mcpelauncher-manifest#319] opened 2020-06-01 03:44 UTC
I opened a different issue as it now shows a different exit code, even if I didn't change anything.

Today it kept crashing every time.

I'm in Mac OS 10.14.6 and I'm using Launcher 0.1.129

>22:42:45 Info  [Launcher] Version: client 4432ade / manifest b4136d7
22:42:45 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
22:42:45 Info  [Launcher] CPU supports SSSE3: YES
22:42:45 Trace [Launcher] Loading hybris libraries
22:42:45 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
22:42:45 Trace [HybrisUtils] Loaded OS library libm.dylib
22:42:45 Error [HybrisUtils] Failed to load OS library libz.so.1
22:42:45 Info  [Launcher] Creating window
22:42:45 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
22:42:45 Trace [Launcher] Loading Minecraft library
22:42:46 Info  [Launcher] Loaded Minecraft library
22:42:46 Debug [Launcher] Minecraft is at offset 0x6319000
22:42:46 Trace [AppPlatform] Vtable size = 295
22:42:46 Trace [Patch] Patching - original: 85 83 87 86 129
22:42:46 Trace [Patch] Patching - result: 233 11 115 131 245
22:42:46 Trace [Patch] Patching - original: 85 83 87 86 131
22:42:46 Trace [Patch] Patching - result: 233 59 177 130 245
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Info  [Minecraft] android_main starting. internalDataPath is './idata/', externalDataPath is './edata/'
22:42:46 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/Users/Santiago/Library/Application Support/mcpelauncher/'
22:42:46 Error [JNIVM] Object not found in current local layer
22:42:46 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
22:42:46 Error [JNIVM] Object not found in current local layer
22:42:46 Debug [XSAPI.Android] Successfully registerered HttpCall methods
22:42:46 Error [JNIVM] Object not found in current local layer
22:42:46 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
22:42:46 Error [JNIVM] Object not found in current local layer
22:42:46 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
22:42:46 Error [JNIVM] Object not found in current local layer
22:42:46 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
22:42:46 Trace [XBOXLive] Reading xbox config file
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
unsupported prctl 15
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] EGL stub eglMakeCurrent called
22:42:46 Warn  [Launcher] EGL stub eglMakeCurrent called
22:42:46 Warn  [Launcher] Android stub called
22:42:46 Warn  [Launcher] EGL stub eglMakeCurrent called
22:42:46 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
22:42:46 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
22:43:02 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 53829
22:43:02 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 53830
22:43:03 Debug [XSAPI.Android] sign_in_impl: will NOT be showing UI
22:43:03 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Entering
22:43:03 Trace [DaemonLauncher] Starting daemon: /Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./msa-daemon
22:43:03 Info  [com::microsoft::xbox::idp::interop::Interop::LogTelemetrySignIn] API - signin_silently - :Exiting
22:43:03 Trace [com::microsoft::xbox::idp::interop::Interop::LogCLL] log_cll 2535410647803322 Microsoft.XboxLive.T1739947436.SignInToXboxLive {"baseData":{"measurements":null,"name":"SignInToXboxLive","playerSessionId":"0df4ea3e-5a45-45b2-9c22-430c7e2027da","properties":{"AccountType":1,"ActiveSessionID":"8d645219-0be1-4e9a-922a-c531605516cd","AppSessionID":"1ce07897-b942-457c-99ba-f6d3babd90ce","Build":"1.14.60","BuildPlat":1,"Cheevos":1,"ClientId":"19af3ae9-b15a-44b0-a3c2-aa2c66df489e","CurrentInput":2,"DeviceSessionId":"1ce07897-b942-457c-99ba-f6d3babd90ce","Plat":"","SchemaCommitHash":"19b6ec0744c3c83a00ecbd840f48cb080c7bc64d","Seq":6,"SignInUI":0,"Stage":4,"TimeStamp":17.478943999999998,"UserId":"2535410647803322","locale":"en"},"serviceConfigId":"00000000-0000-0000-0000-000067b57dac","titleId":"1739947436","userId":"2535410647803322","ver":1},"baseType":"Microsoft.XboxLive.InGame"}

Process exited with unexpected exit code: 10

**Comment by ChristopherHX** [comment] 2020-06-01 20:52
duplicate of #317

**Closed by ChristopherHX** 2020-06-01 20:52 UTC
