### ISSUE TITLE
Non-zero error code

### ISSUE THREAD

**Issue by jurassicjordan** [minecraft-linux/mcpelauncher-manifest#212] opened 2019-12-26 19:58 UTC
theres probably like 50 of these so, lemme just give you the crash report and steps and ill be on my way.

due to the inability to log in to google I used bluestacks to download and export an apk of the latest verson of bedrock. I imported it and of course with high expectations the game crashes :/

crash report:
11:54:43 Info  [Launcher] Version: client c735370 / manifest eb0bc83
11:54:43 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
11:54:43 Info  [Launcher] CPU supports SSSE3: YES
11:54:43 Trace [Launcher] Loading hybris libraries
11:54:43 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
11:54:43 Trace [HybrisUtils] Loaded OS library libm.dylib
11:54:43 Error [HybrisUtils] Failed to load OS library libz.so.1
11:54:43 Trace [Launcher] Loading Minecraft library
11:54:43 Info  [Launcher] Loaded Minecraft library
11:54:43 Debug [Launcher] Minecraft is at offset 0x53a8000
11:54:43 Trace [Launcher] Initializing vtables
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
11:54:43 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
11:54:43 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 13
#0 0   mcpelauncher-client                 0x0016488e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa17c3e5b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa1649a34 abort + 141
#4 4   libc++abi.dylib                     0xa01d1df7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa01f2371 _ZL25default_terminate_handlerv + 244
#6 6   libc++abi.dylib                     0xa01ef551 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa01eef7b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
#8 8   mcpelauncher-client                 0x001e018c _Z21minecraft_get_versionPiS_S_S_ + 396
#9 9   mcpelauncher-client                 0x001667f9 _ZN16MinecraftVersion4initEv + 57
#10 10  mcpelauncher-client                 0x00165f85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#11 11  mcpelauncher-client                 0x000aa790 main + 10208
#12 12  libdyld.dylib                       0xa15ba395 start + 1
Dumping stack...
#480 HYBRIS (null)+128466574 in libminecraftpe.so+0x26dbe8e [0x7a83e8e]
#518 HYBRIS (null)+87720212 in libminecraftpe.so+0x0114 [0x53a8114]
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0xc608f60]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7260f60 [0xc608f60]
#627 HYBRIS (null)+87719936 in libminecraftpe.so+0x0000 [0x53a8000]
#674 HYBRIS (null)+87719936 in libminecraftpe.so+0x0000 [0x53a8000]
#675 HYBRIS (null)+87719936 in libminecraftpe.so+0x0000 [0x53a8000]
Process exited with unexpected exit code: 6

**Comment by foxxgaming** [comment] 2019-12-26 23:08
same issue. seems to be no fix right now, so it's best to just stick with 1.13 and below. my friend bought a realm for 1.14 except since my launcher doesnt wanna run it i cant open it. :(

**Comment by Mhowser** [comment] 2019-12-27 06:45
1.14 works on Linux right now, update your launcher. And if you are on Mac, use Chris's fork. https://GitHub.com/ChristopherHX/mcpelauncher-manifest

**Comment by raphtlw** [comment] 2020-02-01 08:35
@Mhowser Minecraft 1.14 doesn't work on Ubuntu 18.04 for me. I'm getting the same error as OP.

**Comment by ChristopherHX** [comment] 2020-06-01 21:55
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:55 UTC
