### ISSUE TITLE
No Crossplay for any 1.13 versions

### ISSUE THREAD

**Issue by imsarg** [minecraft-linux/mcpelauncher-manifest#197] opened 2019-11-22 17:03 UTC
Launcher has allowed me to play between this APK and Nintendo Switch flawlessly for at least 6 months.

Since version 1.13 it appears as though the Microsoft account is not signing in correctly. 
Testing now in 1.13.0.34 I can see my name under my character and can browse the in-game 'marketplace' but it does not allow me to find any crossplay games or accept invites from friends. The 'feedback' button on the bottom left does nothing, and selecting 'Play -> Add Friend' also does nothing. 
The friends tab has a strange black splodge underneath in 1.13 versions. https://i.imgur.com/YFXgFht.png
Reproduced the same issue in:
1.13.0.6
1.13.0.4
1.13.0.2
1.13.0.1

Version 1.13.1.5 does not launch at all. That's another issue for another report.

Launching 1.12.1.1 loads into the game, signs into the Microsoft account and finds the crossplay game immediately. Trying to join says 'Could not connect: Outdated client!'. Nintendo switch must be updating itself automatically.

**Comment by ChristopherHX** [comment] 2019-11-23 10:01
Try [my fork](https://github.com/ChristopherHX/mcpelauncher-manifest/blob/master/README.md), someone said it shows friends worlds on 1.13.1.5
I modified the xboxlive login Method to use the "Java Interface", while not using Java.
It also supports 1.14+

**Comment by imsarg** [comment] 2019-11-25 16:30
Thanks for the reply ChristopherHX.

I ran through the 'Build from Source' instructions on your fork and can confirm that the following versions can log into the xbox live account and crossplay with Nintendo Switch:
- 1.13.0.34
- 1.13.1.5

However, I'm now getting some strange visual bugs. I haven't looked more into it at this stage and will revert back if I find anything. An example can be seen here: 
https://i.imgur.com/KatW59w.png

If left to stand stationary for long enough it will eventually 'clean' itself, but moving kind of 'smears' the bottom portion of the screen.

**Comment by ChristopherHX** [comment] 2019-11-26 09:44
You ran into a know issue of my fork, something with nvideas drivers is not working correctly with my entry point, at least I think you have that gpu.
I wish, I find a way to reproduce the issue. (Only my windows laptop has an nvidea gpu, but no linux)

**Comment by zvillager10** [comment] 2019-12-02 00:56
> Try [my fork](https://github.com/ChristopherHX/mcpelauncher-manifest/blob/master/README.md), someone said it shows friends worlds on 1.13.1.5
> I modified the xboxlive login Method to use the "Java Interface", while not using Java.
> It also supports 1.14+
> 
> Play -> add friend isn't implemented, use xbox.com to add friends

hey I'm on linux mint/ubuntu 18.04 what package should I use? or should I build it from source? Please answer soon.

**Comment by ChristopherHX** [comment] 2019-12-02 08:17
@zvillager10 Why not installing https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/34.bionic

bionic = ubuntu 18.04

If you installed this launcher already you need only [mcpelauncher-client-*.deb](https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/34.bionic/mcpelauncher-client-bff1e89-Linux.deb)
Install the .deb via `sudo dpkg -i mcpelauncher-client-*.deb && sudo apt-get install -f` or use the ui to install it

**Comment by zvillager10** [comment] 2019-12-02 11:19
do I need to uninstall first launcher???

**Comment by ChristopherHX** [comment] 2019-12-02 12:24
No it will be overwritten by dpkg automatically, like an update thought apt-get (It shares the same packet identifier with the original).
To reinstall the Original Launcher `sudo apt remove mcpelauncher-client && sudo apt install mcpelauncher-client`

**Comment by zvillager10** [comment] 2019-12-16 16:53
After using your fork version of the launcher for quite the while now, I
noticed that your version is not compatible with the command that helps
reduce the lagspikes when playing pvp; mcpelauncher-client -dg
~/.local/share/mcpelauncher/versions/1.2.3.4

**Comment by zvillager10** [comment] 2019-12-21 03:00
hi, how to delete your fork version

**Comment by ChristopherHX** [comment] 2019-12-21 09:52
**DO YOU NOW THAT THIS IS NO ISSUE THREAD OF MY FORK**

For Ubuntu

Uninstall both fork or original `sudo apt remove msa-daemon msa-ui-qt mcpelauncher-client mcpelauncher-ui-qt`

Reinstall (no uninstall needed) the mrarm launcher `sudo apt install --reinstall msa-daemon msa-ui-qt mcpelauncher-client mcpelauncher-ui-qt`

Install (uninstall needed) the mrarm launcher `sudo apt install msa-daemon msa-ui-qt mcpelauncher-client mcpelauncher-ui-qt`

**Comment by ChristopherHX** [comment] 2020-07-14 20:16
Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/185

**Closed by ChristopherHX** 2020-07-14 20:16 UTC
