### ISSUE TITLE
Exit Code: 6 (MACOS)

### ISSUE THREAD

**Issue by Newcoolboys** [minecraft-linux/mcpelauncher-manifest#357] opened 2020-07-14 00:49 UTC
**20:47:35 Info  [Launcher] Version: client c735370 / manifest eb0bc83
20:47:35 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
20:47:35 Info  [Launcher] CPU supports SSSE3: YES
20:47:35 Trace [Launcher] Loading hybris libraries
20:47:35 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
20:47:35 Trace [HybrisUtils] Loaded OS library libm.dylib
20:47:35 Error [HybrisUtils] Failed to load OS library libz.so.1
20:47:35 Trace [Launcher] Loading Minecraft library
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: load_library[1115]: Library '/Users/jasminepal/Library/Application Support/mcpelauncher/versions/1.14.60.5/libs/libminecraftpe.so' not found
Signal 6 received
Backtrace elements: 13
#0 0   mcpelauncher-client                 0x0018188e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ce1bae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7b9b80e abort + 133
#4 4   libc++abi.dylib                     0xa5a60177 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa5a6031f _ZL25default_terminate_handlerv + 232
#6 6   libc++abi.dylib                     0xa5a6b1fd _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa5a6afbc __cxa_get_exception_ptr + 0
#8 8   libc++abi.dylib                     0xa5a5ea01 __cxa_get_globals + 0
#9 9   mcpelauncher-client                 0x00182ddf _ZN14MinecraftUtils16loadMinecraftLibERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 1439
#10 10  mcpelauncher-client                 0x000c769a main + 9962
#11 11  libdyld.dylib                       0xa7af8051 start + 1
#12 12  ???                                 0x00000003 0x0 + 3
Dumping stack...
Process exited with unexpected exit code: 6**

**Comment by ChristopherHX** [comment] 2020-07-14 10:08
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`

**Closed by ChristopherHX** 2020-07-14 10:08 UTC
