### ISSUE TITLE
Game wont open (Mac os Mojave)

### ISSUE THREAD

**Issue by Aliababwa12** [minecraft-linux/mcpelauncher-manifest#358] opened 2020-07-14 08:50 UTC
12:44:56 Info  [Launcher] Version: client c735370 / manifest eb0bc83
12:44:56 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
12:44:56 Info  [Launcher] CPU supports SSSE3: YES
12:44:56 Trace [Launcher] Loading hybris libraries
12:44:56 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
12:44:56 Trace [HybrisUtils] Loaded OS library libm.dylib
12:44:56 Error [HybrisUtils] Failed to load OS library libz.so.1
12:44:56 Trace [Launcher] Loading Minecraft library
linkerlibc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Process exited with unexpected exit code: 9

Game wont open, this pops up

**Comment by ChristopherHX** [comment] 2020-07-14 10:09
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`

**Closed by ChristopherHX** 2020-07-14 10:09 UTC
