### ISSUE TITLE
start fail

### ISSUE THREAD

**Issue by mox1910** [minecraft-linux/mcpelauncher-manifest#243] opened 2020-03-13 03:44 UTC
11:42:37 Info  [Launcher] Version: client c735370 / manifest e405b8c
11:42:37 Info  [Launcher] CPU: AuthenticAMD AMD A8-6500 APU with Radeon(tm) HD Graphics    
11:42:37 Info  [Launcher] CPU supports SSSE3: YES
11:42:37 Trace [Launcher] Loading hybris libraries
11:42:37 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
11:42:37 Trace [HybrisUtils] Loaded OS library libm.so.6
11:42:37 Trace [HybrisUtils] Loaded OS library libz.so.1
11:42:37 Trace [Launcher] Loading Minecraft library
11:42:38 Info  [Launcher] Loaded Minecraft library
11:42:38 Debug [Launcher] Minecraft is at offset 0xe12e2000
11:42:38 Trace [Launcher] Initializing vtables
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
11:42:38 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
11:42:38 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82ccc85]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f7fb60]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f7fb49]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf760c9b6]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf75f53f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf795593e]
#6 /usr/lib32/libstdc++.so.6(+0x83847) [0xf7963847]
#7 /usr/lib32/libstdc++.so.6(+0x838d3) [0xf79638d3]
#8 /usr/lib32/libstdc++.so.6(+0x83c15) [0xf7963c15]
#9 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0xf1) [0x8315672]
#10 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x1f) [0x82ce023]
#11 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x31) [0x82cdf61]
#12 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client(main+0xf82) [0x8282f64]
#13 /usr/lib32/libc.so.6(__libc_start_main+0xf5) [0xf75f6ee5]
#14 /tmp/.mount_MinecrNWah97/usr/bin/./mcpelauncher-client() [0x8281b11]
Dumping stack...
#2 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#13 HYBRIS (null)+-517070848 in libminecraftpe.so+0x0000 [0xe12e2000]
#32 HYBRIS (null)+-508155089 in libminecraftpe.so+0x880b2f [0xe1b62b2f]
#33 HYBRIS (null)+-456002048 in libminecraftpe.so+0x3a3d600 [0xe4d1f600]
#34 HYBRIS (null)+-456005744 in libminecraftpe.so+0x3a3c790 [0xe4d1e790]
#38 HYBRIS (null)+-455998256 in libminecraftpe.so+0x3a3e4d0 [0xe4d204d0]
#39 HYBRIS (null)+-456001952 in libminecraftpe.so+0x3a3d660 [0xe4d1f660]
#104 HYBRIS (null)+-455923248 in libminecraftpe.so+0x3a509d0 [0xe4d329d0]
#108 HYBRIS (null)+-455912384 in libminecraftpe.so+0x3a53440 [0xe4d35440]
#109 HYBRIS (null)+-455912432 in libminecraftpe.so+0x3a53410 [0xe4d35410]
#113 HYBRIS (null)+-455900960 in libminecraftpe.so+0x3a560e0 [0xe4d380e0]
#114 HYBRIS (null)+-455901008 in libminecraftpe.so+0x3a560b0 [0xe4d380b0]
#118 HYBRIS (null)+-455878864 in libminecraftpe.so+0x3a5b730 [0xe4d3d730]
#119 HYBRIS (null)+-455889584 in libminecraftpe.so+0x3a58d50 [0xe4d3ad50]
#122 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#123 HYBRIS (null)+-455877856 in libminecraftpe.so+0x3a5bb20 [0xe4d3db20]
#124 HYBRIS (null)+-455878768 in libminecraftpe.so+0x3a5b790 [0xe4d3d790]
#128 HYBRIS (null)+-455877712 in libminecraftpe.so+0x3a5bbb0 [0xe4d3dbb0]
#129 HYBRIS (null)+-455877760 in libminecraftpe.so+0x3a5bb80 [0xe4d3db80]
#132 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0e85c [0xe1cf085c]
#133 HYBRIS (null)+-455858848 in libminecraftpe.so+0x3a60560 [0xe4d42560]
#134 HYBRIS (null)+-455866336 in libminecraftpe.so+0x3a5e820 [0xe4d40820]
#138 HYBRIS (null)+-455858704 in libminecraftpe.so+0x3a605f0 [0xe4d425f0]
#139 HYBRIS (null)+-455858752 in libminecraftpe.so+0x3a605c0 [0xe4d425c0]
#143 HYBRIS (null)+-455828304 in libminecraftpe.so+0x3a67cb0 [0xe4d49cb0]
#144 HYBRIS (null)+-455828352 in libminecraftpe.so+0x3a67c80 [0xe4d49c80]
#148 HYBRIS (null)+-455797904 in libminecraftpe.so+0x3a6f370 [0xe4d51370]
#149 HYBRIS (null)+-455797952 in libminecraftpe.so+0x3a6f340 [0xe4d51340]
#153 HYBRIS (null)+-455767504 in libminecraftpe.so+0x3a76a30 [0xe4d58a30]
#154 HYBRIS (null)+-455767552 in libminecraftpe.so+0x3a76a00 [0xe4d58a00]
#158 HYBRIS (null)+-455733456 in libminecraftpe.so+0x3a7ef30 [0xe4d60f30]
#159 HYBRIS (null)+-455737152 in libminecraftpe.so+0x3a7e0c0 [0xe4d600c0]
#162 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#163 HYBRIS (null)+-455732448 in libminecraftpe.so+0x3a7f320 [0xe4d61320]
#164 HYBRIS (null)+-455733360 in libminecraftpe.so+0x3a7ef90 [0xe4d60f90]
#168 HYBRIS (null)+-455728656 in libminecraftpe.so+0x3a801f0 [0xe4d621f0]
#169 HYBRIS (null)+-455732352 in libminecraftpe.so+0x3a7f380 [0xe4d61380]
#174 HYBRIS (null)+-455737341 in libminecraftpe.so+0x3a7e003 [0xe4d60003]
#176 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#184 HYBRIS (null)+-506626836 in libminecraftpe.so+0x9f5cec [0xe1cd7cec]
#187 HYBRIS (null)+-452021264 in libminecraftpe.so+0x3e093f0 [0xe50eb3f0]
#188 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#190 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#194 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5604676 [0xe68e6676]
#195 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#196 HYBRIS Core::Result::makeFailureWithStringLiteral(char const*)+114 in libminecraftpe.so+0x3e08a32 [0xe50eaa32]
#198 HYBRIS (null)+-394039880 in libminecraftpe.so+0x7554db8 [0xe8836db8]
#200 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#202 HYBRIS (null)+-452021264 in libminecraftpe.so+0x3e093f0 [0xe50eb3f0]
#203 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#205 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74f4bd8 [0xe87d6bd8]
#206 HYBRIS (null)+-394929920 in libminecraftpe.so+0x747b900 [0xe875d900]
#208 HYBRIS Core::StorageAreasTree::insertStorageArea(Core::FileStorageArea&)+316 in libminecraftpe.so+0x3df68ec [0xe50d88ec]
#213 HYBRIS (null)+-455689616 in libminecraftpe.so+0x3a89a70 [0xe4d6ba70]
#218 HYBRIS (null)+-455687680 in libminecraftpe.so+0x3a8a200 [0xe4d6c200]
#219 HYBRIS (null)+-455689520 in libminecraftpe.so+0x3a89ad0 [0xe4d6bad0]
#223 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#227 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#228 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#229 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#230 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#231 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#232 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#233 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#234 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#235 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#236 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#237 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#238 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#239 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#254 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#255 HYBRIS (null)+-394039868 in libminecraftpe.so+0x7554dc4 [0xe8836dc4]
#723 HYBRIS (null)+-517070848 in libminecraftpe.so+0x0000 [0xe12e2000]
#790 HYBRIS (null)+-402447443 in libminecraftpe.so+0x6d503ad [0xe80323ad]
Process exited with unexpected exit code: 6

**Comment by dbeschulte** [comment] 2020-03-20 23:38
Same issue and non-zero error code when opening up the launcher the first time

**Comment by capk1rk** [comment] 2020-03-22 06:34
Same exact issue on Ubuntu 18.04.4

**Comment by ChristopherHX** [comment] 2020-06-01 22:00
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:00 UTC
