### ISSUE TITLE
Minecraft 1.13.034 crash

### ISSUE THREAD

**Issue by bobby4343** [minecraft-linux/mcpelauncher-manifest#182] opened 2019-11-09 20:29 UTC
10:28:46 Info  [Launcher] Version: client c735370 / manifest eb0bc83
10:28:46 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
10:28:46 Info  [Launcher] CPU supports SSSE3: YES
10:28:46 Trace [Launcher] Loading hybris libraries
10:28:46 Trace [HybrisUtils] Loaded OS library /private/var/folders/th/f1jmvx6s1dq080m5rn0gdm240000gn/T/AppTranslocation/BA3AD031-C822-4211-A0E0-7BB9AC8B7CA7/d/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
10:28:46 Trace [HybrisUtils] Loaded OS library libm.dylib
10:28:46 Error [HybrisUtils] Failed to load OS library libz.so.1
10:28:46 Trace [Launcher] Loading Minecraft library
10:28:46 Info  [Launcher] Loaded Minecraft library
10:28:46 Debug [Launcher] Minecraft is at offset 0x3084000
10:28:46 Trace [Launcher] Initializing vtables
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
10:28:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
10:28:46 Trace [AppPlatform] Vtable size = 288
10:28:46 Trace [Store] Vtable size = 40
10:28:46 Info  [Launcher] Game version: 1.13.0
10:28:46 Info  [Launcher] Applying patches
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 131
10:28:46 Trace [Patch] Patching - result: 233 251 9 103 252
10:28:46 Trace [Patch] Patching - original: 83 87 86 131 236
10:28:46 Trace [Patch] Patching - result: 233 11 167 108 252
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 43 27 191 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 59 57 253 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 203 82 253 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 107 63 253 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 139 166 252 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 155 154 252 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 59 215 254 248
10:28:46 Trace [Patch] Patching - original: 83 87 86 131 236
10:28:46 Trace [Patch] Patching - result: 233 219 56 253 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 129
10:28:46 Trace [Patch] Patching - result: 233 155 99 253 248
10:28:46 Trace [Patch] Patching - original: 83 131 236 8 232
10:28:46 Trace [Patch] Patching - result: 233 171 130 30 249
10:28:46 Trace [Patch] Patching - original: 137 76 36 4 137
10:28:46 Trace [Patch] Patching - result: 232 113 211 211 248
10:28:46 Trace [Patch] Patching - original: 36 88 139 65 12
10:28:46 Trace [Patch] Patching - result: 232 124 211 211 248
10:28:46 Trace [Patch] Patching - original: 85 83 87 86 131
10:28:46 Trace [Patch] Patching - result: 233 91 198 185 248
10:28:46 Error [SplitscreenPatch] Not patching splitscreen - incompatible code
Signal 11 received
Backtrace elements: 7
#0 0   mcpelauncher-client                 0x000fc88e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7ca4bbe _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   mcpelauncher-client                 0x000c25b6 _ZN11GLCorePatch7installEPv + 662
#4 4   mcpelauncher-client                 0x00042a95 main + 10981
#5 5   libdyld.dylib                       0xa7abb051 start + 1
#6 6   ???                                 0x00000009 0x0 + 9
Dumping stack...
#78 HYBRIS (null)+140011305 in libminecraftpe.so+0x5502729 [0x8586729]
#128 HYBRIS (null)+60764752 in libminecraftpe.so+0x96f250 [0x39f3250]
#129 HYBRIS (null)+60764816 in libminecraftpe.so+0x96f290 [0x39f3290]
#130 HYBRIS (null)+60764832 in libminecraftpe.so+0x96f2a0 [0x39f32a0]
#131 HYBRIS (null)+60764848 in libminecraftpe.so+0x96f2b0 [0x39f32b0]
#277 HYBRIS mce::ShaderGroupBase::loadShader(std::string const&, Core::Path const&, Core::Path const&, Core::Path const&)+0 in libminecraftpe.so+0x3afbde0 [0x6b7fde0]
#386 HYBRIS (null)+50872320 in libminecraftpe.so+0x0000 [0x3084000]
#387 HYBRIS (null)+50872320 in libminecraftpe.so+0x0000 [0x3084000]
Process exited with unexpected exit code: 6

Does anyone know when it'll be fixed?

**Comment by ChristopherHX** [comment] 2019-11-09 22:56
@bobby4343 Your Issue is a duplicate off #171 
You will find there a temporary Solution until it is merged

**Comment by bobby4343** [comment] 2019-11-10 19:40
So I can log in, and get into the menu, however everything is super zoomed in, and my cursor is off, meaning if I hover over the options I can’t click but if I move to the left I’ll be able to click the menu options. I tried adjusting the settings of the launcher but it doesn’t help. I even tried the tedious act of going into the Minecraft settings but can’t seem to find the settings to fit the screen. Any idea on how to fix that?

**Comment by ChristopherHX** [comment] 2019-11-10 23:25
@bobby4343 Hmm If you see only the lower left 1/4 of the screen then use a other dmg under
`MacOs DMG 10.10 / 10.12 - 10.14 (Minecraft Displays only the lower left quater of the Game) Then Try this`, ~~but why nobody understand that heading of special dmg with this problem~~
[Direct link](https://github.com/ChristopherHX/mcpelauncher-manifest/releases/download/MacOs1.3/Minecraft.Bedrock.Launcher.sizebug1.dmg)

**Comment by Mhowser** [comment] 2019-11-16 00:20
Thank you for the crash report, We are consolidating all issues related to 1.13+ crashes to #165

**Closed by Mhowser** 2019-11-16 00:20 UTC
Labels: crash, duplicate
