### ISSUE TITLE
Crostini help

### ISSUE THREAD

**Issue by benne3** [minecraft-linux/mcpelauncher-manifest#239] opened 2020-03-04 23:57 UTC
So I've basically been through hell and back with this tedious installation setup. I'v spent more than a couple of days just trying to run this stupid thing, so if someone could please just help me so I can get on my way to playing. Thanks👍

**Comment by Mhowser** [comment] 2020-03-05 03:28
Try using Chris's appimage.

**Comment by ChristopherHX** [comment] 2020-06-03 21:02
duplicate of #150

**Closed by ChristopherHX** 2020-06-03 21:02 UTC
