### ISSUE TITLE
not working macOS sequoia mincraft crashes when loading world

### ISSUE THREAD

**Issue by KeyFlyz** [minecraft-linux/mcpelauncher-manifest#1059] opened 2024-11-03 09:18 UTC
02:12:55 Info  [Launcher] Version: client 4c5f4fd / manifest 4101034
02:12:55 Info  [Launcher] OS: macOS, Arch: x86_64
02:12:55 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
02:12:55 Info  [Launcher] CPU supports SSSE3: YES
02:12:55 Info  [Launcher] Reading Launcher Settings File: /Users/keyflysmacbook/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
02:12:55 Info  [Launcher] Applied Launcher Settings
02:12:55 Trace [Launcher] Loading android libraries
02:12:55 Trace [Launcher] linker loaded
02:12:55 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
02:12:55 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/4229/cmdline to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
02:12:55 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
02:12:55 Trace [REDIRECT] /data/data to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/
02:12:55 Trace [REDIRECT] . to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/assets/
02:12:55 Trace [REDIRECT] /proc to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/proc/
02:12:55 Trace [REDIRECT] /sys to /Users/keyflysmacbook/Library/Application Support/mcpelauncher/sys/
02:12:55 Trace [LinkerUtils] Loaded OS library libm.dylib
02:12:55 Trace [LinkerUtils] Loaded OS library libz.dylib
02:12:55 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
02:12:55 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libc++_shared.so 0x10eb40000
02:12:57 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so"...
02:12:57 Info  [Launcher] Loading gamepad mappings
02:12:57 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
02:12:57 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libc++_shared.so 0x1109c0000
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so 0x114400000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x108caf5f0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x108caf5d0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x108caf610
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x108e5a350
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x108e5a710
02:12:58 Info  [Launcher] Loaded Minecraft library
02:12:58 Debug [Launcher] Minecraft is at offset 0x114400000
02:12:58 Info  [Launcher] Game version: 0.0.0.0
02:12:58 Info  [Launcher] Applying patches
02:12:58 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
02:12:58 Info  [Launcher] Initializing JNI
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
02:12:58 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
02:12:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
02:12:58 Trace [Minecraft] Entering JNI_OnLoad 0x700008e8c000
02:12:58 Trace [Minecraft] JNI_OnLoad completed
02:12:58 Trace [JniSupport] Invoking nativeRegisterThis
02:12:58 Trace [JniSupport] Invoking ANativeActivity_onCreate
02:12:58 Info  [Launcher] Executing main thread
02:12:58 Warn  [Main] Android stub called
02:12:58 Warn  [Main] Android stub called
02:12:58 Warn  [Main] Android stub called
02:12:58 Warn  [Main] Android stub called
02:12:58 Trace [WindowCallbacks] Gamepad connected #0
02:12:58 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
02:12:58 Trace [JniSupport] Invoking start activity callbacks
02:12:58 Error [MCPE] *** setCachedDeviceId(254624cb-50b8-422e-824f-9ecb8cb93a6f)
02:12:58 Info  [Bedrock] Breakpad config: directory is: /crash, sessionid is: cf5634ae-edc2-4703-8aed-72134703ba51
02:12:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/keyflysmacbook/Library/Application Support/mcpelauncher/'
02:12:58 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
02:12:58 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
2024-11-03 02:12:58.892 mcpelauncher-client[4229:46549] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-03 02:12:58.892 mcpelauncher-client[4229:46549] +[IMKInputSession subclass]: chose IMKInputSession_Modern
02:12:58 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
02:12:58 Warn  [FakeEGL] eglQueryString 308d
02:12:58 Warn  [Main] Android stub called
02:12:58 Info  [GL] Vendor: Google Inc.
02:12:58 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
02:12:58 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
02:12:58 Info  [GL] Vendor: Google Inc.
02:12:58 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
02:12:58 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
02:12:58 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libMediaDecoders_Android.so 0x129900000

02:12:59 Info  [GL] Vendor: Google Inc.
02:12:59 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
02:12:59 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
02:12:59 Warn  [Main] Android stub called
02:13:01 Info  [GL] Vendor: Google Inc.
02:13:01 Info  [GL] Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 5500M OpenGL Engine, OpenGL 4.1 core)
02:13:01 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
02:13:01 Warn  [Main] Android stub called
02:13:01 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
02:13:01 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
02:13:01 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
02:13:04 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/Users/keyflysmacbook/Library/Application Support/mcpelauncher/'
02:13:04 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/keyflysmacbook/Library/Application Support/mcpelauncher/'
02:13:05 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
02:13:22 Info  [Minecraft] NO LOG FILE! - Opening level '/Users/keyflysmacbook/Library/Application Support/mcpelauncher/games/com.mojang/minecraftWorlds/VtOoZkaTAAA=/db'
02:13:22 Info  [Minecraft] NO LOG FILE! - [SERVER] Pack Stack - None
02:13:23 Info  [Minecraft] NO LOG FILE! - Player connected: Midnight6025, xuid: 
02:13:23 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
02:13:23 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
02:13:23 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
02:13:23 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unknown socket family when converting sockaddr to host
Signal 6 received
Backtrace elements: 16
#0 0   mcpelauncher-client                 0x0000000108dfb708 _ZN12CrashHandler12handleSignalEiPv + 344
#1 1   mcpelauncher-client                 0x0000000108dfbb35 _ZN12CrashHandler15handle_fs_faultEiPvS0_ + 133
#2 2   libsystem_platform.dylib            0x00007ff817de3e9d _sigtramp + 29
#3 3   ???                                 0x0000000000000400 0x0 + 1024
#4 4   libsystem_c.dylib                   0x00007ff817ccfb19 abort + 126
#5 5   libc++abi.1.dylib                   0x000000010a743003 abort_message + 195
#6 6   libc++abi.1.dylib                   0x000000010a72414e _ZL28demangling_terminate_handlerv + 238
#7 7   libc++abi.1.dylib                   0x000000010a741fc8 _ZSt11__terminatePFvvE + 8
#8 8   libc++abi.1.dylib                   0x000000010a7451eb _ZN10__cxxabiv1L12failed_throwEPNS_15__cxa_exceptionE + 27
#9 9   libc++abi.1.dylib                   0x000000010a745165 __cxa_throw + 117
#10 10  mcpelauncher-client                 0x0000000108e59603 _ZN4shim6bionic12get_host_lenEPKNS0_8sockaddrE + 163
#11 11  mcpelauncher-client                 0x0000000108e5c87d _ZN4shim6detail11sockaddr_inC2EPKNS_6bionic8sockaddrEj + 141
#12 12  mcpelauncher-client                 0x0000000108e5a983 _ZN4shim6detail11sockaddr_inC1EPKNS_6bionic8sockaddrEj + 35
#13 13  mcpelauncher-client                 0x0000000108e5ae01 _ZN4shim6sendtoEiPKvmiPKNS_6bionic8sockaddrEj + 97
#14 14  mcpelauncher-client                 0x0000000108e5c240 _ZN4shim6detail19errno_update_helperIFliPKvmiPKNS_6bionic8sockaddrEjEE7wrapperIXadL_ZNS_6sendtoEiS3_miS7_jEEEEliS3_miS7_j + 80
#15 15  ???                                 0x0000000122440a2a 0x0 + 4869851690
Dumping stack...
#435 LINKER vtable for rtc::SocketDispatcher+0x68 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xf9b77f0 [0x123db77f0]
#436 LINKER rtc::PhysicalSocket::SendTo(void const*, unsigned long, rtc::SocketAddress const&)+0x5a in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xe040a2a [0x122440a2a]
#460 LINKER NetherNet::OpenSSLAesAdapter::SendTo(void const*, unsigned long, rtc::SocketAddress const&)+0x55 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xdd75b55 [0x122175b55]
#468 LINKER rtc::AsyncUDPSocket::SendTo(void const*, unsigned long, rtc::SocketAddress const&, rtc::PacketOptions const&)+0x76 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xe021056 [0x122421056]
#481 LINKER (null)+0x123ff8e08 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xfbf8e08 [0x123ff8e08]
#482 LINKER (null)+0x123ff8c78 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xfbf8c78 [0x123ff8c78]
#484 LINKER NetherNet::LanThreadManager::SendToHelper(std::__ndk1::unique_ptr<rtc::AsyncPacketSocket, std::__ndk1::default_delete<rtc::AsyncPacketSocket> >&, void const*, unsigned long, rtc::SocketAddress const&)+0x1c6 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xdd72976 [0x122172976]
#517 LINKER (null)+0x123ff8c78 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xfbf8c78 [0x123ff8c78]
#520 LINKER (null)+0x123ff8e08 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xfbf8e08 [0x123ff8e08]
#522 LINKER NetherNet::LanThreadManager::SendLanBroadcastResponse(rtc::SocketAddress const&, NetherNet::DiscoveryResponsePacket const&)+0x57 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xdd73897 [0x122173897]
#530 LINKER rtc::SimpleStringBuilder::AppendFormat(char const*, ...)+0xb6 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xe055eb6 [0x122455eb6]
#534 LINKER (null)+0x123da363a in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xf9a363a [0x123da363a]
#546 LINKER rtc::SocketAddress::HostAsURIString() const+0xd6 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xe0492a6 [0x1224492a6]
#552 LINKER (null)+0x119ac679a in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x56c679a [0x119ac679a]
#558 LINKER rtc::SocketAddress::ToString() const+0xa7 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xe049577 [0x122449577]
#688 LINKER std::__ndk1::mutex::unlock()+0x6 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libc++_shared.so+0xcd066 [0x110a8d066]
#690 LINKER (null)+0x11e359927 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x9f59927 [0x11e359927]
#698 LINKER NetherNet::SimpleNetworkInterfaceImpl::OnSignalingEvent(NetherNet::SignalingEvents::DiscoveryRequest const&)+0xda in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xdd7ad4a [0x12217ad4a]
#859 LINKER (null)+0x116893030 in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x2493030 [0x116893030]
#875 LINKER (null)+0x11689dd4d in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x249dd4d [0x11689dd4d]
#883 LINKER (null)+0x11689dd4b in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x249dd4b [0x11689dd4b]
#915 LINKER (null)+0x11689dd4d in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0x249dd4d [0x11689dd4d]
#996 LINKER (null)+0x12218d0de in /Users/keyflysmacbook/Library/Application Support/mcpelauncher/versions/1.21.44.01/lib/x86_64/libminecraftpe.so+0xdd8d0de [0x12218d0de]
program failed with unix signal number: 6

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2024-11-03 10:20
Duplicate of #1055

Not enough information available, this release doesn't log important information.

It's important for me to get a log of the **(not crashing, e.g. broken multiplayer)** [debug build (Click to find the link)](https://github.com/minecraft-linux/mcpelauncher-manifest/issues/1055#issuecomment-2449076032) including lines like "Unknown socket family when converting" without aborting.

**Closed as not planned** 2024-11-03 12:27 UTC
Labels: bug
