### ISSUE TITLE
prime-run =crash

### ISSUE THREAD

**Issue by KingTheGuy** [minecraft-linux/mcpelauncher-manifest#233] opened 2020-02-09 21:17 UTC
15:55:36 Info  [Launcher] Version: client 10b2d53 / manifest 132cbf3
15:55:36 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
15:55:36 Info  [Launcher] CPU supports SSSE3: YES
15:55:36 Trace [Launcher] Loading hybris libraries
15:55:36 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
15:55:36 Trace [HybrisUtils] Loaded OS library libm.so.6
15:55:36 Trace [HybrisUtils] Loaded OS library libz.so.1
15:55:36 Info  [Launcher] Creating window
15:55:36 Trace [Launcher] Loading gamepad mappings: /usr/share//mcpelauncher/gamecontrollerdb.txt
15:55:36 Trace [Launcher] Loading gamepad mappings: /usr/share/mcpelauncher/gamecontrollerdb.txt
EGLUT: failed to create surface
Process exited with unexpected exit code: 1

**Comment by ChristopherHX** [comment] 2020-06-07 17:29
duplicate of #223

**Closed by ChristopherHX** 2020-06-07 17:29 UTC
