### ISSUE TITLE
Crash on start Manjaro KDE 18.0.4

### ISSUE THREAD

**Issue by EvanescentKnight** [minecraft-linux/mcpelauncher-manifest#114] opened 2019-07-04 13:38 UTC
08:33:50 Info  [Launcher] Version: client 9d41f29 / manifest a7e2144
08:33:50 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
08:33:50 Info  [Launcher] CPU supports SSSE3: YES
08:33:50 Trace [Launcher] Loading hybris libraries
08:33:50 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
08:33:50 Trace [HybrisUtils] Loaded OS library libm.so.6
08:33:50 Trace [HybrisUtils] Loaded OS library libz.so.1
08:33:50 Trace [Launcher] Loading Minecraft library
08:33:51 Info  [Launcher] Loaded Minecraft library
08:33:51 Debug [Launcher] Minecraft is at offset 0xee881000
08:33:51 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
08:33:51 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
Signal 11 received
Backtrace elements: 6
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xcc) [0x56688d9c]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f24e00]
#2 /usr/bin/mcpelauncher-client(_Z22minecraft_symbols_initPv+0x19aa) [0x566b522a]
#3 /usr/bin/mcpelauncher-client(main+0xc44) [0x566571e4]
#4 /usr/lib32/libc.so.6(__libc_start_main+0xf1) [0xf779f7d1]
#5 /usr/bin/mcpelauncher-client(_start+0x31) [0x56658881]
Dumping stack...
#16 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+859 in libminecraftpe.so+0x1925b9b [0xf01a6b9b]
#74 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#75 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#82 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#84 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#100 HYBRIS Core::FileSystem::cleanPathSeparators_deprecated(Core::PathBuffer<Core::StackString<char, 1024u> >&, Core::Path)+12 in libminecraftpe.so+0x3966c2c [0xf21e7c2c]
#111 HYBRIS (null)+-181734399 in libminecraftpe.so+0x6a2e401 [0xf52af401]
#112 HYBRIS Core::FileSystem::cleanPath_deprecated(Core::PathBuffer<Core::StackString<char, 1024u> >&, Core::Path)+958 in libminecraftpe.so+0x3961d3e [0xf21e2d3e]
#154 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x51cb8b6 [0xf3a4c8b6]
#168 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#171 HYBRIS (null)+-206964757 in libminecraftpe.so+0x521e7eb [0xf3a9f7eb]
#172 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#173 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#174 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#177 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#184 HYBRIS std::pair<std::__detail::_Node_iterator<std::pair<unsigned char const, std::string>, false, false>, bool> std::_Hashtable<unsigned char, std::pair<unsigned char const, std::string>, std::allocator<std::pair<unsigned char const, std::string> >, std::__detail::_Select1st, std::equal_to<unsigned char>, std::hash<unsigned char>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_insert<std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > >(std::pair<unsigned char const, std::string> const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<unsigned char const, std::string>, false> > > const&, std::integral_constant<bool, true>)+12 in libminecraftpe.so+0x39e1c9c [0xf2262c9c]
#186 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#187 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#189 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#190 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#191 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#194 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#196 HYBRIS (null)+-269737128 in libminecraftpe.so+0x1641358 [0xefec2358]
#197 HYBRIS std::unordered_map<unsigned char, std::string, std::hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, std::string> > >::~unordered_map()+0 in libminecraftpe.so+0x39df4c0 [0xf22604c0]
#198 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#199 HYBRIS (null)+-181280768 in libminecraftpe.so+0x6a9d000 [0xf531e000]
#202 HYBRIS (null)+-179072136 in libminecraftpe.so+0x6cb8378 [0xf5539378]
#203 HYBRIS (null)+-179179880 in libminecraftpe.so+0x6c9de98 [0xf551ee98]
#243 HYBRIS (null)+-206964757 in libminecraftpe.so+0x521e7eb [0xf3a9f7eb]
#244 HYBRIS (null)+-181734228 in libminecraftpe.so+0x6a2e4ac [0xf52af4ac]
#247 HYBRIS xbox::services::serviceLocales+0 in libminecraftpe.so+0x6c9f07c [0xf552007c]
#248 HYBRIS std::_Hashtable<std::string, std::pair<std::string const, std::string>, std::allocator<std::pair<std::string const, std::string> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned int, unsigned int, std::__detail::_Hash_node<std::pair<std::string const, std::string>, true>*)+71 in libminecraftpe.so+0x1675ab7 [0xefef6ab7]
#250 HYBRIS xbox::services::serviceLocales+16 in libminecraftpe.so+0x6c9f08c [0xf552008c]
#260 HYBRIS xbox::services::serviceLocales+8 in libminecraftpe.so+0x6c9f084 [0xf5520084]
#570 HYBRIS vtable for GameStore+0 in libminecraftpe.so+0x6926e04 [0xf51a7e04]
#571 HYBRIS vtable for App+0 in libminecraftpe.so+0x693b19c [0xf51bc19c]
#599 HYBRIS (null)+-293072896 in libminecraftpe.so+0x0000 [0xee881000]
#739 HYBRIS (null)+-273119239 in libminecraftpe.so+0x13077f9 [0xefb887f9]
Process exited with unexpected exit code: 6

**Comment by spicecode** [comment] 2019-07-05 16:30
I'm using manjaro cinnamon, and the same thing is hapening

**Comment by glemsom** [comment] 2019-07-06 13:40
I'm on Manjaro Gnome - and is seeing the same issue

**Comment by reitraced** [comment] 2019-07-09 22:17
Manjaro i3 here, same issue

**Comment by MCMrARM** [comment] 2019-08-03 16:35
Duplicate of #104

**Closed by MCMrARM** 2019-08-03 16:35 UTC
