### ISSUE TITLE
error in version 1.14.20.1 in the old ones works

### ISSUE THREAD

**Issue by edergames29** [minecraft-linux/mcpelauncher-manifest#227] opened 2020-01-28 21:10 UTC
i using xubuntu 32x linux
18:08:42 Info  [Launcher] Version: client c735370 / manifest b3dd620
18:08:42 Info  [Launcher] CPU: GenuineIntel           Intel(R) Celeron(R) CPU 847 @ 1.10GHz
18:08:42 Info  [Launcher] CPU supports SSSE3: YES
18:08:42 Trace [Launcher] Loading hybris libraries
18:08:42 Trace [HybrisUtils] Loaded OS library /usr/local/share/mcpelauncher/libs/native/libfmod.so.9.16
18:08:42 Trace [HybrisUtils] Loaded OS library libm.so.6
18:08:42 Trace [HybrisUtils] Loaded OS library libz.so.1
18:08:42 Trace [Launcher] Loading Minecraft library
18:08:46 Info  [Launcher] Loaded Minecraft library
18:08:46 Debug [Launcher] Minecraft is at offset 0xad6e5000
18:08:46 Trace [Launcher] Initializing vtables
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
18:08:46 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
18:08:46 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/local/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x646729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xb7ef3ab0]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xb7ef3aa5]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xb77d1832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xb77d2cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xb7b2f97d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xb7b370f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xb7b3715d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xb7b3745c]
#9 /usr/local/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x69baa1]
#10 /usr/local/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x647f22]
#11 /usr/local/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x647e1a]
#12 /usr/local/bin/mcpelauncher-client(main+0x10c2) [0x5e279e]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xb77bce81]
#14 /usr/local/bin/mcpelauncher-client(+0x1dc0f1) [0x5e10f1]
Dumping stack...
#4 HYBRIS (null)+-1324179776 in libminecraftpe.so+0x3a44ec0 [0xb1129ec0]
#13 HYBRIS (null)+-1385279488 in libminecraftpe.so+0x0000 [0xad6e5000]
#32 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0e85c [0xae0f385c]
#33 HYBRIS (null)+-1324148016 in libminecraftpe.so+0x3a4cad0 [0xb1131ad0]
#34 HYBRIS (null)+-1324148064 in libminecraftpe.so+0x3a4caa0 [0xb1131aa0]
#38 HYBRIS (null)+-1324132944 in libminecraftpe.so+0x3a505b0 [0xb11355b0]
#39 HYBRIS (null)+-1324136640 in libminecraftpe.so+0x3a4f740 [0xb1134740]
#78 HYBRIS (null)+-1324068304 in libminecraftpe.so+0x3a60230 [0xb1145230]
#79 HYBRIS (null)+-1324068352 in libminecraftpe.so+0x3a60200 [0xb1145200]
#108 HYBRIS (null)+-1323938256 in libminecraftpe.so+0x3a7fe30 [0xb1164e30]
#112 HYBRIS std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_lookahead(std::__detail::_State<std::regex_traits<char> >)+531 in libminecraftpe.so+0xa0e803 [0xae0f3803]
#113 HYBRIS (null)+-1323927392 in libminecraftpe.so+0x3a828a0 [0xb11678a0]
#114 HYBRIS (null)+-1323938160 in libminecraftpe.so+0x3a7fe90 [0xb1164e90]
#124 HYBRIS (null)+-1374835476 in libminecraftpe.so+0x9f5cec [0xae0dacec]
#128 HYBRIS (null)+-1262248508 in libminecraftpe.so+0x7554dc4 [0xb4c39dc4]
#130 HYBRIS (null)+-1263138560 in libminecraftpe.so+0x747b900 [0xb4b60900]
#134 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x56042b6 [0xb2ce92b6]
#135 HYBRIS (null)+-1263138560 in libminecraftpe.so+0x747b900 [0xb4b60900]
#138 HYBRIS (null)+-1262248520 in libminecraftpe.so+0x7554db8 [0xb4c39db8]
#140 HYBRIS (null)+-1262248508 in libminecraftpe.so+0x7554dc4 [0xb4c39dc4]
#142 HYBRIS (null)+-1320230864 in libminecraftpe.so+0x3e09030 [0xb14ee030]
#143 HYBRIS (null)+-1262248508 in libminecraftpe.so+0x7554dc4 [0xb4c39dc4]
#145 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74f4bd8 [0xb4bd9bd8]
#153 HYBRIS (null)+-1323899216 in libminecraftpe.so+0x3a896b0 [0xb116e6b0]
#667 HYBRIS (null)+-1385279488 in libminecraftpe.so+0x0000 [0xad6e5000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-02-11 13:21
Look here for workaround
https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903

**Comment by ChristopherHX** [comment] 2020-06-01 21:57
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:57 UTC
