### ISSUE TITLE
Minecraft 1.13 won't run

### ISSUE THREAD

**Issue by raphtlw** [minecraft-linux/mcpelauncher-manifest#229] opened 2020-02-01 08:39 UTC
OS: Ubuntu 18.04
Minecraft - Purchased from the play store

Logs:
```
16:36:27 Info  [Launcher] Version: client c735370 / manifest e405b8c
16:36:27 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
16:36:27 Info  [Launcher] CPU supports SSSE3: YES
16:36:27 Trace [Launcher] Loading hybris libraries
16:36:27 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
16:36:27 Trace [HybrisUtils] Loaded OS library libm.so.6
16:36:27 Trace [HybrisUtils] Loaded OS library libz.so.1
16:36:27 Trace [Launcher] Loading Minecraft library
16:36:30 Info  [Launcher] Loaded Minecraft library
16:36:30 Debug [Launcher] Minecraft is at offset 0xed8c4000
16:36:30 Trace [Launcher] Initializing vtables
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:36:30 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:36:30 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567fde41]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f88b70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f88b59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7867832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7868cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7bc597d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760f4) [0xf7bcd0f4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7615d) [0xf7bcd15d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7645c) [0xf7bcd45c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x568525b1]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567ff63a]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567ff532]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567a65de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7852e81]
#14 /usr/bin/mcpelauncher-client(+0x1c8f31) [0x567a4f31]
Dumping stack...
#2 HYBRIS (null)+-249874976 in libminecraftpe.so+0x38ef5e0 [0xf11b35e0]
#13 HYBRIS (null)+-309575680 in libminecraftpe.so+0x0000 [0xed8c4000]
#32 HYBRIS (null)+-249835120 in libminecraftpe.so+0x38f9190 [0xf11bd190]
#33 HYBRIS (null)+-249835168 in libminecraftpe.so+0x38f9160 [0xf11bd160]
#36 HYBRIS (null)+-189396416 in libminecraftpe.so+0x729ca40 [0xf4b60a40]
#37 HYBRIS (null)+-249816880 in libminecraftpe.so+0x38fd8d0 [0xf11c18d0]
#38 HYBRIS (null)+-249820576 in libminecraftpe.so+0x38fca60 [0xf11c0a60]
#77 HYBRIS (null)+-249762912 in libminecraftpe.so+0x390aba0 [0xf11ceba0]
#78 HYBRIS (null)+-249766608 in libminecraftpe.so+0x3909d30 [0xf11cdd30]
#108 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#111 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#112 HYBRIS (null)+-249727231 in libminecraftpe.so+0x3913701 [0xf11d7701]
#113 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#114 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#116 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#117 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#119 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#120 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#122 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#123 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#125 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#126 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#128 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#129 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#131 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#132 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#134 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#135 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#137 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#138 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#140 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#141 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#143 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#144 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#146 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#147 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#149 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#150 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#152 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#153 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#155 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#156 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#158 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#159 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#161 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#162 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#164 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#165 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#167 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#168 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#170 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#171 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#173 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#174 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#176 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#177 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#179 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#180 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#182 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#183 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#185 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#186 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#188 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#189 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#191 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#192 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#194 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#195 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#197 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#198 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#200 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#201 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#203 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#204 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#206 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#207 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#209 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#213 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#215 HYBRIS (null)+-220259844 in libminecraftpe.so+0x552d9fc [0xf2df19fc]
#216 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#219 HYBRIS (null)+-220260095 in libminecraftpe.so+0x552d901 [0xf2df1901]
#731 HYBRIS (null)+-309575680 in libminecraftpe.so+0x0000 [0xed8c4000]
#986 HYBRIS (null)+-301326037 in libminecraftpe.so+0x7de12b [0xee0a212b]
Process exited with unexpected exit code: 6
```
I tried christopher's fork too but that didn't work and kept saying core dumped whenever I tried to run the launcher.

**Comment by joshturge** [comment] 2020-02-02 06:57
I'm not sure what you did but Chris's fork worked for me

**Comment by raphtlw** [comment] 2020-02-03 09:08
@joshturge How did you install it? Do you need to have the original mcpelauncher installed too? Or just the fork installed?

**Comment by joshturge** [comment] 2020-02-04 11:41
@raphtlw I uninstalled the original mcpelauncher and installed the fork

**Comment by raphtlw** [comment] 2020-02-04 12:26
@joshturge How did you install the fork? Via pre-packaged binaries or the terminal git clone method?

**Comment by joshturge** [comment] 2020-02-06 03:36
@raphtlw I used the git clone method

**Comment by ChristopherHX** [comment] 2020-06-01 21:58
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:58 UTC
