### ISSUE TITLE
error code: 11

### ISSUE THREAD

**Issue by the-portalboy** [minecraft-linux/mcpelauncher-manifest#305] opened 2020-05-20 18:12 UTC
21:10:49 Info  [Launcher] Version: client c735370 / manifest e405b8c
21:10:49 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx  
21:10:49 Info  [Launcher] CPU supports SSSE3: YES
21:10:49 Trace [Launcher] Loading hybris libraries
21:10:49 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
21:10:49 Trace [HybrisUtils] Loaded OS library libm.so.6
21:10:49 Trace [HybrisUtils] Loaded OS library libz.so.1
21:10:49 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 11

**Comment by korsynik** [comment] 2020-05-21 17:13
I have the same mistake

`
19:09:59 Info  [Launcher] Version: client c735370 / manifest e405b8c
19:09:59 Info  [Launcher] CPU: GenuineIntel Intel(R) Celeron(R) CPU N3350 @ 1.10GHz
19:09:59 Info  [Launcher] CPU supports SSSE3: YES
19:09:59 Trace [Launcher] Loading hybris libraries
19:09:59 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
19:09:59 Trace [HybrisUtils] Loaded OS library libm.so.6
19:09:59 Trace [HybrisUtils] Loaded OS library libz.so.1
19:09:59 Trace [Launcher] Loading Minecraft library
linkerlinkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Process exited with unexpected exit code: 11
`

**Comment by ChristopherHX** [comment] 2020-06-01 21:24
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:24 UTC
Labels: bug, crash, legacy (unsupported)
