### ISSUE TITLE
libminecraftpe, libgnustl_shared not found: Signal 11

### ISSUE THREAD

**Issue by TudbuT** [minecraft-linux/mcpelauncher-manifest#315] opened 2020-05-24 15:45 UTC
On Ubuntu 18.04

```
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Process exited with unexpected exit code: 11
```

**Comment by arcana261** [comment] 2020-05-25 08:59
@TudbuT 

Apparently, the library is in the APK file. However, simply extracting the library from the APK file won't do. There has been people having success with recompiling the launcher using `clang` though, But I couldn't make it work. You can read more about here in this issue: #271

**Comment by ChristopherHX** [comment] 2020-06-01 21:17
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:17 UTC
