### ISSUE TITLE
/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SkycladObserver0** [minecraft-linux/mcpelauncher-manifest#262] opened 2020-04-02 03:46 UTC
Title basically says it all. Full error says
`/usr/bin/mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
Process exited with unexpected exit code: 127`
Trying to run Minecraft 1.14.1.5

**Comment by Mhowser** [comment] 2020-04-02 08:51
Install 32bit graphics drivers as per the instructions found in the wiki.

**Comment by AtomynosAtom** [comment] 2020-04-02 10:52
Just use the forked one by ChristopherHX.

**Comment by ChristopherHX** [comment] 2020-06-03 21:23
duplicate of #94

**Closed by ChristopherHX** 2020-06-03 21:23 UTC
