### ISSUE TITLE
1.13 (skin update) crashes at launcher

### ISSUE THREAD

**Issue by Craftstar15** [minecraft-linux/mcpelauncher-manifest#194] opened 2019-11-18 19:10 UTC
1.13 (skin update) crashes at the launcher and i have tried all I know. Anyone else have this problem?
does anyone have solutions? I just wanna play with my friend!

**Comment by Mhowser** [comment] 2019-11-20 15:45
What version specifically? And can you add your crash log to #165 please (use pastebin.com)

**Comment by ChristopherHX** [comment] 2020-07-14 10:36
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`

**Closed by ChristopherHX** 2020-07-14 10:36 UTC
Labels: crash, duplicate
