### ISSUE TITLE
Error when opening 1.14.1.3

### ISSUE THREAD

**Issue by Xico26** [minecraft-linux/mcpelauncher-manifest#205] opened 2019-12-15 10:25 UTC
Hi again.
I'm trying to play 1.14.1.3 but I get this error:
/usr/bin/mcpelauncher-client: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/bin/mcpelauncher-client)
Process exited with unexpected exit code: 1
Can anyone help me?
Thanks :D

**Comment by pcs3rd** [comment] 2019-12-17 15:43
@Xico26 Minecraft has removed debugging symbols from Minecraft bedrock at version 1.13. anything above 1.13.x is pretty much not guaranteed to work at all in a decent amount of time. [Change.org](https://www.change.org/p/microsoft-bring-back-debugging-symbols-into-minecraft-bedrock-edition)

**Comment by ChristopherHX** [comment] 2020-07-14 10:41
Please download a newer launcher or only play older Minecraft Versions (duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165)
Please read https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165#issuecomment-560015903 to upgrade to `my fork` or `ng preview`

The appimage doesn't have this bug and you will need another launcher version
@pcs3rd I found a pretty good solution, don't use these symbols, launch the game differently.
Still impacts game mods like the opengl patch for macOS

**Closed by ChristopherHX** 2020-07-14 10:41 UTC
