### ISSUE TITLE
Minecraft Education Edition 

### ISSUE THREAD

**Issue by A53o** [minecraft-linux/mcpelauncher-manifest#1037] opened 2024-08-28 21:03 UTC
Would it be possible for education edition to be an option to play in the launcher as its built off of bedrock edition and it's on the Play store, this would be very helpful as I use education quite a bit. it wouldn't have to be updated that much because education edition doesn't update a lot, it could just stay on the latest version without a version switcher.

**Comment by ChristopherHX** [comment] 2024-08-30 20:06
Duplicate of #763 

I cannot login in that version / demo mode is rejected, nothing to share here.
Please subscribe to the linked issue, this isn't something I would work on in the next months.

Someone at the minecraft rtx discord did manage to run Minecraft EDU in wine even with RTX, maybe that's something for you.

**Closed as not planned by ChristopherHX** 2024-08-30 20:06 UTC
Labels: enhancement
