### ISSUE TITLE
Exit code 11 mac os

### ISSUE THREAD

**Issue by jackson1234578** [minecraft-linux/mcpelauncher-manifest#1038] opened 2024-08-30 19:21 UTC
game randomly crashes and launcher log gives exit 11. 

Log:
```
15:12:51 Info  [Launcher] Version: client 4c5f4fd / manifest 80770c4
15:12:51 Info  [Launcher] OS: macOS, Arch: arm64
15:12:51 Info  [Launcher] Reading Launcher Settings File: /Users/jacksonfox/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
15:12:51 Info  [Launcher] Applied Launcher Settings
15:12:51 Trace [Launcher] Loading android libraries
15:12:51 Trace [Launcher] linker loaded
15:12:51 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/jacksonfox/Library/Application Support/mcpelauncher/
15:12:51 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/2116/cmdline to /Users/jacksonfox/Library/Application Support/mcpelauncher/
15:12:51 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client-arm64-v8a to /Users/jacksonfox/Library/Application Support/mcpelauncher/
15:12:51 Trace [REDIRECT] /data/data to /Users/jacksonfox/Library/Application Support/mcpelauncher/
15:12:51 Trace [REDIRECT] . to /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/assets/
15:12:51 Trace [REDIRECT] /proc to /Users/jacksonfox/Library/Application Support/mcpelauncher/proc/
15:12:51 Trace [REDIRECT] /sys to /Users/jacksonfox/Library/Application Support/mcpelauncher/sys/
15:12:51 Trace [LinkerUtils] Loaded OS library libm.dylib
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libc.so 0x107102000
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/liblog.so 0x107282000
15:12:51 Trace [LinkerUtils] Loaded OS library libz.dylib
15:12:51 Warn  [FMOD] Failed to load host libfmod: 'Failed to find data file: lib/native/arm64-v8a/libfmod.dylib', use experimental pulseaudio backend if available
15:12:51 Trace [Launcher] Loading Minecraft library
linker: Warning: "/Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
linker: mcpelauncher_linker_notifylldb /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so 0x107302000
linker: mcpelauncher_linker_notifylldb /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so 0x107481000
15:12:51 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so"...
15:12:51 Info  [Launcher] Loading gamepad mappings
15:12:51 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
15:12:51 Info  [Launcher] Creating window
2024-08-30 15:12:51.857 mcpelauncher-client-arm64-v8a[2116:77069] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
linker: Warning: "/Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
linker: mcpelauncher_linker_notifylldb /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so 0x119882000
linker: mcpelauncher_linker_notifylldb /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so 0x146581000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x102900e04
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x102900dec
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x102900e1c
Found hook: _ZN4FMOD6System4initEijPv @ 0x102a1157c
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x102a360cc
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x102a3638c
15:12:52 Info  [Launcher] Loaded Minecraft library
15:12:52 Debug [Launcher] Minecraft is at offset 0x146581000
15:12:52 Info  [Launcher] Game version: 0.0.0.0
15:12:52 Info  [Launcher] Applying patches
15:12:52 Info  [V8] Applying v8-flags --jitless
15:12:52 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
15:12:52 Info  [Launcher] Initializing JNI
linker: mcpelauncher_linker_notifylldb /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/arm64-v8a/libjnivmsupport.so 0x10fd43000
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
15:12:52 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
15:12:52 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
15:12:52 Trace [Minecraft] Entering JNI_OnLoad 0x6d9c7000
15:12:52 Trace [Minecraft] JNI_OnLoad completed
15:12:52 Trace [JniSupport] Invoking nativeRegisterThis
15:12:52 Trace [JniSupport] Invoking ANativeActivity_onCreate
15:12:52 Info  [Launcher] Executing main thread
15:12:52 Warn  [Main] Android stub called
15:12:52 Warn  [Main] Android stub called
15:12:52 Warn  [Main] Android stub called
15:12:52 Warn  [Main] Android stub called
15:12:52 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
15:12:52 Trace [JniSupport] Invoking start activity callbacks
15:12:52 Error [MCPE] *** setCachedDeviceId(149cd2d0-d9e1-4983-894b-11d6eb84f0ab)
15:12:52 Info  [Bedrock] configureBreakpad with directory: /crash, sessionid is: b8d6f8b6-501d-4493-8518-a62d1179b51e
15:12:52 Info  [Bedrock] configureBreakpad called, directory is: /crash, sessionid is: b8d6f8b6-501d-4493-8518-a62d1179b51e
15:12:52 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/jacksonfox/Library/Application Support/mcpelauncher/'
15:12:52 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
15:12:52 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
15:12:52 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
15:12:52 Warn  [FakeEGL] eglQueryString 308d
15:12:52 Warn  [Main] Android stub called
15:12:52 Info  [GL] Vendor: Google Inc. (Apple)
15:12:52 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:12:52 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:12:52 Info  [GL] Vendor: Google Inc. (Apple)
15:12:52 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:12:52 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:12:52 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libMediaDecoders_Android.so 0x11c002000
15:12:52 Info  [GL] Vendor: Google Inc. (Apple)
15:12:52 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:12:52 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:12:52 Warn  [Main] Android stub called
15:12:52 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
15:12:52 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
15:12:52 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
15:12:52 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/Users/jacksonfox/Library/Application Support/mcpelauncher/'
15:12:52 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/jacksonfox/Library/Application Support/mcpelauncher/'
15:12:52 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
15:12:59 Info  [GL] Vendor: Google Inc. (Apple)
15:12:59 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:12:59 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:12:59 Warn  [Main] Android stub called
15:13:39 Info  [Minecraft] NO LOG FILE! - Opening level '/Users/jacksonfox/Library/Application Support/mcpelauncher/games/com.mojang/minecraftWorlds/tRFX-FwyPzU=/db'
15:13:39 Info  [Minecraft] NO LOG FILE! - [SERVER] Pack Stack - None
15:13:40 Info  [Minecraft] NO LOG FILE! - Player connected: cfxiam, xuid: 
15:13:40 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
15:13:40 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
15:13:40 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
19:13:42 Info  [Minecraft] NO LOG FILE! - Player Spawned: cfxiam xuid: 2535407255616710, pfid: 73d16c7fe4332f79
15:13:55 Info  [GL] Vendor: Google Inc. (Apple)
15:13:55 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:13:55 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:13:55 Warn  [Main] Android stub called
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
15:16:02 Info  [Minecraft] NO LOG FILE! - Player disconnected: cfxiam, xuid: , pfid: 73d16c7fe4332f79
15:16:06 Info  [Minecraft] NO LOG FILE! - Opening level '/Users/jacksonfox/Library/Application Support/mcpelauncher/games/com.mojang/minecraftWorlds/tRFX-FwyPzU=/db'
15:16:06 Info  [Minecraft] NO LOG FILE! - [SERVER] Pack Stack - None
15:16:07 Info  [Minecraft] NO LOG FILE! - Player connected: cfxiam, xuid: 
15:16:08 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
15:16:08 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
15:16:08 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
15:16:10 Info  [Minecraft] NO LOG FILE! - Player Spawned: cfxiam xuid: 2535407255616710, pfid: 73d16c7fe4332f79
15:19:02 Info  [GL] Vendor: Google Inc. (Apple)
15:19:02 Info  [GL] Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)
15:19:02 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.22420 git hash: a3a43254afd1)
15:19:02 Warn  [Main] Android stub called
Signal 11 received
Backtrace elements: 17
#0 0   mcpelauncher-client-arm64-v8a       0x0000000102a0d560 _ZN12CrashHandler12handleSignalEiPv + 280
#1 1   libsystem_platform.dylib            0x000000018ea5e584 _sigtramp + 56
#2 2   ???                                 0x00000001074ad964 0x0 + 4417313124
#3 3   ???                                 0x00000001074b3e94 0x0 + 4417339028
#4 4   ???                                 0x00000001074d82ac 0x0 + 4417487532
#5 5   ???                                 0x00000001074d7d80 0x0 + 4417486208
#6 6   ???                                 0x000000010753da38 0x0 + 4417903160
#7 7   ???                                 0x00000001539144e4 0x0 + 5696996580
#8 8   ???                                 0x0000000153912d24 0x0 + 5696990500
#9 9   ???                                 0x000000014d7f3200 0x0 + 5595148800
#10 10  ???                                 0x000000014c836f00 0x0 + 5578649344
#11 11  ???                                 0x000000014c830e98 0x0 + 5578624664
#12 12  ???                                 0x000000014c82fb64 0x0 + 5578619748
#13 13  ???                                 0x0000000152e04ab4 0x0 + 5685398196
#14 14  ???                                 0x000000014f9f5e04 0x0 + 5630811652
#15 15  mcpelauncher-client-arm64-v8a       0x0000000102816a64 main + 16764
#16 16  dyld                                0x000000018e6a3154 start + 2476
Dumping stack...
#3 LINKER (null)+0x1074ad964 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x2c964 [0x1074ad964]
#4 LINKER (null)+0x1074b3e94 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x32e94 [0x1074b3e94]
#5 LINKER (null)+0x1074d82ac in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x572ac [0x1074d82ac]
#6 LINKER (null)+0x1074d7d80 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x56d80 [0x1074d7d80]
#7 LINKER FMOD::System::update()+0x38 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0xbca38 [0x10753da38]
#8 LINKER (null)+0x1539144e4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd3934e4 [0x1539144e4]
#9 LINKER (null)+0x153912d24 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd391d24 [0x153912d24]
#10 LINKER (null)+0x14d7f3200 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x7272200 [0x14d7f3200]
#11 LINKER (null)+0x14c836f00 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62b5f00 [0x14c836f00]
#12 LINKER (null)+0x14c830e98 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62afe98 [0x14c830e98]
#13 LINKER (null)+0x14c82fb64 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62aeb64 [0x14c82fb64]
#14 LINKER (null)+0x152e04ab4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc883ab4 [0x152e04ab4]
#15 LINKER (null)+0x14f9f5e04 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x9474e04 [0x14f9f5e04]
#75 LINKER (null)+0x107599a20 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x118a20 [0x107599a20]
#97 LINKER (null)+0x1074ad964 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x2c964 [0x1074ad964]
#99 LINKER (null)+0x1074adb74 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x2cb74 [0x1074adb74]
#168 LINKER (null)+0x1074c15a4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x405a4 [0x1074c15a4]
#180 LINKER (null)+0x1074b4c88 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x33c88 [0x1074b4c88]
#225 LINKER (null)+0x1547d5838 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe254838 [0x1547d5838]
#248 LINKER (null)+0x153183ff8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xcc02ff8 [0x153183ff8]
#250 LINKER (null)+0x1533085d0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xcd875d0 [0x1533085d0]
#258 LINKER std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>::__grow_by_and_replace(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char const*)+0xa0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so+0xcb448 [0x11994d448]
#262 LINKER std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>::operator=(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+0xf4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libc++_shared.so+0xcd004 [0x11994f004]
#274 LINKER (null)+0x15391a49c in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd39949c [0x15391a49c]
#276 LINKER (null)+0x15391a350 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd399350 [0x15391a350]
#298 LINKER (null)+0x14d7f3bfc in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x7272bfc [0x14d7f3bfc]
#621 LINKER (null)+0x154965000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3e4000 [0x154965000]
#622 LINKER (null)+0x154954000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3d3000 [0x154954000]
#632 LINKER (null)+0x1074b3e94 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x32e94 [0x1074b3e94]
#640 LINKER (null)+0x1074d82ac in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x572ac [0x1074d82ac]
#660 LINKER (null)+0x1074d7d80 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0x56d80 [0x1074d7d80]
#670 LINKER FMOD::System::update()+0x38 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libfmod.so+0xbca38 [0x10753da38]
#705 LINKER (null)+0x154965000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3e4000 [0x154965000]
#710 LINKER (null)+0x1539144e4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd3934e4 [0x1539144e4]
#712 LINKER (null)+0x153912d24 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xd391d24 [0x153912d24]
#715 LINKER (null)+0x14d7f3200 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x7272200 [0x14d7f3200]
#728 LINKER (null)+0x14c836f00 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62b5f00 [0x14c836f00]
#730 LINKER (null)+0x14c836e24 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62b5e24 [0x14c836e24]
#755 LINKER (null)+0x1545308f0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdfaf8f0 [0x1545308f0]
#762 LINKER (null)+0x14c830e10 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62afe10 [0x14c830e10]
#764 LINKER (null)+0x14c830e98 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62afe98 [0x14c830e98]
#765 LINKER (null)+0x154965000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3e4000 [0x154965000]
#771 LINKER (null)+0x154965000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3e4000 [0x154965000]
#791 LINKER (null)+0x154965f20 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3e4f20 [0x154965f20]
#819 LINKER (null)+0x154309e28 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88e28 [0x154309e28]
#825 LINKER (null)+0x154309da8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88da8 [0x154309da8]
#827 LINKER (null)+0x154a18000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe497000 [0x154a18000]
#837 LINKER (null)+0x154309ca8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88ca8 [0x154309ca8]
#843 LINKER (null)+0x154309c28 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88c28 [0x154309c28]
#845 LINKER (null)+0x154a18000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe497000 [0x154a18000]
#849 LINKER (null)+0x154309ba8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88ba8 [0x154309ba8]
#857 LINKER (null)+0x154a18000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe497000 [0x154a18000]
#861 LINKER (null)+0x154309aa8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xdd88aa8 [0x154309aa8]
#872 LINKER (null)+0x14c82fb64 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x62aeb64 [0x14c82fb64]
#877 LINKER (null)+0x154a18000 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe497000 [0x154a18000]
#884 LINKER (null)+0x152e04ab4 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc883ab4 [0x152e04ab4]
#906 LINKER (null)+0x15494bfb8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe3cafb8 [0x15494bfb8]
#927 LINKER (null)+0x1547b8fb8 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe237fb8 [0x1547b8fb8]
#933 LINKER (null)+0x1547b8f38 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xe237f38 [0x1547b8f38]
#942 LINKER (null)+0x14f9f5e04 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0x9474e04 [0x14f9f5e04]
#958 LINKER (null)+0x0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc87fa70 [0x152e00a70]
#959 LINKER (null)+0x0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc87fa78 [0x152e00a78]
#960 LINKER (null)+0x0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc87fa70 [0x152e00a70]
#961 LINKER (null)+0x0 in /Users/jacksonfox/Library/Application Support/mcpelauncher/versions/1.21.22.01/lib/arm64-v8a/libminecraftpe.so+0xc87fa60 [0x152e00a60]
program failed with unix signal number: 11

Process exited with unexpected exit code: 11
```

I was eating a carrot and the game crashed

**Comment by ChristopherHX** [comment] 2024-08-30 19:48
Duplicate of #1036, downgrade launcher to v0.x for now.

**Closed as not planned by ChristopherHX** 2024-08-30 19:48 UTC
Labels: bug, crash, Mac OS X
