### ISSUE TITLE
Error code: 127

### ISSUE THREAD

**Issue by NeoLight1010** [minecraft-linux/mcpelauncher-manifest#299] opened 2020-05-06 16:58 UTC
I'm getting this error:

> /tmp/.mount_MinecrHQntwA/usr/bin/./mcpelauncher-client: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
> Process exited with unexpected exit code: 127

My specs are:
RAM: 8Gb
Processor: Intel Core i7-6700 3.40GHz x 8
Graphics: Nvidia Geforce GT 730
OS type: 64-bit

**Comment by NeoLight1010** [comment] 2020-05-07 01:03
My OS is Zorus 15.2, based on Ubuntu.

**Comment by ChristopherHX** [comment] 2020-05-22 12:13
Please read https://mcpelauncher.readthedocs.io/en/latest/getting_started.html more careful, you need to install 32bit graphics drivers

**Comment by ChristopherHX** [comment] 2020-06-03 21:24
duplicate of #94

**Closed by ChristopherHX** 2020-06-03 21:24 UTC
Labels: User Error, duplicate
