### ISSUE TITLE
Steam deck game mode: game doesn't respond to any controller inputs.

### ISSUE THREAD

**Issue by hl2jeep** [minecraft-linux/mcpelauncher-manifest#785] opened 2023-02-12 11:55 UTC
title.
this is on the newest stable branch of steam os 3, also using the lastest version of the launcher from flathub.
also using the newest google play release. the older versions work fine

**Comment by RavinMaddHatter** [comment] 2023-02-13 05:17
Same issue, 

i browsed to the flatpack folder and found that camecontrollerdb.txt didnt exist. i created it, and then ran gamepad tool. I attempted with the steamdeck profile and with a profile for a PS3 controller i had lying around.

I cant unplug the steamdeck controller, but i could unplug the PS3, neither functioned. Happy to give more data but i dont know what would be useful for debug.

V0.8.1-flatpack-qt6 (build 56)

**Comment by ChristopherHX** [comment] 2023-02-13 21:33
The following report provided an important detail that this is a regression caused by a game change https://github.com/flathub/io.mrarm.mcpelauncher/issues/94.

You can still play with controllers on Minecraft 1.19.50 or lower.

_Too many repos, where the same issue can be reported, but it is a false claim that this is related to steam deck only_

**Comment by RavinMaddHatter** [comment] 2023-02-14 00:42
Note on the Steam deck you can use the default "Keyboard  (WASD) and mouse" as a starting point to get you close. I enabled "full keyboard support" and remapped some buttons in the control editor, then remapped the ingame controlls a bit. it is not good but it is playable. It does require touch screen inventory managment and some menus. but the rest is fine. After i finish a work around steam profile i will post a link to it. But i want to minimize the number of remaps in game.

This should work as a limp along method as long as mouse and keyboard work...

**Comment by ChristopherHX** [comment] 2023-02-28 22:52
Fixed in 0.8.5

**Closed as completed by ChristopherHX** 2023-02-28 22:52 UTC
Labels: bug
