### ISSUE TITLE
[AppImage] Cannot Launch Minecraft, Crashes on Launch

### ISSUE THREAD

**Issue by ThisNekoGuy** [minecraft-linux/mcpelauncher-manifest#520] opened 2021-06-03 00:32 UTC
**OS:** Arch Linux (Rolling release)
**CPU:** Ryzen 3700X (x86_64)
**GPU:** RTX 2080 Ti
**GPU Driver:** 460.80
**Launcher:** [AppImage](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.2.1-661)
**Game version:** 1.16.211.01

```
19:26:35 Info  [Launcher] Version: client 992db17 / manifest 8cae128
19:26:35 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 7 3700X 8-Core Processor             
19:26:35 Info  [Launcher] CPU supports SSSE3: YES
19:26:35 Trace [Launcher] Loading hybris libraries
19:26:35 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /mnt/bigStorage/Gaming/Lutris/mcpelauncher/
19:26:35 Trace [REDIRECT] /data/data/tmp/.mount_Minecr93UHLy/usr/proc/1388083/cmdline to /mnt/bigStorage/Gaming/Lutris/mcpelauncher/
19:26:35 Trace [REDIRECT] /data/data/tmp/.mount_Minecr93UHLy/usr/bin/./mcpelauncher-client to /mnt/bigStorage/Gaming/Lutris/mcpelauncher/
19:26:35 Trace [REDIRECT] /data/data to /mnt/bigStorage/Gaming/Lutris/mcpelauncher/
19:26:35 Trace [HybrisUtils] Loaded OS library libm.so.6
19:26:35 Trace [HybrisUtils] Loaded OS library libz.so.1
19:26:35 Trace [HybrisUtils] Loaded OS library /tmp/.mount_Minecr93UHLy/usr/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
19:26:35 Trace [Launcher] Loading Minecraft library
19:26:35 Info  [Launcher] Loaded Minecraft library
19:26:35 Debug [Launcher] Minecraft is at offset 0x0x7f24d2100000
19:26:35 Info  [Launcher] Game version: 0.0.0.0
19:26:35 Info  [Launcher] Applying patches
19:26:35 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
19:26:35 Info  [Launcher] Initializing JNI
19:26:35 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
19:26:35 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
19:26:35 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
19:26:35 Info  [Launcher] Executing main thread
19:26:35 Trace [Minecraft] Entering JNI_OnLoad 0x7f24d20ff640
19:26:35 Trace [Minecraft] JNI_OnLoad completed
19:26:35 Trace [JniSupport] Invoking nativeRegisterThis
19:26:35 Trace [JniSupport] Invoking ANativeActivity_onCreate
19:26:35 Warn  [Main] Android stub called
19:26:35 Warn  [Main] Android stub called
19:26:35 Warn  [Main] Android stub called
19:26:35 Warn  [Main] Android stub called
19:26:35 Info  [Launcher] Loading gamepad mappings
19:26:35 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_Minecr93UHLy/usr/share/mcpelauncher/gamecontrollerdb.txt
19:26:35 Info  [Launcher] Creating window
libevdev_new_from_fd error -22 (/dev/input/js2)
libevdev_new_from_fd error -22 (/dev/input/js3)
19:26:35 Trace [WindowCallbacks] Gamepad connected #1
Signal 11 received
Backtrace elements: 3
#0 /tmp/.mount_Minecr93UHLy/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xfc) [0xb950ac]
#1 /usr/lib/libpthread.so.0(+0x13870) [0x7f24e3c48870]
#2 HYBRIS (null)+0x7 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f0f7e7 [0x0x7f24d400f7e7]
Dumping stack...
#23 HYBRIS (null)+(nil) in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f0f7e0 [0x0x7f24d400f7e0]
#25 HYBRIS (null)+0x7 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f0f7e7 [0x0x7f24d400f7e7]
#213 HYBRIS (null)+(nil) in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f0f7e0 [0x0x7f24d400f7e0]
#471 HYBRIS (null)+0x7f24d40551a2 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f551a2 [0x0x7f24d40551a2]
#480 HYBRIS (null)+0x7f24d4055100 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f55100 [0x0x7f24d4055100]
#486 HYBRIS (null)+0x7f24d4055100 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f55100 [0x0x7f24d4055100]
#493 HYBRIS (null)+0x7f24d2100000 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x(nil) [0x0x7f24d2100000]
#494 HYBRIS (null)+0x7f24d2100000 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x(nil) [0x0x7f24d2100000]
#836 HYBRIS (null)+0x7f24d40549b0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f549b0 [0x0x7f24d40549b0]
#837 HYBRIS (null)+0x7f24d4054a60 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54a60 [0x0x7f24d4054a60]
#838 HYBRIS (null)+0x7f24d4054b10 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54b10 [0x0x7f24d4054b10]
#839 HYBRIS (null)+0x7f24d4054bf0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54bf0 [0x0x7f24d4054bf0]
#840 HYBRIS (null)+0x7f24d4054ca0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54ca0 [0x0x7f24d4054ca0]
#841 HYBRIS (null)+0x7f24d40548d0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f548d0 [0x0x7f24d40548d0]
#842 HYBRIS (null)+0x7f24d4054df0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54df0 [0x0x7f24d4054df0]
#843 HYBRIS (null)+0x7f24d4054e50 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54e50 [0x0x7f24d4054e50]
#846 HYBRIS (null)+0x7f24d4054f70 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54f70 [0x0x7f24d4054f70]
#847 HYBRIS (null)+0x7f24d4055030 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f55030 [0x0x7f24d4055030]
#848 HYBRIS (null)+0x7f24d4055040 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f55040 [0x0x7f24d4055040]
#850 HYBRIS (null)+0x7f24d4054d50 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54d50 [0x0x7f24d4054d50]
#851 HYBRIS (null)+0x7f24d4054da0 in /home/neko-san/.local/share/mcpelauncher/versions/1.16.221.01/lib/x86_64/libminecraftpe.so+0x0x1f54da0 [0x0x7f24d4054da0]

Process exited with unexpected exit code: 6

```

**Comment by ChristopherHX** [comment] 2021-06-03 09:21
Duplicate of #510

**Closed by ChristopherHX** 2021-06-03 09:21 UTC
