### ISSUE TITLE
Failed to load Minecraft: Cannot load library

### ISSUE THREAD

**Issue by josh-hetland** [minecraft-linux/mcpelauncher-manifest#285] opened 2020-04-23 17:01 UTC
11:31:05 Info  [Launcher] Version: client c735370 / manifest b3dd620
11:31:05 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
11:31:05 Info  [Launcher] CPU supports SSSE3: YES
11:31:05 Trace [Launcher] Loading hybris libraries
11:31:05 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
11:31:05 Trace [HybrisUtils] Loaded OS library libm.so.6
11:31:05 Trace [HybrisUtils] Loaded OS library libz.so.1
11:31:05 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x5686f729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f53090]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f53079]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf7830832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf7831cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b8e97d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7b96174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf7b961dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf7b964dc]
#9 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x183) [0x56870c03]
#10 /usr/bin/mcpelauncher-client(main+0xff8) [0x5680b6d4]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf781be81]
#12 /usr/bin/mcpelauncher-client(+0x1dc0f1) [0x5680a0f1]
Dumping stack...
Process exited with unexpected exit code: 6

**Comment by josh-hetland** [comment] 2020-04-23 20:47
I'm getting this error on 3 different 18.04 ubuntu machines

**Comment by emomo666** [comment] 2020-04-23 22:34
I'm having the same issue...

**Comment by ChristopherHX** [comment] 2020-04-25 13:36
**Broken install of the Minecraft Version**
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/78#issuecomment-617794215

**Comment by ChristopherHX** [comment] 2020-04-25 13:37
And an it is unsupported current master (legacy launcher)

**Comment by Bloodiko** [comment] 2020-04-29 16:42
@ChristopherHX if its the legacy launcher , which is the new official supported one ?

**Comment by ChristopherHX** [comment] 2020-04-29 23:20
There is currently no new official supported one. **(ng is still experimental somewhat based on my legacy fork approach + new linker + 64bit support + beta support)**

I partially support my [legacy fork (it is a link for the linux build)](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage) which supports 1.14.60.5 incl. 1.16 beta (even if the beta is crashing far more often than 1.14 stable)
If you install that make shure to read also this https://github.com/ChristopherHX/mcpelauncher-manifest/issues/78#issuecomment-617794215

**Comment by ChristopherHX** [comment] 2020-06-01 21:12
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:12 UTC
