### ISSUE TITLE
Process exited with unexpected exit code: 6

### ISSUE THREAD

**Issue by JuanjoCatala** [minecraft-linux/mcpelauncher-manifest#304] opened 2020-05-20 11:11 UTC
OS: Debian GNU/Linux bullseye/sid x86_64 
Host: 80QR Lenovo B50-10 
Kernel: 5.6.0-1-amd64 
CPU: Intel Celeron N2840 (2) @ 2.582GHz 
GPU: Intel Atom Processor Z36xxx/Z37xxx Series Gr 

I'm using AppImage
Game version: 1.14.60.5

13:06:59 Info  [Launcher] Version: client c735370 / manifest b3dd620
13:06:59 Info  [Launcher] CPU: GenuineIntel       Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
13:06:59 Info  [Launcher] CPU supports SSSE3: YES
13:06:59 Trace [Launcher] Loading hybris libraries
13:06:59 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecrdGIsTN/usr/share/mcpelauncher/libs/native/libfmod.so.9.16
13:06:59 Trace [HybrisUtils] Loaded OS library libm.so.6
13:06:59 Trace [HybrisUtils] Loaded OS library libz.so.1
13:06:59 Trace [Launcher] Loading Minecraft library
linkerterminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Minecraft: Cannot load library: link_image[1965]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1115]: Library 'libgnustl_shared.so' not found)
Signal 6 received
Backtrace elements: 13
#0 /tmp/.mount_MinecrdGIsTN/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xb7) [0x82f3a0f]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7fa5180]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fa5169]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf765f8e2]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x12c) [0xf7648309]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x79994) [0xf79cd994]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x87364) [0xf79db364]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x873dd) [0xf79db3dd]
#8 /lib/i386-linux-gnu/libstdc++.so.6(+0x876dc) [0xf79db6dc]
#9 /tmp/.mount_MinecrdGIsTN/usr/bin/./mcpelauncher-client(_ZN14MinecraftUtils16loadMinecraftLibERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14c) [0x82f4b52]
#10 /tmp/.mount_MinecrdGIsTN/usr/bin/./mcpelauncher-client(main+0xece) [0x829e6b0]
#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf7649ef1]
#12 /tmp/.mount_MinecrdGIsTN/usr/bin/./mcpelauncher-client() [0x829d311]
Dumping stack...

**Comment by ChristopherHX** [comment] 2020-06-01 21:15
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:15 UTC
Labels: bug, crash, duplicate, legacy (unsupported)
