### ISSUE TITLE
1.16.100.50 crashes upon opening on MacOS HighSierra

### ISSUE THREAD

**Issue by NecrozmaBoy** [minecraft-linux/mcpelauncher-manifest#370] opened 2020-08-05 00:48 UTC
Every time I open the game I get the error "Minecraft has exited with a non-zero error code. How do I fix this?

**Comment by ChristopherHX** [comment] 2020-08-05 20:22
Why do you want to play beta and not release 1.16.10.02?
duplicate of #340

**Closed by ChristopherHX** 2020-08-05 20:22 UTC
Labels: duplicate
