### ISSUE TITLE
Error playing minecraft in any version above 1.12.1

### ISSUE THREAD

**Issue by CallumI1** [minecraft-linux/mcpelauncher-manifest#301] opened 2020-05-11 20:08 UTC
22:07:57 Info  [Launcher] Version: client c735370 / manifest b3dd620
22:07:57 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
22:07:57 Info  [Launcher] CPU supports SSSE3: YES
22:07:57 Trace [Launcher] Loading hybris libraries
22:07:57 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
22:07:57 Trace [HybrisUtils] Loaded OS library libm.so.6
22:07:57 Trace [HybrisUtils] Loaded OS library libz.so.1
22:07:57 Trace [Launcher] Loading Minecraft library
22:07:57 Info  [Launcher] Loaded Minecraft library
22:07:57 Debug [Launcher] Minecraft is at offset 0xe3edf000
22:07:57 Trace [Launcher] Initializing vtables
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
22:07:57 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
22:07:57 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 14
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xce) [0x56611f2e]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f28170]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f28159]
#3 /usr/lib32/libc.so.6(gsignal+0xc6) [0xf77a99b6]
#4 /usr/lib32/libc.so.6(abort+0x130) [0xf77923f5]
#5 /usr/lib32/libstdc++.so.6(+0x7593e) [0xf7ae293e]
#6 /usr/lib32/libstdc++.so.6(+0x83957) [0xf7af0957]
#7 /usr/lib32/libstdc++.so.6(+0x839e3) [0xf7af09e3]
#8 /usr/lib32/libstdc++.so.6(+0x83d25) [0xf7af0d25]
#9 /usr/bin/mcpelauncher-client(+0x4e9d6) [0x565d79d6]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x2f) [0x56612e1f]
#11 /usr/bin/mcpelauncher-client(main+0xbbc) [0x565db5ac]
#12 /usr/lib32/libc.so.6(__libc_start_main+0xf5) [0xf7793ee5]
#13 /usr/bin/mcpelauncher-client(_start+0x35) [0x565dce45]
Dumping stack...
#1 HYBRIS (null)+-410030768 in libminecraftpe.so+0x3a17d50 [0xe78f6d50]
#5 HYBRIS (null)+-470945792 in libminecraftpe.so+0x0000 [0xe3edf000]
#26 HYBRIS (null)+-409992512 in libminecraftpe.so+0x3a212c0 [0xe79002c0]
#27 HYBRIS (null)+-409996208 in libminecraftpe.so+0x3a20450 [0xe78ff450]
#30 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#31 HYBRIS (null)+-409992368 in libminecraftpe.so+0x3a21350 [0xe7900350]
#32 HYBRIS (null)+-409992416 in libminecraftpe.so+0x3a21320 [0xe7900320]
#67 HYBRIS (null)+-409928368 in libminecraftpe.so+0x3a30d50 [0xe790fd50]
#70 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#100 HYBRIS (null)+-462029329 in libminecraftpe.so+0x880def [0xe475fdef]
#101 HYBRIS (null)+-409859504 in libminecraftpe.so+0x3a41a50 [0xe7920a50]
#102 HYBRIS (null)+-409863200 in libminecraftpe.so+0x3a40be0 [0xe791fbe0]
#106 HYBRIS (null)+-409855712 in libminecraftpe.so+0x3a42920 [0xe7921920]
#107 HYBRIS (null)+-409859408 in libminecraftpe.so+0x3a41ab0 [0xe7920ab0]
#110 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#111 HYBRIS (null)+-409855568 in libminecraftpe.so+0x3a429b0 [0xe79219b0]
#112 HYBRIS (null)+-409855616 in libminecraftpe.so+0x3a42980 [0xe7921980]
#116 HYBRIS (null)+-409842432 in libminecraftpe.so+0x3a45d00 [0xe7924d00]
#117 HYBRIS (null)+-409844192 in libminecraftpe.so+0x3a45620 [0xe7924620]
#120 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe48edd5c]
#121 HYBRIS (null)+-409834848 in libminecraftpe.so+0x3a47aa0 [0xe7926aa0]
#122 HYBRIS (null)+-409842336 in libminecraftpe.so+0x3a45d60 [0xe7924d60]
#126 HYBRIS (null)+-409827728 in libminecraftpe.so+0x3a49670 [0xe7928670]
#127 HYBRIS (null)+-409834752 in libminecraftpe.so+0x3a47b00 [0xe7926b00]
#131 HYBRIS (null)+-409820144 in libminecraftpe.so+0x3a4b410 [0xe792a410]
#132 HYBRIS (null)+-409827632 in libminecraftpe.so+0x3a496d0 [0xe79286d0]
#136 HYBRIS (null)+-409809328 in libminecraftpe.so+0x3a4de50 [0xe792ce50]
#137 HYBRIS (null)+-409820048 in libminecraftpe.so+0x3a4b470 [0xe792a470]
#141 HYBRIS (null)+-409805536 in libminecraftpe.so+0x3a4ed20 [0xe792dd20]
#142 HYBRIS (null)+-409809232 in libminecraftpe.so+0x3a4deb0 [0xe792ceb0]
#146 HYBRIS (null)+-409801744 in libminecraftpe.so+0x3a4fbf0 [0xe792ebf0]
#147 HYBRIS (null)+-409805440 in libminecraftpe.so+0x3a4ed80 [0xe792dd80]
#150 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#151 HYBRIS (null)+-409799808 in libminecraftpe.so+0x3a50380 [0xe792f380]
#152 HYBRIS (null)+-409801648 in libminecraftpe.so+0x3a4fc50 [0xe792ec50]
#156 HYBRIS (null)+-409796016 in libminecraftpe.so+0x3a51250 [0xe7930250]
#157 HYBRIS (null)+-409799712 in libminecraftpe.so+0x3a503e0 [0xe792f3e0]
#160 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe48edd5c]
#161 HYBRIS (null)+-409795872 in libminecraftpe.so+0x3a512e0 [0xe79302e0]
#162 HYBRIS (null)+-409795920 in libminecraftpe.so+0x3a512b0 [0xe79302b0]
#166 HYBRIS (null)+-409780800 in libminecraftpe.so+0x3a54dc0 [0xe7933dc0]
#167 HYBRIS (null)+-409784496 in libminecraftpe.so+0x3a53f50 [0xe7932f50]
#171 HYBRIS (null)+-409769984 in libminecraftpe.so+0x3a57800 [0xe7936800]
#172 HYBRIS (null)+-409780704 in libminecraftpe.so+0x3a54e20 [0xe7933e20]
#176 HYBRIS (null)+-409769840 in libminecraftpe.so+0x3a57890 [0xe7936890]
#177 HYBRIS (null)+-409769888 in libminecraftpe.so+0x3a57860 [0xe7936860]
#181 HYBRIS (null)+-409758416 in libminecraftpe.so+0x3a5a530 [0xe7939530]
#182 HYBRIS (null)+-409758464 in libminecraftpe.so+0x3a5a500 [0xe7939500]
#186 HYBRIS (null)+-409736320 in libminecraftpe.so+0x3a5fb80 [0xe793eb80]
#187 HYBRIS (null)+-409747040 in libminecraftpe.so+0x3a5d1a0 [0xe793c1a0]
#190 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#191 HYBRIS (null)+-409735312 in libminecraftpe.so+0x3a5ff70 [0xe793ef70]
#192 HYBRIS (null)+-409736224 in libminecraftpe.so+0x3a5fbe0 [0xe793ebe0]
#196 HYBRIS (null)+-409735168 in libminecraftpe.so+0x3a60000 [0xe793f000]
#197 HYBRIS (null)+-409735216 in libminecraftpe.so+0x3a5ffd0 [0xe793efd0]
#200 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xe48edd5c]
#201 HYBRIS (null)+-409716304 in libminecraftpe.so+0x3a649b0 [0xe79439b0]
#202 HYBRIS (null)+-409723792 in libminecraftpe.so+0x3a62c70 [0xe7941c70]
#206 HYBRIS (null)+-409716160 in libminecraftpe.so+0x3a64a40 [0xe7943a40]
#207 HYBRIS (null)+-409716208 in libminecraftpe.so+0x3a64a10 [0xe7943a10]
#211 HYBRIS (null)+-409685760 in libminecraftpe.so+0x3a6c100 [0xe794b100]
#212 HYBRIS (null)+-409685808 in libminecraftpe.so+0x3a6c0d0 [0xe794b0d0]
#216 HYBRIS (null)+-409655360 in libminecraftpe.so+0x3a737c0 [0xe79527c0]
#217 HYBRIS (null)+-409655408 in libminecraftpe.so+0x3a73790 [0xe7952790]
#221 HYBRIS (null)+-409624960 in libminecraftpe.so+0x3a7ae80 [0xe7959e80]
#222 HYBRIS (null)+-409625008 in libminecraftpe.so+0x3a7ae50 [0xe7959e50]
#226 HYBRIS (null)+-409590912 in libminecraftpe.so+0x3a83380 [0xe7962380]
#227 HYBRIS (null)+-409594608 in libminecraftpe.so+0x3a82510 [0xe7961510]
#230 HYBRIS (null)+-348780284 in libminecraftpe.so+0x7481904 [0xeb360904]
#231 HYBRIS (null)+-409589904 in libminecraftpe.so+0x3a83770 [0xe7962770]
#232 HYBRIS (null)+-409590816 in libminecraftpe.so+0x3a833e0 [0xe79623e0]
#236 HYBRIS (null)+-409586112 in libminecraftpe.so+0x3a84640 [0xe7963640]
#237 HYBRIS (null)+-409589808 in libminecraftpe.so+0x3a837d0 [0xe79627d0]
#242 HYBRIS (null)+-409599997 in libminecraftpe.so+0x3a81003 [0xe7960003]
#246 HYBRIS (null)+-409573312 in libminecraftpe.so+0x3a87840 [0xe7966840]
#247 HYBRIS (null)+-409575152 in libminecraftpe.so+0x3a87110 [0xe7966110]
#252 HYBRIS (null)+-460500500 in libminecraftpe.so+0x9f61ec [0xe48d51ec]
#255 HYBRIS (null)+-405878368 in libminecraftpe.so+0x3e0d9a0 [0xe7cec9a0]
#501 HYBRIS (null)+-457965558 in libminecraftpe.so+0xc6100a [0xe4b4000a]
#766 HYBRIS vtable for xbox::services::local_config+0 in libminecraftpe.so+0x7445d18 [0xeb324d18]
#767 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7445d20 [0xeb324d20]
#787 HYBRIS (null)+-470945792 in libminecraftpe.so+0x0000 [0xe3edf000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-01 22:09
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:09 UTC
Labels: crash, duplicate, legacy (unsupported)
