### ISSUE TITLE
Minecraft has exited with non-zero error code! Process exited with unexpected exit code: 6

### ISSUE THREAD

**Issue by dmitlenko** [minecraft-linux/mcpelauncher-manifest#314] opened 2020-05-24 14:29 UTC
Ubuntu 18.04

17:27:45 Info  [Launcher] Version: client c735370 / manifest b3dd620
17:27:45 Info  [Launcher] CPU: AuthenticAMD AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx  
17:27:45 Info  [Launcher] CPU supports SSSE3: YES
17:27:45 Trace [Launcher] Loading hybris libraries
17:27:45 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
17:27:45 Trace [HybrisUtils] Loaded OS library libm.so.6
17:27:45 Trace [HybrisUtils] Loaded OS library libz.so.1
17:27:45 Trace [Launcher] Loading Minecraft library
17:27:45 Info  [Launcher] Loaded Minecraft library
17:27:45 Debug [Launcher] Minecraft is at offset 0xe2127000
17:27:45 Trace [Launcher] Initializing vtables
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
17:27:45 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
17:27:45 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567fa729]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7efeb70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7efeb59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf77d1832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf77d2cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b2f97d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x76174) [0xf7b37174]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x761dd) [0xf7b371dd]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x764dc) [0xf7b374dc]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x5684faa1]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567fbf22]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567fbe1a]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x5679679e]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf77bce81]
#14 /usr/bin/mcpelauncher-client(+0x1dc0f1) [0x567950f1]
Dumping stack...
#2 HYBRIS (null)+-441934624 in libminecraftpe.so+0x3962ce0 [0xe5a89ce0]
#13 HYBRIS (null)+-502108160 in libminecraftpe.so+0x0000 [0xe2127000]
#32 HYBRIS (null)+-441894768 in libminecraftpe.so+0x396c890 [0xe5a93890]
#33 HYBRIS (null)+-441894816 in libminecraftpe.so+0x396c860 [0xe5a93860]
#36 HYBRIS (null)+-493258593 in libminecraftpe.so+0x87089f [0xe299789f]
#37 HYBRIS (null)+-441876528 in libminecraftpe.so+0x3970fd0 [0xe5a97fd0]
#38 HYBRIS (null)+-441880224 in libminecraftpe.so+0x3970160 [0xe5a97160]
#77 HYBRIS (null)+-441822560 in libminecraftpe.so+0x397e2a0 [0xe5aa52a0]
#78 HYBRIS (null)+-441826256 in libminecraftpe.so+0x397d430 [0xe5aa4430]
#108 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#111 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#112 HYBRIS (null)+-441786879 in libminecraftpe.so+0x3986e01 [0xe5aade01]
#113 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#114 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#116 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#117 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#119 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#120 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#122 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#123 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#125 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#126 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#128 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#129 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#131 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#132 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#134 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#135 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#137 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#138 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#140 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#141 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#143 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#144 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#146 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#147 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#149 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#150 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#152 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#153 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#155 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#156 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#158 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#159 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#161 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#162 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#164 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#165 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#167 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#168 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#170 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#171 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#173 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#174 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#176 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#177 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#179 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#180 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#182 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#183 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#185 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#186 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#188 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#189 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#191 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#192 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#194 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#195 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#197 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#198 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#200 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#201 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#203 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#204 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#206 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#207 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#209 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#213 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#215 HYBRIS (null)+-412321956 in libminecraftpe.so+0x55a075c [0xe76c775c]
#216 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#219 HYBRIS (null)+-412322047 in libminecraftpe.so+0x55a0701 [0xe76c7701]
#731 HYBRIS (null)+-502108160 in libminecraftpe.so+0x0000 [0xe2127000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-06-01 22:10
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:10 UTC
