### ISSUE TITLE
Close when i open

### ISSUE THREAD

**Issue by portacha** [minecraft-linux/mcpelauncher-manifest#256] opened 2020-03-24 23:15 UTC
17:13:36 Info  [Launcher] Version: client c735370 / manifest eb0bc83
17:13:36 Info  [Launcher] CPU: GenuineIntel        Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
17:13:36 Info  [Launcher] CPU supports SSSE3: YES
17:13:36 Trace [Launcher] Loading hybris libraries
17:13:36 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
17:13:36 Trace [HybrisUtils] Loaded OS library libm.dylib
17:13:36 Error [HybrisUtils] Failed to load OS library libz.so.1
17:13:36 Trace [Launcher] Loading Minecraft library
17:13:36 Info  [Launcher] Loaded Minecraft library
17:13:36 Debug [Launcher] Minecraft is at offset 0x3765000
17:13:36 Trace [Launcher] Initializing vtables
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
17:13:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
17:13:36 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 13
#0 0   mcpelauncher-client                 0x0015e88e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa17b8e5b _sigtramp + 43
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa163ea34 abort + 141
#4 4   libc++abi.dylib                     0xa01c5df7 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa01e6371 _ZL25default_terminate_handlerv + 244
#6 6   libc++abi.dylib                     0xa01e3551 _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa01e2f7b _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
#8 8   mcpelauncher-client                 0x001da18c _Z21minecraft_get_versionPiS_S_S_ + 396
#9 9   mcpelauncher-client                 0x001607f9 _ZN16MinecraftVersion4initEv + 57
#10 10  mcpelauncher-client                 0x0015ff85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#11 11  mcpelauncher-client                 0x000a4790 main + 10208
#12 12  libdyld.dylib                       0xa15af395 start + 1
Dumping stack...
#485 HYBRIS (null)+60328284 in libminecraftpe.so+0x22395c [0x398895c]
#518 HYBRIS (null)+58085652 in libminecraftpe.so+0x0114 [0x3765114]
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7445d20 [0xabaad20]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7445d20 [0xabaad20]
#627 HYBRIS (null)+58085376 in libminecraftpe.so+0x0000 [0x3765000]
#674 HYBRIS (null)+58085376 in libminecraftpe.so+0x0000 [0x3765000]
#675 HYBRIS (null)+58085376 in libminecraftpe.so+0x0000 [0x3765000]
Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment] 2020-03-25 20:17
Works as designed by the dev.
These Versions works with this repository 0.12-1.13.0.6, 1.13.0.15, 1.13.0.34, 1.14.1.3 and 1.14.1.5
Try my version if you wish to run them anyways
Link under github forks .

**Comment by ChristopherHX** [comment] 2020-06-01 22:04
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:04 UTC
