### ISSUE TITLE
Failed to load OS library?

### ISSUE THREAD

**Issue by emomo666** [minecraft-linux/mcpelauncher-manifest#286] opened 2020-04-23 23:18 UTC
15:35:32 Info  [Launcher] Version: client 7c17ac3 / manifest 05861bf
15:35:32 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
15:35:32 Info  [Launcher] CPU supports SSSE3: YES
15:35:32 Trace [Launcher] Loading hybris libraries
15:35:32 Trace [HybrisUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/libs/native/libfmod.dylib
15:35:32 Trace [HybrisUtils] Loaded OS library libm.dylib
15:35:32 Error [HybrisUtils] Failed to load OS library libz.so.1
15:35:32 Info  [Launcher] Creating window
15:35:32 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
15:35:32 Trace [Launcher] Loading Minecraft library
linkerProcess exited with unexpected exit code: 9

**Comment by ChristopherHX** [comment] 2020-04-25 13:35
**Broken install of the Minecraft Version**
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/78#issuecomment-617794215

**Comment by ChristopherHX** [comment] 2020-06-01 21:23
duplicate of #271

**Closed by ChristopherHX** 2020-06-01 21:23 UTC
