### ISSUE TITLE
crash on exit from game every time

### ISSUE THREAD

**Issue by pellcorp** [minecraft-linux/mcpelauncher-manifest#115] opened 2019-07-05 12:27 UTC
Running minecraft 1.11.4, this issue happens on both ubuntu 18.04 and 19.04

The game plays fine but crashes due to:

21:05:52 Debug [Launcher] Minecraft is at offset 0xee081000
21:05:52 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
21:05:52 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
21:05:52 Info  [Launcher] Game version: 1.11.4

[logfile.txt](https://github.com/minecraft-linux/mcpelauncher-manifest/files/3362665/logfile.txt)

**Comment by Xenorio** [comment] 2019-07-23 08:56
Same on Manjaro 18.0.4 using the AppImage

Crash log: https://pastebin.com/Lckragq0

**Comment by ChristopherHX** [comment] 2020-06-07 18:09
duplicate of #89 (newer comments are another issue)
[my fork avoids the error at exit, with `_Exit(0)` quit the launcher immediately (won't give the launcher any chance to crash before exit)](https://github.com/ChristopherHX/mcpelauncher-manifest/releases)

**Closed by ChristopherHX** 2020-06-07 18:09 UTC
Labels: crash
