### ISSUE TITLE
unable to sign into google account 

### ISSUE THREAD

**Issue by emmygoalie23** [minecraft-linux/mcpelauncher-manifest#268] opened 2020-04-15 02:27 UTC
I had to delete the launcher off my mac and when I re downloaded I went to set up, but when I tried to sign into my google acc it said the browser isn't secure. not sure if this is happening to anyone else but I don't know what to do. just want to get to play again :/

**Comment by InductedPine** [comment] 2020-04-17 21:03
hey, the same thing happened to me, you have to delete your current version and download a newer version. sorry, I don't have the link but if you search your issue up, with a little bit of searching, you should be able to find the newest launcher.

**Comment by ChristopherHX** [comment] 2020-06-03 21:45
You may use the launcher found here https://github.com/ChristopherHX/mcpelauncher-manifest/releases, or login may fail on macOS

**Comment by ChristopherHX** [comment] 2020-06-04 12:44
duplicate of #140

**Closed by ChristopherHX** 2020-06-04 12:44 UTC
