### ISSUE TITLE
crafting table not working minecraft 1.16.220.02 (x86_64)

### ISSUE THREAD

**Issue by Awiteb** [minecraft-linux/mcpelauncher-manifest#490] opened 2021-04-22 02:02 UTC
I cannot use the crafting table

**Comment by Awiteb** [comment] 2021-04-22 02:08
# Some pictures

https://prnt.sc/11u0qfk
https://prnt.sc/11u0ly8
https://prnt.sc/11u0p7x

**Comment by ChristopherHX** [comment] 2021-04-22 16:41
Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/478

**Closed by ChristopherHX** 2021-04-22 16:41 UTC
