### ISSUE TITLE
Crash with error code 6 in 1.14.0.4 Beta

### ISSUE THREAD

**Issue by Xico26** [minecraft-linux/mcpelauncher-manifest#181] opened 2019-11-05 10:58 UTC
Hi. In my VM with Kubuntu I got this crash when trying to play MC 1.14.0.4

libEGL warning: DRI2: failed to authenticate
10:57:02 Info  [Launcher] Version: client c735370 / manifest eb0bc83
10:57:02 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
10:57:02 Info  [Launcher] CPU supports SSSE3: YES
10:57:02 Trace [Launcher] Loading hybris libraries
10:57:02 Trace [HybrisUtils] Loaded OS library /usr/share/mcpelauncher/libs/native/libfmod.so.9.16
10:57:02 Trace [HybrisUtils] Loaded OS library libm.so.6
10:57:02 Trace [HybrisUtils] Loaded OS library libz.so.1
10:57:02 Trace [Launcher] Loading Minecraft library
10:57:03 Info  [Launcher] Loaded Minecraft library
10:57:03 Debug [Launcher] Minecraft is at offset 0xe9990000
10:57:03 Trace [Launcher] Initializing vtables
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
10:57:03 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
10:57:03 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x567fde43]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f42b40]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f42b29]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc6) [0xf7783616]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x130) [0xf776b3f7]
#5 /lib/i386-linux-gnu/libstdc++.so.6(+0x7d7f6) [0xf7b017f6]
#6 /lib/i386-linux-gnu/libstdc++.so.6(+0x8be48) [0xf7b0fe48]
#7 /lib/i386-linux-gnu/libstdc++.so.6(+0x8bec1) [0xf7b0fec1]
#8 /lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7b101f0]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x56850cde]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x567ff63c]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x567ff534]
#12 /usr/bin/mcpelauncher-client(main+0x10bc) [0x567a77e0]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf9) [0xf776cfb9]
#14 /usr/bin/mcpelauncher-client(_start+0x31) [0x567a6241]
Dumping stack...
#1 HYBRIS (null)+-315482576 in libminecraftpe.so+0x3991e30 [0xed321e30]
#13 HYBRIS (null)+-375848960 in libminecraftpe.so+0x0000 [0xe9990000]
#34 HYBRIS (null)+-254306768 in libminecraftpe.so+0x73e9630 [0xf0d79630]
#35 HYBRIS (null)+-315413088 in libminecraftpe.so+0x39a2da0 [0xed332da0]
#36 HYBRIS (null)+-315420112 in libminecraftpe.so+0x39a1230 [0xed331230]
#40 HYBRIS (null)+-315412944 in libminecraftpe.so+0x39a2e30 [0xed332e30]
#75 HYBRIS (null)+-315355344 in libminecraftpe.so+0x39b0f30 [0xed340f30]
#109 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#110 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#112 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#113 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#115 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#116 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#118 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#119 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#121 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#122 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#124 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#125 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#127 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#128 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#130 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#131 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#133 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#134 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#136 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#137 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#139 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#140 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#142 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#143 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#145 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#146 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#148 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#149 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#151 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#152 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#154 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#155 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#157 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#158 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#160 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#161 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#163 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#164 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#166 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#167 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#169 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#170 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#172 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#173 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#175 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#176 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#178 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#179 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#181 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#182 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#184 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#185 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#187 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#188 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#190 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#191 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#193 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#194 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#196 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#197 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#199 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#200 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#202 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#203 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#205 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#206 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#208 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#209 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#211 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#212 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#217 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#218 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#220 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#221 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#223 HYBRIS (null)+-285836996 in libminecraftpe.so+0x55d793c [0xeef6793c]
#224 HYBRIS (null)+-285837055 in libminecraftpe.so+0x55d7901 [0xeef67901]
#739 HYBRIS (null)+-375848960 in libminecraftpe.so+0x0000 [0xe9990000]
Process exited with unexpected exit code: 6

Can you help me please?

**Comment by ChristopherHX** [comment] 2019-11-05 15:14
Please wait at least till some days after its offical Release, **betas** (1.13.0.9+) are not **Supported in this Repo**
If you can't wait to play it, build my [**Fork**](https://github.com/ChristopherHX/mcpelauncher-manifest) of this Launcher which utilizes another approach since the **disappearing of a lot of used Debugging Information**.

**Comment by Xico26** [comment] 2019-11-05 21:15
Thank you very much. It worked.
But every time I want to play I need to put that commands?

**Comment by ChristopherHX** [comment] 2019-11-06 13:39
No more I now managed to generate .deb at
https://github.com/ChristopherHX/linux-packaging-scripts/releases
You can use the Qt gui to launch it, if you install the .deb or add your build to the PATH
You need only to install the mcpelauncher-client-*.deb

**Comment by Xico26** [comment] 2019-11-06 14:09
Thank you very much for your help. 😀

**Comment by docenig** [comment] 2019-11-08 01:02
The fork above runs 1.14.0.6 under Manjaro 18.1.2 (using this since the current regular build of mcpelauncher can't pull 1.13.0.34 due to its manifest file not being up to date), but when I click to sign in it never moves past the message stating it is signing in with my MS account. Tried the fork using both the command method and moving it into /usr/local/bin but neither will allow a sign-in. Bit of a problem since no signing in means no access to external servers.

**Comment by ChristopherHX** [comment] 2019-11-08 12:27
@docenig This is a known issue of my fork https://github.com/ChristopherHX/mcpelauncher-manifest/issues please write them there

For xbox live on 1.13.0.28 it should work with the current manifest, you must opt out beta first

**Comment by ChristopherHX** [comment] 2020-06-01 21:48
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 21:48 UTC
Labels: crash, duplicate
