### ISSUE TITLE
Minecraft linux launcher crashes - long error code in gamelog

### ISSUE THREAD

**Issue by sophtea666** [minecraft-linux/mcpelauncher-manifest#1055] opened 2024-10-23 20:07 UTC
I have just updated the minecraft linux launcher but now minecraft crashes 1 second after loading and goes back to the launcher

Here is the error code in the gamelog on the launcher:
21:00:55 Info  [Launcher] Version: client 4c5f4fd / manifest afe4e50
21:00:55 Info  [Launcher] OS: macOS, Arch: x86_6421:00:55 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
21:00:55 Info  [Launcher] CPU supports SSSE3: YES
21:00:55 Info  [Launcher] Reading Launcher Settings File: /Users/sophie/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
21:00:55 Info  [Launcher] Applied Launcher Settings
21:00:55 Trace [Launcher] Loading android libraries
21:00:55 Trace [Launcher] linker loaded
21:00:55 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/sophie/Library/Application Support/mcpelauncher/
21:00:55 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/proc/8426/cmdline to /Users/sophie/Library/Application Support/mcpelauncher/
21:00:55 Trace [REDIRECT] /data/data/Applications/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/sophie/Library/Application Support/mcpelauncher/
21:00:55 Trace [REDIRECT] /data/data to /Users/sophie/Library/Application Support/mcpelauncher/
21:00:55 Trace [REDIRECT] . to /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/assets/
21:00:55 Trace [REDIRECT] /proc to /Users/sophie/Library/Application Support/mcpelauncher/proc/
21:00:55 Trace [REDIRECT] /sys to /Users/sophie/Library/Application Support/mcpelauncher/sys/
21:00:55 Trace [LinkerUtils] Loaded OS library libm.dylib
21:00:55 Trace [LinkerUtils] Loaded OS library libz.dylib
21:00:55 Trace [LinkerUtils] Loaded OS library /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
21:00:55 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libc++_shared.so 0x10ce80000
21:00:56 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libminecraftpe.so"...
21:00:56 Info  [Launcher] Loading gamepad mappings
21:00:56 Trace [Launcher] Loading gamepad mappings: /Applications/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
21:00:56 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libc++_shared.so 0x10fd40000
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libminecraftpe.so 0x111840000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x1071bff10
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x1071bfef0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x1071bff30
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x10736a930
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x10736acf0
21:00:58 Info  [Launcher] Loaded Minecraft library
21:00:58 Debug [Launcher] Minecraft is at offset 0x111840000
21:00:58 Info  [Launcher] Game version: 0.0.0.0
21:00:58 Info  [Launcher] Applying patches
21:00:58 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
21:00:58 Info  [Launcher] Initializing JNI
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
21:00:58 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
21:00:58 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
21:00:58 Trace [Minecraft] Entering JNI_OnLoad 0x700001fbe000
21:00:58 Trace [Minecraft] JNI_OnLoad completed
21:00:58 Trace [JniSupport] Invoking nativeRegisterThis
21:00:58 Info  [Launcher] Executing main thread
21:00:58 Trace [JniSupport] Invoking ANativeActivity_onCreate
21:00:58 Warn  [Main] Android stub called
21:00:58 Warn  [Main] Android stub called
21:00:58 Warn  [Main] Android stub called
21:00:58 Warn  [Main] Android stub called
21:00:58 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
21:00:58 Trace [JniSupport] Invoking start activity callbacks
21:00:58 Error [MCPE] *** setCachedDeviceId(14ec9694-a752-4471-8420-dc231296858f)
21:00:58 Info  [Bedrock] Breakpad config: directory is: /crash, sessionid is: 2a74aef2-14d3-443f-921d-dc9088a5f7d0
21:00:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'
21:00:58 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
21:00:58 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
21:00:58 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
21:00:58 Warn  [FakeEGL] eglQueryString 308d
21:00:58 Warn  [Main] Android stub called
21:00:58 Info  [GL] Vendor: Google Inc.
21:00:58 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
21:00:58 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
21:00:58 Info  [GL] Vendor: Google Inc.
21:00:58 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
21:00:58 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
21:00:58 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libMediaDecoders_Android.so 0x124680000

21:00:58 Info  [GL] Vendor: Google Inc.
21:00:58 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
21:00:58 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
21:00:58 Warn  [Main] Android stub called
21:00:58 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
21:00:58 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
21:00:58 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Unknown socket family when converting sockaddr to host
Signal 6 received
21:00:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'
Backtrace elements: 16
#0 0   mcpelauncher-client                 0x000000010730bce8 _ZN12CrashHandler12handleSignalEiPv + 344
#1 1   mcpelauncher-client                 0x000000010730c115 _ZN12CrashHandler15handle_fs_faultEiPvS0_ + 133
#2 2   libsystem_platform.dylib            0x00007ff806e16e9d _sigtramp + 29
#3 3   ???                                 0x0000000000000400 0x0 + 1024
#4 4   libsystem_c.dylib                   0x00007ff806d02b19 abort + 126
#5 5   libc++abi.1.dylib                   0x0000000108c4f003 abort_message + 195
#6 6   libc++abi.1.dylib                   0x0000000108c3014e _ZL28demangling_terminate_handlerv + 238
#7 7   libc++abi.1.dylib                   0x0000000108c4dfc8 _ZSt11__terminatePFvvE + 8
#8 8   libc++abi.1.dylib                   0x0000000108c511eb _ZN10__cxxabiv1L12failed_throwEPNS_15__cxa_exceptionE + 27
#9 9   libc++abi.1.dylib                   0x0000000108c51165 __cxa_throw + 117
#10 10  mcpelauncher-client                 0x0000000107369be3 _ZN4shim6bionic12get_host_lenEPKNS0_8sockaddrE + 163
#11 11  mcpelauncher-client                 0x000000010736ce5d _ZN4shim6detail11sockaddr_inC2EPKNS_6bionic8sockaddrEj + 141
#12 12  mcpelauncher-client                 0x000000010736af63 _ZN4shim6detail11sockaddr_inC1EPKNS_6bionic8sockaddrEj + 35
#13 13  mcpelauncher-client                 0x000000010736b3e1 _ZN4shim6sendtoEiPKvmiPKNS_6bionic8sockaddrEj + 97
#14 14  mcpelauncher-client                 0x000000010736c820 _ZN4shim6detail19errno_update_helperIFliPKvmiPKNS_6bionic8sockaddrEjEE7wrapperIXadL_ZNS_6sendtoEiS3_miS7_jEEEEliS3_miS7_j + 80
#15 15  ???                                 0x000000011f88cb7a 0x0 + 4824025978
Dumping stack...
#229 LINKER (null)+0x113ce0a8d in /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.41.01/lib/x86_64/libminecraftpe.so+0x24a0a8d [0x113ce0a8d]
21:00:58 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'

Process exited with unexpected exit code: 6

I am currently on Macbook Pro 2020 - version 15.0.1 Sequoia

Please help. It was working until I updated the launcher today

**Comment by ChristopherHX** [comment] 2024-10-31 06:14
Help wanted. I request more logs the following debug build **doesn't crash** in this case, but I need the **full log** from that one as well.

Such a network debug build is created here: https://github.com/minecraft-linux/macos-builder/actions/runs/11544017967 (after it is successfully done there are zipped dmg files as artifact, otherwise nothing), when finished I manually add them as prerelease to the release page.

_As always required information has been forgetten to put into a fatal error showing a serious network translation error between bionic and macOS libc.

**Comment by ChristopherHX** [comment] 2024-10-31 06:15
The direct link of the dmg I want the logs is https://github.com/minecraft-linux/macos-builder/actions/runs/11544017967/artifacts/2109758931

**GitHub Account login required**

**Comment by sophtea666** [comment] 2024-10-31 11:04
@ChristopherHX  is this the log you are after? I used the link you just sent above

10:58:03 Info  [Launcher] Version: client 4c5f4fd / manifest f4c075a
10:58:03 Info  [Launcher] OS: macOS, Arch: x86_6410:58:03 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
10:58:03 Info  [Launcher] CPU supports SSSE3: YES
10:58:03 Info  [Launcher] Reading Launcher Settings File: /Users/sophie/Library/Application Support/mcpelauncher/mcpelauncher-client-settings.txt
10:58:03 Info  [Launcher] Applied Launcher Settings
10:58:03 Trace [Launcher] Loading android libraries
10:58:03 Trace [Launcher] linker loaded
10:58:03 Trace [REDIRECT] /data/data/com.mojang.minecraftpe to /Users/sophie/Library/Application Support/mcpelauncher/
10:58:03 Trace [REDIRECT] /data/data/private/var/folders/st/jnqlkhfd3mz7fjljmljb0cw40000gn/T/AppTranslocation/7F25FA33-CD25-46F9-99F1-395382627694/d/Minecraft Bedrock Launcher.app/Contents/proc/18435/cmdline to /Users/sophie/Library/Application Support/mcpelauncher/
10:58:03 Trace [REDIRECT] /data/data/private/var/folders/st/jnqlkhfd3mz7fjljmljb0cw40000gn/T/AppTranslocation/7F25FA33-CD25-46F9-99F1-395382627694/d/Minecraft Bedrock Launcher.app/Contents/MacOS/./mcpelauncher-client to /Users/sophie/Library/Application Support/mcpelauncher/
10:58:03 Trace [REDIRECT] /data/data to /Users/sophie/Library/Application Support/mcpelauncher/
10:58:03 Trace [REDIRECT] . to /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/assets/
10:58:03 Trace [REDIRECT] /proc to /Users/sophie/Library/Application Support/mcpelauncher/proc/
10:58:03 Trace [REDIRECT] /sys to /Users/sophie/Library/Application Support/mcpelauncher/sys/
10:58:03 Trace [LinkerUtils] Loaded OS library libm.dylib
10:58:04 Trace [LinkerUtils] Loaded OS library libz.dylib
10:58:04 Trace [LinkerUtils] Loaded OS library /private/var/folders/st/jnqlkhfd3mz7fjljmljb0cw40000gn/T/AppTranslocation/7F25FA33-CD25-46F9-99F1-395382627694/d/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/lib/native/x86_64/libfmod.dylib
10:58:04 Trace [Launcher] Loading Minecraft library
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/lib/x86_64/libc++_shared.so 0x10d240000
10:58:08 Error [MinecraftUtils] Failed to load Minecraft: dlopen failed: cannot locate symbol "glBindRenderbuffer" referenced by "/Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/lib/x86_64/libminecraftpe.so"...
10:58:08 Info  [Launcher] Loading gamepad mappings
10:58:08 Trace [Launcher] Loading gamepad mappings: /private/var/folders/st/jnqlkhfd3mz7fjljmljb0cw40000gn/T/AppTranslocation/7F25FA33-CD25-46F9-99F1-395382627694/d/Minecraft Bedrock Launcher.app/Contents/Resources/mcpelauncher/gamecontrollerdb.txt
10:58:08 Info  [Launcher] Creating window
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/lib/x86_64/libc++_shared.so 0x10f7c0000
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/lib/x86_64/libminecraftpe.so 0x111280000
Found hook: _ZN11AppPlatform16showMousePointerEv @ 0x10713d5f0
Found hook: _ZN11AppPlatform16hideMousePointerEv @ 0x10713d5d0
Found hook: _ZN11AppPlatform17setFullscreenModeE14FullscreenMode @ 0x10713d610
Found hook: _ZN3rtc10getifaddrsEPP7ifaddrs @ 0x1072e8270
Found hook: _ZN3rtc11freeifaddrsEP7ifaddrs @ 0x1072e8630
10:58:11 Info  [Launcher] Loaded Minecraft library
10:58:11 Debug [Launcher] Minecraft is at offset 0x111280000
10:58:11 Info  [Launcher] Game version: 0.0.0.0
10:58:11 Info  [Launcher] Applying patches
10:58:11 Debug [CorePatches] Failed to patch, vtable _ZTV21AppPlatform_android23 not found
10:58:11 Info  [Launcher] Initializing JNI
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeRegisterThis
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeWithApplicationContext
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeUnregisterThis
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeXboxLive
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeinitializeLibHttpClient
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_MainActivity_nativeInitializeLibHttpClient
10:58:11 Error [JniSupport] Missing native symbol: Java_com_microsoft_xal_browser_WebView_urlOperationSucceeded
10:58:11 Error [JniSupport] Missing native symbol: Java_com_mojang_minecraftpe_PlayIntegrity_nativePlayIntegrityComplete
10:58:11 Trace [Minecraft] Entering JNI_OnLoad 0x70000b95b000
10:58:11 Trace [Minecraft] JNI_OnLoad completed
10:58:11 Trace [JniSupport] Invoking nativeRegisterThis
10:58:11 Trace [JniSupport] Invoking ANativeActivity_onCreate
10:58:11 Info  [Launcher] Executing main thread
10:58:11 Warn  [Main] Android stub called
10:58:11 Warn  [Main] Android stub called
10:58:11 Warn  [Main] Android stub called
10:58:11 Warn  [Main] Android stub called
10:58:11 Info  [Minecraft] android_main starting. internalDataPath is '/internal', externalDataPath is '/external'
10:58:11 Trace [JniSupport] Invoking start activity callbacks
10:58:11 Error [MCPE] *** setCachedDeviceId(14ec9694-a752-4471-8420-dc231296858f)
10:58:11 Info  [Bedrock] Breakpad config: directory is: /crash, sessionid is: ac04cacf-d52f-4ad2-b3eb-7b91bdb780a2
10:58:11 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'
10:58:11 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
10:58:11 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was gained
2024-10-31 10:58:11.909 mcpelauncher-client[18435:776141] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-31 10:58:11.909 mcpelauncher-client[18435:776141] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
10:58:11 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
10:58:11 Warn  [FakeEGL] eglQueryString 308d
10:58:11 Warn  [Main] Android stub called
10:58:11 Info  [GL] Vendor: Google Inc.
10:58:11 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
10:58:11 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
10:58:12 Info  [GL] Vendor: Google Inc.
10:58:12 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
10:58:12 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
10:58:12 Warn  [Main] Android stub called
linker: mcpelauncher_linker_notifylldb /Users/sophie/Library/Application Support/mcpelauncher/versions/1.21.43.01/lib/x86_64/libMediaDecoders_Android.so 0x124900000


10:58:12 Info  [GL] Vendor: Google Inc.
10:58:12 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
10:58:12 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
10:58:12 Warn  [Main] Android stub called
10:58:12 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
10:58:12 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
10:58:12 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
10:58:12 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using AppData dir - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'
10:58:12 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir (NEW) - CurrentFileStoragePath is now '/Users/sophie/Library/Application Support/mcpelauncher/'
10:58:14 Info  [Minecraft] NO LOG FILE! - Time played notifier not required for 'en'
10:58:22 Info  [GL] Vendor: Google Inc.
10:58:22 Info  [GL] Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 645, OpenGL 4.1 core)
10:58:22 Info  [GL] Version: OpenGL ES 3.0.0 (ANGLE 2.1.14073 git hash: 26930173647b)
10:58:22 Warn  [Main] Android stub called
10:59:48 Info  [Minecraft] NO LOG FILE! - Opening level '/Users/sophie/Library/Application Support/mcpelauncher/games/com.mojang/minecraftWorlds/32JG8LfiI-c=/db'
10:59:48 Info  [Minecraft] NO LOG FILE! - [SERVER] Pack Stack - None
10:59:51 Info  [Minecraft] NO LOG FILE! - Player connected: sophtea666, xuid: 
10:59:53 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Starting...
10:59:53 Trace [Minecraft] NO LOG FILE! - DBStorage - Compaction Complete.
10:59:53 Trace [Minecraft] NO LOG FILE! - Scheduling AutoCompaction...
11:00:02 Info  [Minecraft] NO LOG FILE! - Player Spawned: sophtea666 xuid: 2535452690826629, pfid: ac1cc519e551c871
11:03:15 Trace [JniSupport] Invoking stop activity callbacks
11:03:16 Warn  [Minecraft] NO LOG FILE! - [Graphics] The graphics context was lost
11:03:16 Info  [Minecraft] NO LOG FILE! - Player disconnected: sophtea666, xuid: , pfid: ac1cc519e551c871

Process exited normally

**Comment by sophtea666** [comment] 2024-10-31 11:17
@ChristopherHX Minecraft doesn't crash anymore with that new link but it says 'unable to connect' to any of my friends worlds and they can't connect to my world either whereas before this worked. They are on PS5

**Comment by ChristopherHX** [comment] 2024-10-31 13:29
> Minecraft doesn't crash anymore with that new link

Yes I know, the error is still there only the crash has been replaced by a log line.

Everything else needs more information material.

> @ChristopherHX is this the log you are after? I used the link you just sent above

Did you do something differently than in your original post while recording this log?

The reason for this crash doesn't seem to happen in that log file.

Can you post the log if you see the failed to connect error?

**Comment by ChristopherHX** [comment] 2024-11-05 21:22
Seems like I need to debug this problem myself, this can take a while as I'm pretty busy.

My current understanding, location of fatal error known. Source of fatal error unknown, I need to know this to write a fix.

Logging the required information is a complex problem, currently this needs a lldb debugger attached to the mcpelauncher-client process.

However the first required step for me is to reproduce it on my aged intel macOS 10.14.
If this is not possible I'm only able to extend error diagnosis e.g. notify by showing content over the game UI when such runtime errors happen and that it is needed to share this information to fix launcher problems

**Comment by ChristopherHX** [comment] 2024-12-04 20:50
fixed install v0.17.2

**Closed as completed by ChristopherHX** 2024-12-04 20:50 UTC
Labels: bug
