### ISSUE TITLE
Crashes in 1.14.1.5 on macOS Mojave:

### ISSUE THREAD

**Issue by Firebirdnj8** [minecraft-linux/mcpelauncher-manifest#246] opened 2020-03-20 15:37 UTC
When clicking play, I get this error:
ted
Signal 6 received
Backtrace elements: 14
#0 0   mcpelauncher-client                 0x0015688e _ZN12CrashHandler12handleSignalEiPv + 318
#1 1   libsystem_platform.dylib            0xa7cc7bae _sigtramp + 46
#2 2   ???                                 0xffffffff 0x0 + 4294967295
#3 3   libsystem_c.dylib                   0xa7b8180e abort + 133
#4 4   libc++abi.dylib                     0xa5a46177 __cxa_bad_cast + 0
#5 5   libc++abi.dylib                     0xa5a4631f _ZL25default_terminate_handlerv + 232
#6 6   libc++abi.dylib                     0xa5a511fd _ZSt11__terminatePFvvE + 14
#7 7   libc++abi.dylib                     0xa5a50fbc __cxa_get_exception_ptr + 0
#8 8   libc++abi.dylib                     0xa5a44a01 __cxa_get_globals + 0
#9 9   mcpelauncher-client                 0x001d218c _Z21minecraft_get_versionPiS_S_S_ + 396
#10 10  mcpelauncher-client                 0x001587f9 _ZN16MinecraftVersion4initEv + 57
#11 11  mcpelauncher-client                 0x00157f85 _ZN14MinecraftUtils18initSymbolBindingsEPv + 69
#12 12  mcpelauncher-client                 0x0009c790 main + 10208
#13 13  libdyld.dylib                       0xa7ade051 start + 1
Dumping stack...
#598 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7421d30 [0xaad6d30]
#599 HYBRIS vtable for xbox::services::local_config+8 in libminecraftpe.so+0x7421d30 [0xaad6d30]

**Comment by Firebirdnj8** [comment] 2020-03-22 17:17
I have opened this quite a while ago, I was wondering if anyone has looked at it so I know I am not being ignored.

**Comment by ChristopherHX** [comment] 2020-06-03 14:56
duplicate of #165,
~~This issue is even pinned~~
The legacy master ( **now unsupported** ) have had only added 1.14.1.5 support for **GNU/linux** (not macOS)
1.13.0.6 last version working with it.
Please visit https://github.com/ChristopherHX/mcpelauncher-manifest/releases/tag/stable for a version which can run latest Minecraft 1.14.60.5 or 1.16 beta on GNU/Linux and macOS

**Closed by ChristopherHX** 2020-06-03 14:56 UTC
