### ISSUE TITLE
Cannot launch game or troubleshoot (bad CPU type)

### ISSUE THREAD

**Issue by le0-VV** [minecraft-linux/mcpelauncher-manifest#173] opened 2019-11-01 04:42 UTC
<img width="641" alt="Screenshot 2019-11-01 at 3 35 35 pm" src="https://user-images.githubusercontent.com/40534994/68002572-9debb700-fcbd-11e9-91ad-a41e5e522714.png">
<img width="641" alt="Screenshot 2019-11-01 at 3 35 44 pm" src="https://user-images.githubusercontent.com/40534994/68002593-b1971d80-fcbd-11e9-9073-8833b88fd8d8.png">
<img width="762" alt="Screenshot 2019-11-01 at 3 36 11 pm" src="https://user-images.githubusercontent.com/40534994/68002596-b3f97780-fcbd-11e9-952d-8daf74c25a59.png">
I think the pics said enough
I suspect this is due to the macOS Catalina not supporting 32bit apps thing, but before first time launching I fiddled around with game directory to put it along my java edition directories, maybe that took a part as well?

**Comment by ChristopherHX** [comment] 2020-06-03 14:30
duplicate of #100

**Closed by ChristopherHX** 2020-06-03 14:30 UTC
