### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by jollyzen** [minecraft-linux/mcpelauncher-manifest#261] opened 2020-03-28 23:22 UTC
I get the pop up to sign in with my microsoft account (which is actually my gmail sign in). I Can see my friend to invite if I create a world. They never get the invite. They are playing on PS4 and I am on linux (ubuntu 19.10)

**Comment by ChristopherHX** [comment] 2020-06-08 19:16
Handling invites is not supported, e.g. this launcher can't receive them to join a world.

**Comment by ChristopherHX** [comment] 2020-07-14 20:40
duplicate of #134

**Closed** 2020-07-14 20:40 UTC
Labels: enhancement
