### ISSUE TITLE
why not working on endless os ?

### ISSUE THREAD

**Issue by Andrei700** [minecraft-linux/mcpelauncher-manifest#364] opened 2020-07-28 13:04 UTC
why?

**Comment by ChristopherHX** [comment] 2020-08-01 20:14
You never supplied more information than "nothing works and have the launcher somehow installed"
How should I know what doesn't work for you, because it works fine for me.

Duplicate of https://github.com/minecraft-linux/mcpelauncher-manifest/issues/347

**Closed by ChristopherHX** 2020-08-01 20:14 UTC
Labels: duplicate, invalid, question
