### ISSUE TITLE
Crash opening minecraft

### ISSUE THREAD

**Issue by ElUnikornio** [minecraft-linux/mcpelauncher-manifest#249] opened 2020-03-22 22:05 UTC
when i try open minenecraft and show this the game log:

16:04:35 Info  [Launcher] Version: client c735370 / manifest e405b8c
16:04:35 Info  [Launcher] CPU: GenuineIntel Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
16:04:35 Info  [Launcher] CPU supports SSSE3: YES
16:04:35 Trace [Launcher] Loading hybris libraries
16:04:35 Trace [HybrisUtils] Loaded OS library /usr/share//mcpelauncher/libs/native/libfmod.so.9.16
16:04:35 Trace [HybrisUtils] Loaded OS library libm.so.6
16:04:35 Trace [HybrisUtils] Loaded OS library libz.so.1
16:04:35 Trace [Launcher] Loading Minecraft library
16:04:36 Info  [Launcher] Loaded Minecraft library
16:04:36 Debug [Launcher] Minecraft is at offset 0xed6df000
16:04:36 Trace [Launcher] Initializing vtables
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN3App4initER10AppContext
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App4quitERKSsS1_
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App6updateEv
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App16setRenderingSizeEii
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App17setUISizeAndScaleEiif
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN3App10wantToQuitEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServiceLocatorI11AppPlatformE15mDefaultServiceE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN11AppPlatform12showKeyboardERKSsibbbiRKN3glm5tvec2IfLNS2_9precisionE0EEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK11AppPlatform22getHardwareInformationEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17AppResourceLoaderC1ESt8functionIFN4Core10PathBufferISsEEvEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN10Automation16AutomationClientC2ER13IMinecraftApp
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance7getUserEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance15_startLeaveGameEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ClientInstance16_syncDestroyGameEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK13CommandOutput11getMessagesEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender9translateERKSt6vectorISsSaISsEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderC2ERN10Automation16AutomationClientE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSenderD2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender4sendERK13CommandOriginRK13CommandOutput
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19CommandOutputSender22registerOutputCallbackERKSt8functionIFvR19AutomationCmdOutputEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Common23getGameVersionStringNetEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSourceC2EPN4Core15FilePathManagerESt10shared_ptrI22SaveTransactionManagerE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsRK15ContentIdentityRK19IContentKeyProvider
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManagerC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourceLoadManager4syncE16ResourceLoadType
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n3getERKSsRKSt6vectorISsSaISsEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n14chooseLanguageERKSs
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerR19ResourceLoadManagerRKSs
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN5Level16createRandomSeedEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettingsC2ERKS_
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13LevelSettings15parseSeedStringERKSsj
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN9Minecraft11getCommandsEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK9Minecraft8getLevelEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftCommands15setOutputSenderESt10unique_ptrI19CommandOutputSenderSt14default_deleteIS1_EE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK17MinecraftCommands23requestCommandExecutionESt10unique_ptrI13CommandOriginSt14default_deleteIS1_EERKSsib
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventingC2ERKSs
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17MinecraftEventing4initEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameC2EiPPc
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGameD2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK13MinecraftGame8isInGameEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame16requestLeaveGameEbb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24doPrimaryClientReadyWorkESt8functionIFvvEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame21getPrimaryUserOptionsEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame24getPrimaryClientInstanceEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14startLeaveGameEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame17continueLeaveGameEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN13MinecraftGame14setTextboxTextERKSsi
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel32navigateToXblConsoleSignInScreenERKSsS1_
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel41navigateToXblConsoleSignInSucceededScreenERKN6Social12SignInResultESt8functionIFvS1_EEb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN20MinecraftScreenModel11leaveScreenEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social14MultiplayerXBLC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZTV22NullTextToSpeechClient
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK7Options13getFullscreenEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN7Options13setFullscreenEb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15PermissionsFileC2ERKSs
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19SkinPackKeyProviderC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19PackManifestFactoryC2ER14IPackTelemetry
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17PackSourceFactoryC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepositoryC2ER18IMinecraftEventingR19PackManifestFactoryR29IContentAccessibilityProviderPN4Core15FilePathManagerER17PackSourceFactoryb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository21addWorldResourcePacksERKN4Core4PathE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22ResourcePackRepository12refreshPacksEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN18ContentTierManagerC2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManagerC2ESt8functionIFN4Core10PathBufferISsEEvEERK18ContentTierManagerb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager8setStackESt10unique_ptrI17ResourcePackStackSt14default_deleteIS1_EE21ResourcePackStackTypeb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ResourcePackManager17onLanguageChangedEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackibP12PackSettings
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZTV17ResourcePackStack
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN17ResourcePackStack3addE12PackInstanceRK22ResourcePackRepositoryb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN22SaveTransactionManagerC2ESt8functionIFvbEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler17processCoroutinesENSt6chrono8durationIxSt5ratioILx1ELx1000000000EEEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN18MinecraftScheduler6clientEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN19ServerCommandOriginC2ERKSsR11ServerLevel22CommandPermissionLevel
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN16EducationOptionsC2EP19ResourcePackManager
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR30ServerInstanceEventCoordinator
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance16initializeServerER13IMinecraftAppR9WhitelistP15PermissionsFilePN4Core15FilePathManagerENSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsib20ConnectionDefinitionbRKSt6vectorISsSaISsEESsRKN3mce4UUIDER18IMinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS10_EER9SchedulerEERKSsP9LevelDataSsSsSZ_I16EducationOptionsS11_IS1C_EEPSW_SY_IFvvEES1H_P13ServerMetricsP13DebugEndPointb
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceD2Ev
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance17startServerThreadEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance13leaveGameSyncEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance20queueForServerThreadESt8functionIFvvEE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MajorVersionE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12MinorVersionE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants12PatchVersionE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN15SharedConstants15RevisionVersionE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK6Social4User11getLiveUserEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social12XboxLiveUser22_handleUISignInNoErrorERN4xbox8services6system14sign_in_resultESt8functionIFvNS_12SignInResultEbEE
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore18onStoreInitializedEb
16:04:36 Error [MinecraftSymbols] Unresolved vtable symbol: _ZN9GameStore22onQueryProductsSuccessERKSt6vectorI11ProductInfoSaIS1_EE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN6Social11UserManager17CreateUserManagerEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V810InitializeEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2v82V818InitializePlatformEPNS_8PlatformE
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZNK4pplx4taskIN4xbox8services16xbox_live_resultINS2_6system26token_and_signature_resultEEEE3getEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl15getOpenGLVendorEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl17getOpenGLRendererEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl16getOpenGLVersionEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN2gl19getOpenGLExtensionsEv
16:04:36 Error [MinecraftSymbols] Unresolved symbol: _ZN3mce8Platform3OGL12InitBindingsEv
terminate called after throwing an instance of 'std::runtime_error'
  what():  Found no way to resolve library version, Minecraft version likely unsupported
Signal 6 received
Backtrace elements: 15
#0 /usr/bin/mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc5) [0x5681de41]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7edcb70]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7edcb59]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2) [0xf77b8832]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x121) [0xf77b9cc1]
#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x6e97d) [0xf7b1697d]
#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x760e4) [0xf7b1e0e4]
#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7614d) [0xf7b1e14d]
#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x7644c) [0xf7b1e44c]
#9 /usr/bin/mcpelauncher-client(_Z21minecraft_get_versionPiS_S_S_+0x13a) [0x568725b1]
#10 /usr/bin/mcpelauncher-client(_ZN16MinecraftVersion4initEv+0x34) [0x5681f63a]
#11 /usr/bin/mcpelauncher-client(_ZN14MinecraftUtils18initSymbolBindingsEPv+0x44) [0x5681f532]
#12 /usr/bin/mcpelauncher-client(main+0x10c2) [0x567c65de]
#13 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0xf77a3e81]
#14 /usr/bin/mcpelauncher-client(+0x1c8f31) [0x567c4f31]
Dumping stack...
#1 HYBRIS (null)+-250544912 in libminecraftpe.so+0x3a30cf0 [0xf110fcf0]
#2 HYBRIS (null)+-250552400 in libminecraftpe.so+0x3a2efb0 [0xf110dfb0]
#13 HYBRIS (null)+-311562240 in libminecraftpe.so+0x0000 [0xed6df000]
#31 HYBRIS (null)+-250494336 in libminecraftpe.so+0x3a3d280 [0xf111c280]
#32 HYBRIS (null)+-250501360 in libminecraftpe.so+0x3a3b710 [0xf111a710]
#36 HYBRIS (null)+-250494192 in libminecraftpe.so+0x3a3d310 [0xf111c310]
#37 HYBRIS (null)+-250494240 in libminecraftpe.so+0x3a3d2e0 [0xf111c2e0]
#40 HYBRIS (null)+-302645777 in libminecraftpe.so+0x880def [0xedf5fdef]
#77 HYBRIS (null)+-250436496 in libminecraftpe.so+0x3a4b470 [0xf112a470]
#111 HYBRIS (null)+-250386432 in libminecraftpe.so+0x3a57800 [0xf1136800]
#112 HYBRIS (null)+-250397152 in libminecraftpe.so+0x3a54e20 [0xf1133e20]
#116 HYBRIS (null)+-250386288 in libminecraftpe.so+0x3a57890 [0xf1136890]
#117 HYBRIS (null)+-250386336 in libminecraftpe.so+0x3a57860 [0xf1136860]
#121 HYBRIS (null)+-250374864 in libminecraftpe.so+0x3a5a530 [0xf1139530]
#122 HYBRIS (null)+-250374912 in libminecraftpe.so+0x3a5a500 [0xf1139500]
#126 HYBRIS (null)+-250352768 in libminecraftpe.so+0x3a5fb80 [0xf113eb80]
#127 HYBRIS (null)+-250363488 in libminecraftpe.so+0x3a5d1a0 [0xf113c1a0]
#130 HYBRIS (null)+-189396732 in libminecraftpe.so+0x7481904 [0xf4b60904]
#131 HYBRIS (null)+-250351760 in libminecraftpe.so+0x3a5ff70 [0xf113ef70]
#132 HYBRIS (null)+-250352672 in libminecraftpe.so+0x3a5fbe0 [0xf113ebe0]
#136 HYBRIS (null)+-250351616 in libminecraftpe.so+0x3a60000 [0xf113f000]
#137 HYBRIS (null)+-250351664 in libminecraftpe.so+0x3a5ffd0 [0xf113efd0]
#140 HYBRIS void std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_dfs<false>(long)+12 in libminecraftpe.so+0xa0ed5c [0xee0edd5c]
#141 HYBRIS (null)+-250332752 in libminecraftpe.so+0x3a649b0 [0xf11439b0]
#142 HYBRIS (null)+-250340240 in libminecraftpe.so+0x3a62c70 [0xf1141c70]
#146 HYBRIS (null)+-250332608 in libminecraftpe.so+0x3a64a40 [0xf1143a40]
#147 HYBRIS (null)+-250332656 in libminecraftpe.so+0x3a64a10 [0xf1143a10]
#151 HYBRIS (null)+-250302208 in libminecraftpe.so+0x3a6c100 [0xf114b100]
#152 HYBRIS (null)+-250302256 in libminecraftpe.so+0x3a6c0d0 [0xf114b0d0]
#156 HYBRIS (null)+-250271808 in libminecraftpe.so+0x3a737c0 [0xf11527c0]
#157 HYBRIS (null)+-250271856 in libminecraftpe.so+0x3a73790 [0xf1152790]
#161 HYBRIS (null)+-250241408 in libminecraftpe.so+0x3a7ae80 [0xf1159e80]
#162 HYBRIS (null)+-250241456 in libminecraftpe.so+0x3a7ae50 [0xf1159e50]
#166 HYBRIS (null)+-250207360 in libminecraftpe.so+0x3a83380 [0xf1162380]
#167 HYBRIS (null)+-250211056 in libminecraftpe.so+0x3a82510 [0xf1161510]
#170 HYBRIS (null)+-189396732 in libminecraftpe.so+0x7481904 [0xf4b60904]
#171 HYBRIS (null)+-250206352 in libminecraftpe.so+0x3a83770 [0xf1162770]
#172 HYBRIS (null)+-250207264 in libminecraftpe.so+0x3a833e0 [0xf11623e0]
#176 HYBRIS (null)+-250202560 in libminecraftpe.so+0x3a84640 [0xf1163640]
#180 HYBRIS std::__detail::_Executor<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, std::regex_traits<char>, true>::_M_lookahead(std::__detail::_State<std::regex_traits<char> >)+531 in libminecraftpe.so+0xa0ed03 [0xee0edd03]
#181 HYBRIS (null)+-250191696 in libminecraftpe.so+0x3a870b0 [0xf11660b0]
#182 HYBRIS (null)+-250202464 in libminecraftpe.so+0x3a846a0 [0xf11636a0]
#192 HYBRIS (null)+-301116948 in libminecraftpe.so+0x9f61ec [0xee0d51ec]
#196 HYBRIS (null)+-188506684 in libminecraftpe.so+0x755adc4 [0xf4c39dc4]
#198 HYBRIS (null)+-189396732 in libminecraftpe.so+0x7481904 [0xf4b60904]
#202 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x5608c36 [0xf2ce7c36]
#203 HYBRIS (null)+-189396732 in libminecraftpe.so+0x7481904 [0xf4b60904]
#206 HYBRIS (null)+-188506696 in libminecraftpe.so+0x755adb8 [0xf4c39db8]
#208 HYBRIS (null)+-188506684 in libminecraftpe.so+0x755adc4 [0xf4c39dc4]
#210 HYBRIS (null)+-246494816 in libminecraftpe.so+0x3e0d9a0 [0xf14ec9a0]
#211 HYBRIS (null)+-188506684 in libminecraftpe.so+0x755adc4 [0xf4c39dc4]
#213 HYBRIS Core::FileStorageArea::sStorageAreas+0 in libminecraftpe.so+0x74fabf8 [0xf4bd9bf8]
#221 HYBRIS (null)+-250163520 in libminecraftpe.so+0x3a8dec0 [0xf116cec0]
#735 HYBRIS (null)+-311562240 in libminecraftpe.so+0x0000 [0xed6df000]
Process exited with unexpected exit code: 6

**Comment by intchanter** [comment] 2020-03-23 01:20
I get this as well. I'm running Ubuntu 19.10 (Eoan Ermine).

**Comment by intchanter** [comment] 2020-03-23 01:24
Related to pinned issue: https://github.com/minecraft-linux/mcpelauncher-manifest/issues/165

Short answer: Launcher needs to be updated for every new version of Minecraft: Bedrock edition. Older versions should work, but not the latest at the moment.

**Comment by rothesayrepair** [comment] 2020-03-23 09:19
I'm having this exact same issue. Very frustrating as it was working fantastic a while ago!?

**Comment by survivalbloke** [comment] 2020-03-26 13:47
> Related to pinned issue: #165
> 
> Short answer: Launcher needs to be updated for every new version of Minecraft: Bedrock edition. Older versions should work, but not the latest at the moment.

Is there a way we can update it?  I'm not a programmer but not all things like this directly involve programming.

**Comment by ChristopherHX** [comment] 2020-06-01 22:02
duplicate of #165

**Closed by ChristopherHX** 2020-06-01 22:02 UTC
